import type { Asset } from './schema';

const content: Asset[] = [
  {
    id: 'figure-note-1',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-1',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-1',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-1',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-2',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-2',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-2',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-2',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-8',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-8',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-8',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-8',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-16',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-16',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-16',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-16',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-32',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-32',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-32',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-32',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-64',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-64',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-64',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-64',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-note-128',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'note-128',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-rest-128',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'rest-128',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-whole-bar-3',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'whole-bar-3',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-whole-bar-6',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'whole-bar-6',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-dotted',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'dotted',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-double-dotted',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'double-dotted',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-beamed',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'beamed',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-flagged',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'flagged',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-triplet',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'triplet',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-duplet',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'duplet',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tied',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tied',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-detached',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'detached',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tenuto',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tenuto',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-trill',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'trill',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-mordent',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'mordent',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-turn',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'turn',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-grace',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'grace',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tremolo',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tremolo',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-multi-rest',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'multi-rest',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-soft',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-soft',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-strong',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-strong',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-successive',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-successive',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-together',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-together',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-pulse',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-pulse',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-whole',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-whole',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-halves',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-halves',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-quarters',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-quarters',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-untied',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-untied',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-tied',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-tied',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-eighths',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-eighths',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-triplets',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-triplets',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-sustained',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-sustained',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-detached',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-detached',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-figure',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-figure',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-repeated',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-repeated',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-example-ending',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'example-ending',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-grand-staff',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'grand-staff',
    description: {
      en: 'Two staves share one timeline. Middle C can be written below treble or above bass without changing pitch.',
      ru: 'Два стана имеют общую временную ось. До первой октавы можно записать под скрипичным или над басовым станом без изменения высоты.',
      de: 'Zwei Systeme teilen dieselbe Zeitachse. c′ kann unter dem Violin- oder über dem Basssystem stehen, ohne die Tonhöhe zu ändern.',
      ruMarkup:
        'Два стана имеют общую временную ось. [[До]] первой октавы можно записать под скрипичным или над басовым станом без изменения высоты.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-organ-staves',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'organ-staves',
    description: {
      en: 'Two manual staves and a pedal staff: read vertically aligned events together, not as three successive lines.',
      ru: 'Два мануальных стана и педальный: совмещённые по вертикали события читаются вместе, а не как три последовательные строки.',
      de: 'Zwei Manualsysteme und ein Pedalsystem: senkrecht ausgerichtete Ereignisse gehören zusammen, nicht in drei aufeinanderfolgende Zeilen.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-stem-directions',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'stem-directions',
    description: {
      en: 'Compare right-side upward stems and left-side downward stems. In multiple voices, stem direction can identify the voice.',
      ru: 'Сравните штили вверх справа от головки и вниз слева. В многоголосии направление может обозначать голос.',
      de: 'Vergleiche aufwärts gerichtete Hälse rechts und abwärts gerichtete links. Bei mehreren Stimmen kann die Richtung die Stimme kennzeichnen.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-signature-bass',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'signature-bass',
    description: {
      en: 'The bass-clef signature keeps the same order of altered letters, but places the signs for the bass clef.',
      ru: 'Порядок изменённых ступеней сохраняется; положение ключевых знаков соответствует басовому ключу.',
      de: 'Die Vorzeichnung behält die Reihenfolge der alterierten Stammtöne; die Positionen passen zum Bassschlüssel.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-accidental-tie-scope',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'accidental-tie-scope',
    description: {
      en: 'Follow the altered note across the tie: its continuation is not a new attack. Then compare the following untied note.',
      ru: 'Проследите изменённую ноту через лигу продления: продолжение не имеет новой атаки. Затем сравните следующую незалигованную ноту.',
      de: 'Verfolge den alterierten Ton über den Haltebogen: die Fortsetzung ist kein neuer Anschlag. Vergleiche danach die neu angeschlagene Note.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-accidental-octave-scope',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'accidental-octave-scope',
    description: {
      en: 'A local accidental affects its written octave. Compare the same letter in another octave with the signature rule.',
      ru: 'Случайный знак относится к своей записанной октаве. Сравните ту же ступень в другой октаве с правилом ключевых знаков.',
      de: 'Ein Versetzungszeichen betrifft seine notierte Oktavlage. Vergleiche denselben Stammton in einer anderen Oktave mit der Vorzeichnungsregel.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-accidental-replacement',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'accidental-replacement',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-accidental-natural',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'accidental-natural',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-accidental-signature-reset',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'accidental-signature-reset',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-beamed-mixed',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'beamed-mixed',
    description: {
      en: 'Mixed short values can share a beam. Count their total and locate the beat before judging the grouping.',
      ru: 'Разные короткие длительности могут иметь общее ребро. Сосчитайте сумму и найдите долю, прежде чем оценивать группировку.',
      de: 'Verschiedene kurze Werte können einen Balken teilen. Zähle die Gesamtdauer und finde die Zählzeit, bevor du die Gruppierung beurteilst.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-beamed-syllables',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'beamed-syllables',
    description: {
      en: 'Compare rhythmic grouping with a text-based grouping convention. Syllables and meter answer different reading questions; this comparison is unscored.',
      ru: 'Сравните ритмическую группировку с группировкой по тексту. Слоги и метр решают разные задачи чтения; сравнение не оценивается.',
      de: 'Vergleiche rhythmische mit textbezogener Gruppierung. Silben und Metrum beantworten verschiedene Lesefragen; der Vergleich wird nicht bewertet.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tuplet-mixed',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tuplet-mixed',
    description: {
      en: 'Count the tuplet span, including rests and subdivided or tied members. The bracket ratio scales the whole group.',
      ru: 'Считайте всю группу, включая паузы, дробление и лиги. Отношение над скобкой изменяет длительность всей группы.',
      de: 'Zähle die gesamte Gruppe mit Pausen, Unterteilungen und Haltebögen. Das Klammerverhältnis skaliert die ganze Gruppe.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tuplet-13-12',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tuplet-13-12',
    description: {
      en: 'At 13:12, thirteen written values occupy the time of twelve such values. The denominator is essential evidence.',
      ru: 'При 13:12 тринадцать записанных длительностей занимают время двенадцати таких же. Второе число необходимо для прочтения.',
      de: 'Bei 13:12 nehmen dreizehn notierte Werte die Zeit von zwölf solchen Werten ein. Die zweite Zahl ist für das Lesen wesentlich.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-quartole',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'quartole',
    description: {
      en: 'Four equal members divide the indicated span. Read the ratio and written values rather than assuming four ordinary notes.',
      ru: 'Четыре равных элемента делят указанный промежуток времени. Читайте отношение и длительности, не предполагая четыре обычные ноты.',
      de: 'Vier gleiche Teile teilen die angegebene Dauer. Lies Verhältnis und Notenwerte statt vier gewöhnliche Noten anzunehmen.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-octole',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'octole',
    description: {
      en: 'Eight equal members divide the indicated span. Compare its total with the dotted value; the comparison is unscored.',
      ru: 'Восемь равных элементов делят указанную длительность. Сравните сумму с длительностью с точкой; сравнение не оценивается.',
      de: 'Acht gleiche Teile teilen die angegebene Dauer. Vergleiche die Summe mit dem punktierten Wert; der Vergleich wird nicht bewertet.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-dotted-rest',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'dotted-rest',
    description: {
      en: 'A dot extends silence by half the rest’s value, just as it extends a note.',
      ru: 'Точка увеличивает молчание на половину длительности паузы, как и у ноты.',
      de: 'Ein Punkt verlängert die Stille um den halben Pausenwert, genauso wie bei einer Note.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-cross-bar-tie',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'cross-bar-tie',
    description: {
      en: 'The sustained sound is split into written parts at the barline. Add the tied values without a new attack.',
      ru: 'Протяжённый звук разделён на записанные части тактовой чертой. Сложите залигованные длительности без новой атаки.',
      de: 'Der gehaltene Klang ist am Taktstrich in notierte Teile aufgeteilt. Addiere die übergebundenen Werte ohne neuen Anschlag.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-historical-multirests',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'historical-multirests',
    description: {
      en: 'Compare the older combined rest signs with numbered silent measures. Count measures, not the number of printed glyphs.',
      ru: 'Сравните старые составные знаки пауз с обозначением пустых тактов числом. Считайте такты, а не напечатанные знаки.',
      de: 'Vergleiche ältere zusammengesetzte Pausenzeichen mit bezifferten Pausentakten. Zähle Takte, nicht gedruckte Zeichen.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-repeat-volta',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'repeat-volta',
    description: {
      en: 'On the first pass take ending 1; after returning, skip it and take ending 2. Trace the route before playing.',
      ru: 'В первый раз возьмите первую вольту; после возврата пропустите её и возьмите вторую. Сначала проследите путь.',
      de: 'Nimm zuerst Klammer 1; überspringe sie nach dem Rücksprung und nimm Klammer 2. Verfolge den Weg vor dem Spielen.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-repeat-implicit',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'repeat-implicit',
    description: {
      en: 'Without an opening repeat sign, this closing repeat returns to the beginning of the passage.',
      ru: 'При отсутствии начального знака репризы этот конечный знак возвращает к началу фрагмента.',
      de: 'Ohne öffnendes Wiederholungszeichen führt dieses schließende Zeichen zum Anfang des Abschnitts zurück.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-repeat-dc-fine',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'repeat-dc-fine',
    description: {
      en: 'D.C. al Fine returns to the beginning and stops at Fine on the return, not on the first traversal.',
      ru: 'D.C. al Fine возвращает к началу и останавливает у Fine после возврата, а не при первом прохождении.',
      de: 'D.C. al Fine führt zum Anfang zurück und endet beim Rücklauf bei Fine, nicht beim ersten Durchgang.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-repeat-ds-coda',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'repeat-ds-coda',
    description: {
      en: 'D.S. al Coda returns to the segno, then transfers at the indicated coda instruction. Follow the signs in their stated order.',
      ru: 'D.S. al Coda возвращает к сеньо, затем направляет в коду по указанному знаку. Следуйте предписанному порядку.',
      de: 'D.S. al Coda führt zum Segno zurück und springt danach an der bezeichneten Stelle zur Coda. Folge der angegebenen Reihenfolge.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-repeat-abbreviation',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'repeat-abbreviation',
    description: {
      en: 'The repeat abbreviation replaces a previously written pattern. Its duration still occupies the indicated measure.',
      ru: 'Сокращение заменяет ранее записанный рисунок. Его длительность по-прежнему занимает указанный такт.',
      de: 'Das Wiederholungskürzel ersetzt ein bereits notiertes Muster. Seine Dauer füllt weiterhin den angegebenen Takt.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tremolo-two',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tremolo-two',
    description: {
      en: 'Strokes between two notes indicate alternation. Read the values and any measured or unmeasured instruction before choosing a speed.',
      ru: 'Черты между двумя нотами обозначают чередование. Перед выбором скорости прочитайте длительности и указание на тремоло с точным ритмом или без точного числа повторений.',
      de: 'Striche zwischen zwei Noten bezeichnen einen Wechsel. Lies Notenwerte und die Angabe zur gemessenen oder ungemessenen Ausführung, bevor du das Tempo wählst.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-upper-mordent',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'upper-mordent',
    description: {
      en: 'The unstruck neighboring-note sign identifies the upper-neighbor form here; it does not prescribe one historical realization.',
      ru: 'Неперечёркнутый знак здесь обозначает мордент с верхним вспомогательным звуком; он не предписывает единственное историческое исполнение.',
      de: 'Das nicht durchstrichene Nebentonzeichen bezeichnet hier den Pralltriller mit oberem Nebenton, keine einzige historische Ausführung.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-long-grace',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'long-grace',
    description: {
      en: 'An unslashed small note is distinguished from the slashed grace form. Its exact timing requires the edition and performance context.',
      ru: 'Неперечёркнутая мелкая нота отличается от перечёркнутого форшлага. Точное время исполнения определяется редакцией и контекстом.',
      de: 'Eine kleine Note ohne Strich unterscheidet sich von der durchstrichenen Vorschlagsform. Der genaue Zeitpunkt verlangt Ausgabe und Aufführungskontext.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-after-grace',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'after-grace',
    description: {
      en: 'The small after-grace notes follow the principal written note. Do not turn their small size into a fixed timing formula.',
      ru: 'Мелкие ноты нахшлага следуют после основной записанной ноты. Их размер не превращается в фиксированную формулу времени.',
      de: 'Die kleinen Nachschlagsnoten folgen auf die notierte Hauptnote. Ihre Größe ist keine feste Zeitformel.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-slide',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'slide',
    description: {
      en: 'The slide approaches the principal tone stepwise. Recognize the approach, then consult the edition for timing.',
      ru: 'Шлейфер подходит к основному звуку поступенно. Узнайте подход, затем уточните время по редакции.',
      de: 'Der Schleifer führt schrittweise zum Hauptton. Erkenne die Hinführung und kläre den Zeitpunkt anhand der Ausgabe.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-arpeggio',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'arpeggio',
    description: {
      en: 'The vertical wavy sign spreads chord attacks in time. An arrow can specify the direction; this is not a change of chord membership.',
      ru: 'Вертикальная волнистая черта разносит атаки звуков аккорда во времени. Стрелка может задать направление; состав аккорда не меняется.',
      de: 'Die senkrechte Wellenlinie verteilt die Akkordanschläge zeitlich. Ein Pfeil kann die Richtung bestimmen; die Akkordtöne ändern sich nicht.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-tempo-return',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'tempo-return',
    description: {
      en: 'Read where the tempo changes and where it returns. A tempo recalls the preceding tempo; Tempo I recalls the initial tempo.',
      ru: 'Найдите начало изменения и возврат темпа. A tempo возвращает предшествующий темп, Tempo I — первоначальный.',
      de: 'Finde Tempoänderung und Rückkehr. A tempo ruft das vorherige Tempo auf, Tempo I das Anfangstempo.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-dynamic-hairpin',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'dynamic-hairpin',
    description: {
      en: 'The hairpin changes intensity across its drawn span. Its endpoint matters; it is not an instruction to keep growing indefinitely.',
      ru: 'Вилка изменяет силу звука на указанном участке. Её конец существенен: усиление не продолжается бесконечно.',
      de: 'Die Gabel verändert die Intensität auf ihrer gezeichneten Strecke. Ihr Ende zählt; sie verlangt keine unbegrenzte Steigerung.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-dynamic-fp',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'dynamic-fp',
    description: {
      en: 'Fp combines a strong onset with a soft continuation. Distinguish the attack from the sustained level.',
      ru: 'Fp сочетает сильное начало с тихим продолжением. Различайте атаку и последующую динамику.',
      de: 'Fp verbindet einen kräftigen Beginn mit leiser Fortsetzung. Unterscheide Anschlag und anhaltende Lautstärke.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-articulation-phrase',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'articulation-phrase',
    description: {
      en: 'Compare articulation marks, a grouping curve and a break in the line. They answer different questions: connection, phrase shape and breathing.',
      ru: 'Сравните штрихи, объединяющую дугу и разрыв линии. Они отвечают на разные вопросы: связность, построение фразы и дыхание.',
      de: 'Vergleiche Artikulationszeichen, einen gliedernden Bogen und einen Einschnitt. Sie betreffen Verbindung, Phrasenform und Atmung.',
    },
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-excerpt-mixed',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'excerpt-mixed',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-excerpt-cross-bar',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'excerpt-cross-bar',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-trill-c4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'trill-c4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-trill-f3',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'trill-f3',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-mordent-c4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'mordent-c4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-mordent-f3',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'mordent-f3',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-turn-c4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'turn-c4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-turn-f3',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'turn-f3',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-grace-c4',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'grace-c4',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'figure-grace-f3',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'notation-figure',
    path: 'lib/notation-figures.json',
    entry: 'grace-f3',
    rights: [
      {
        part: 'Original example composition',
        license: 'CC-BY-4.0',
        evidence: 'CONTENT-LICENSE.md',
      },
      {
        part: 'Embedded Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
  {
    id: 'leipzig-glyphs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: [],
    kind: 'font-outlines',
    path: 'lib/glyphs.json',
    rights: [
      {
        part: 'Leipzig font outlines',
        license: 'OFL-1.1',
        evidence: 'docs/notation-engine.md',
      },
    ],
  },
];
export default content;
