import type { Source } from './schema';

const content: Source[] = [
  {
    id: 'source-001',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Chelsey Hamm / Bryn Hughes · Open Music Theory 2 · American Standard Pitch Notation · ASPN and Octave Designations',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/aspn/',
    edition: '2',
    locator:
      'Open Music Theory 2 · American Standard Pitch Notation · ASPN and Octave Designations',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-002',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24.4 · §1.1.3 Displaying pitches · Key signature / Automatic accidentals / Ottava brackets',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/displaying-pitches',
    edition: '2.24.4',
    locator:
      '§1.1.3 Displaying pitches · Key signature / Automatic accidentals / Ottava brackets',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-003',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title:
      'Lehrklänge · Lexikon · Vortragsbezeichnungen · alphabetical entries',
    url: 'https://www.lehrklaenge.de/PHP/Lexikon/Vortragsbezeichnungen.php',
    edition: null,
    locator: 'Lexikon · Vortragsbezeichnungen · alphabetical entries',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-004',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24.4 Music Glossary · divisio',
    url: 'https://lilypond.org/doc/v2.24/Documentation/music-glossary/divisio',
    edition: '2.24.4',
    locator: 'divisio',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-005',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Saffron Hall · Graphic scores explained · opening explanation (11 May 2022)',
    url: 'https://www.saffronhall.com/articles/graphic-scores-explained',
    edition: null,
    locator: 'Graphic scores explained · opening explanation (11 May 2022)',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-006',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24.4 · §2.7.3 Figured bass · Introduction / Entering figured bass',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/figured-bass',
    edition: '2.24.4',
    locator: '§2.7.3 Figured bass · Introduction / Entering figured bass',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-007',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24.4 · §2.4.1 Common notation for fretted strings · Default tablatures',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/common-notation-for-fretted-strings',
    edition: '2.24.4',
    locator: '§2.4.1 Common notation for fretted strings · Default tablatures',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-008',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24.4 · §1.3.2 Expressive marks as curves · Slurs / Phrasing slurs',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/expressive-marks-as-curves',
    edition: '2.24.4',
    locator: '§1.3.2 Expressive marks as curves · Slurs / Phrasing slurs',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-009',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Gotham / Hamm / Hughes · Open Music Theory 2 · Notating Rhythm · Note Values / Rest Values / Dots and ties',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/notating-rhythm/',
    edition: '2',
    locator:
      'Open Music Theory 2 · Notating Rhythm · Note Values / Rest Values / Dots and ties',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-010',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24.4 · §1.2.1 Writing rhythms · Tuplets / Scaling durations',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/writing-rhythms#tuplets',
    edition: '2.24.4',
    locator: '§1.2.1 Writing rhythms · Tuplets / Scaling durations',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-011',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24.4 · §1.2.1 Writing rhythms · Ties',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/writing-rhythms#ties',
    edition: '2.24.4',
    locator: '§1.2.1 Writing rhythms · Ties',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-012',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Mark Gotham / Chelsey Hamm · Open Music Theory 2 · Other Aspects of Notation · Dynamics / Articulations / Tempo / Structural Features',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/other-aspects-of-notation/',
    edition: '2',
    locator:
      'Open Music Theory 2 · Other Aspects of Notation · Dynamics / Articulations / Tempo / Structural Features',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-013',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Dolmetsch Online · Music Theory §5 Tempo · Table of Tempo Markings / Metronome Marks',
    url: 'https://www.dolmetsch.com/musictheory5.htm',
    edition: null,
    locator:
      'Music Theory §5 Tempo · Table of Tempo Markings / Metronome Marks',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-014',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24.4 · §1.2.4 Beams',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/beams',
    edition: '2.24.4',
    locator: '§1.2.4 Beams',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-015',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24.4 · §1.3.1 Articulations and ornamentations',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/expressive-marks-attached-to-notes',
    edition: '2.24.4',
    locator: '§1.3.1 Articulations and ornamentations',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-016',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24.4 · §1.4 Repeats',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/repeats',
    edition: '2.24.4',
    locator: '§1.4 Repeats',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-017',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Chelsey Hamm · Open Music Theory 2 · Reading Clefs · Clefs and Ranges / Reading Treble, Bass, Alto and Tenor Clef',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/clefs/',
    edition: '2',
    locator:
      'Open Music Theory 2 · Reading Clefs · Clefs and Ranges / Reading Treble, Bass, Alto and Tenor Clef',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-018',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §1.2.1 · Durations, Tuplets, Ties',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/writing-rhythms',
    edition: '2.24',
    locator: 'Notation Reference §1.2.1 · Durations, Tuplets, Ties',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-019',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §1.2.2 · Rests / Full measure rests',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/writing-rests',
    edition: '2.24',
    locator: 'Notation Reference §1.2.2 · Rests / Full measure rests',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-020',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Music Glossary §2 · Duration names, notes and rests',
    url: 'https://lilypond.org/doc/v2.24/Documentation/music-glossary/duration-names-notes-and-rests',
    edition: '2.24',
    locator: 'Music Glossary §2 · Duration names, notes and rests',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-021',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24 · Music Glossary · Multi-measure rest',
    url: 'https://lilypond.org/doc/v2.24/Documentation/music-glossary/multi_002dmeasure-rest',
    edition: '2.24',
    locator: 'Music Glossary · Multi-measure rest',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-022',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §2.2.1 · References for keyboards',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/common-notation-for-keyboards#references-for-keyboards',
    edition: '2.24',
    locator: 'Notation Reference §2.2.1 · References for keyboards',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-023',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §1.1.3 · Clef / Key signature / Ottava / Automatic accidentals',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/displaying-pitches',
    edition: '2.24',
    locator:
      'Notation Reference §1.1.3 · Clef / Key signature / Ottava / Automatic accidentals',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-024',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24 · Notation Reference §1.7.1 · Stems',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/inside-the-staff#stems',
    edition: '2.24',
    locator: 'Notation Reference §1.7.1 · Stems',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-025',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §2.7.2 · Printing and customizing chord names',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/displaying-chords',
    edition: '2.24',
    locator: 'Notation Reference §2.7.2 · Printing and customizing chord names',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-026',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'LilyPond 2.24 · Notation Reference §1.2.6 · Grace notes / afterGrace',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/special-rhythmic-concerns#grace-notes',
    edition: '2.24',
    locator: 'Notation Reference §1.2.6 · Grace notes / afterGrace',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-027',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24 · Notation Reference §1.3.3 · Arpeggio',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/expressive-marks-as-lines#arpeggio',
    edition: '2.24',
    locator: 'Notation Reference §1.3.3 · Arpeggio',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-028',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24 · Music Glossary · Acciaccatura',
    url: 'https://lilypond.org/doc/v2.24/Documentation/music-glossary/acciaccatura',
    edition: '2.24',
    locator: 'Music Glossary · Acciaccatura',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-029',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title: 'Lehrklänge · Grundlagen · Notenschlüssel · Instrument examples',
    url: 'https://www.lehrklaenge.de/PHP/Grundlagen/Notenschluessel.php',
    edition: null,
    locator: 'Grundlagen · Notenschlüssel · Instrument examples',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-030',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Vienna Symphonic Library Academy · Bassoon · Notation',
    url: 'https://www.vsl.co.at/academy/woodwinds/bassoon',
    edition: null,
    locator: 'Bassoon · Notation',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-031',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Vienna Symphonic Library Academy · Tenor trombone · Notation',
    url: 'https://www.vsl.co.at/academy/brass/tenor-trombone',
    edition: null,
    locator: 'Tenor trombone · Notation',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-032',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Dolmetsch Online · Music Theory §21 · Tables of Dynamic and General Musical Markings',
    url: 'https://www.dolmetsch.com/musictheory21.htm',
    edition: null,
    locator:
      'Music Theory §21 · Tables of Dynamic and General Musical Markings',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-033',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Dolmetsch Online · Music Dictionary M–Ma · mancando',
    url: 'https://www.dolmetsch.com/defsm.htm',
    edition: null,
    locator: 'Music Dictionary M–Ma · mancando',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-034',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Dolmetsch Online · Music Dictionary Ts–Tz · tumultuoso',
    url: 'https://www.dolmetsch.com/defst5.htm',
    edition: null,
    locator: 'Music Dictionary Ts–Tz · tumultuoso',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-035',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Zach Gist / Chelsey Hamm · Open Music Theory 2 · Graphic Notation and Scores · A Brief History / Measuring Time and Hybrid Scores (chapter in development)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/graphic-notation-and-scores/',
    edition: '2',
    locator:
      'Open Music Theory 2 · Graphic Notation and Scores · A Brief History / Measuring Time and Hybrid Scores (chapter in development)',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-036',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title:
      'Lehrklänge · Lexikon · Verzierungen · Praller, Mordent, Doppelschlag, Schleifer, Arpeggio, Acciaccatura',
    url: 'https://www.lehrklaenge.de/PHP/Lexikon/Verzierungen.php',
    edition: null,
    locator:
      'Lexikon · Verzierungen · Praller, Mordent, Doppelschlag, Schleifer, Arpeggio, Acciaccatura',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-037',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title:
      'Lehrklänge · Lexikon · Artikulation · Note connection and separation',
    url: 'https://www.lehrklaenge.de/PHP/Lexikon/Artikulation.php',
    edition: null,
    locator: 'Lexikon · Artikulation · Note connection and separation',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-038',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title: 'Lehrklänge · Grundlagen · Das Notensystem',
    url: 'https://www.lehrklaenge.de/PHP/Grundlagen/Notensystem.php',
    edition: null,
    locator: 'Grundlagen · Das Notensystem',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-039',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title:
      'Lehrklänge · Grundlagen · Noten lesen · Repeated names and octave designation',
    url: 'https://www.lehrklaenge.de/PHP/Grundlagen/Noten_lesen.php',
    edition: null,
    locator: 'Grundlagen · Noten lesen · Repeated names and octave designation',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-040',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Joe Wolfe · UNSW · Note names, MIDI numbers and frequencies · 12-TET and A4 = 440 Hz',
    url: 'https://newt.phys.unsw.edu.au/jw/notes.html',
    edition: null,
    locator:
      'UNSW · Note names, MIDI numbers and frequencies · 12-TET and A4 = 440 Hz',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-041',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Brian Blood · Dolmetsch Online · Music Theory §21 · Slur & Phrase (Türk 1789 / Clementi 1801 comparison)',
    url: 'https://www.dolmetsch.com/musictheory21.htm',
    edition: null,
    locator:
      'Dolmetsch Online · Music Theory §21 · Slur & Phrase (Türk 1789 / Clementi 1801 comparison)',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-042',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'S33 · Erich Wolf · Allgemeine Musiklehre · 7., korrigierte Auflage 1985, Nachdruck 2016 · §15b, p.28 · Historical wording only',
    url: 'https://github.com/alex-michels/one-music-lab/blob/main/docs/sources.md',
    edition: null,
    locator:
      'Erich Wolf · Allgemeine Musiklehre · 7., korrigierte Auflage 1985, Nachdruck 2016 · §15b, p.28 · Historical wording only',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-043',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (sound)',
    url: 'https://newt.phys.unsw.edu.au/jw/musical-sounds-musical-instruments.html',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-044',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (tuning)',
    url: 'https://newt.phys.unsw.edu.au/music/temperament/WhatFor.html',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-045',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (intervals)',
    url: 'https://musictheory.pugetsound.edu/mt21c/IntervalsIntroduction.html',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-046',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (scales)',
    url: 'https://viva.pressbooks.pub/openmusictheory/table-of-contents/',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-047',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (chords)',
    url: 'https://musictheory.pugetsound.edu/mt21c/TriadsIntroduction.html',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-048',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title: 'Inherited lesson reference (accidental-signs)',
    url: 'https://www.lehrklaenge.de/PHP/Grundlagen/Vorzeichen.php',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-049',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (enharmonics)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/#chapter-1384-section-4',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-050',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (dots-ties)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/notating-rhythm/#chapter-57-section-3',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-051',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['de'],
    title: 'Inherited lesson reference (beat-division)',
    url: 'https://www.lehrklaenge.de/PHP/Grundlagen/Triole.php',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-052',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'LilyPond 2.24 · Notation Reference §1.2.1 · Tuplets',
    url: 'https://lilypond.org/doc/v2.24/Documentation/notation/writing-rhythms#tuplets',
    edition: '2.24',
    locator: 'Notation Reference §1.2.1 · Tuplets',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-053',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (tempo)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/other-aspects-of-notation/#chapter-4083-section-3',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-054',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (dynamics)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/other-aspects-of-notation/#chapter-4083-section-1',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-055',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (articulation)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/other-aspects-of-notation/#chapter-4083-section-2',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-056',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title: 'Inherited lesson reference (repeats)',
    url: 'https://viva.pressbooks.pub/openmusictheory/chapter/other-aspects-of-notation/#chapter-4083-section-4',
    edition: null,
    locator: null,
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-057',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Joe Wolfe · UNSW · Musical sounds, musical instruments and musical signals · Frequency and pitch / Pure tones and harmonics',
    url: 'https://newt.phys.unsw.edu.au/jw/musical-sounds-musical-instruments.html',
    edition: null,
    locator:
      'UNSW · Musical sounds, musical instruments and musical signals · Frequency and pitch / Pure tones and harmonics',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-058',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Robert Hutchinson · Music Theory for the 21st-Century Classroom · §6.1 Introduction to Triads',
    url: 'https://musictheory.pugetsound.edu/mt21c/TriadsIntroduction.html',
    edition: null,
    locator:
      'Music Theory for the 21st-Century Classroom · §6.1 Introduction to Triads',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-059',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Robert Hutchinson · Music Theory for the 21st-Century Classroom · §1.2 Notation',
    url: 'https://musictheory.pugetsound.edu/mt21c/Notation.html',
    edition: null,
    locator: 'Music Theory for the 21st-Century Classroom · §1.2 Notation',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
  {
    id: 'source-060',
    version: 1,
    scopeId: 'reference-context',
    prerequisites: [],
    locales: ['en'],
    title:
      'Robert Hutchinson · Music Theory for the 21st-Century Classroom · §4.3 Dots and Ties',
    url: 'https://musictheory.pugetsound.edu/mt21c/DotsAndTies.html',
    edition: null,
    locator: 'Music Theory for the 21st-Century Classroom · §4.3 Dots and Ties',
    verification: 'inherited-unverified',
    evidence: ['docs/content-schema.md'],
  },
];
export default content;
