/** Leipzig outlines (SIL OFL 1.1); see THIRD-PARTY-NOTICES.md.
 * Generated by npm run glyphs:generate; checked by npm run glyphs:check. */
import outlines from './glyphs.json';
export const GLYPH_UNITS_PER_SPACE = 250;
export const glyphs = outlines;
export type GlyphName = keyof typeof glyphs;
