import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'accidental-signs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['note-names'],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F03',
    roadmapIds: ['014'],
    lessonIds: ['accidental-signs'],
    experimentIds: ['accidental-signs'],
    exerciseIds: ['alteration-name'],
    conceptIds: [
      'Accidental',
      'Sharp',
      'Flat',
      'Double sharp',
      'Double flat',
      'Natural',
      'Semitone',
      'Whole tone',
    ],
  },
  lesson: {
    id: 'accidental-signs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'accidental-signs',
    title: {
      en: 'The five signs',
      ru: 'Пять знаков альтерации',
      de: 'Die fünf Zeichen',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Read the five accidentals and know how far each moves.',
      ru: 'Читайте пять знаков альтерации и знайте, насколько каждый сдвигает высоту.',
      de: 'Die fünf Versetzungszeichen lesen und ihre Wirkung kennen.',
    },
    formula: {
      en: '♯ +1 · ♭ −1 · × +2 · ♭♭ −2 · ♮ 0 (semitones)',
      ru: '♯ +1 · ♭ −1 · × +2 · ♭♭ −2 · ♮ 0 (в полутонах)',
      de: 'Kreuz +1 · Be −1 · Doppelkreuz +2 · Doppel-Be −2 · Auflösungszeichen 0 (Halbtöne)',
    },
    paragraphs: [
      {
        en: 'An accidental changes the pitch of the written note it stands before. A sharp raises it by a semitone, a flat lowers it by a semitone; the double sharp raises by a whole tone, the double flat lowers by a whole tone. A natural cancels any of them.',
        ru: 'Знак альтерации меняет высоту ноты, перед которой он стоит. Диез повышает её на полутон, бемоль понижает на полутон. Дубль-диез повышает на целый тон, дубль-бемоль понижает на целый тон. Бекар отменяет действие любого из них и возвращает основную ступень.',
        de: 'Ein Versetzungszeichen verändert die Tonhöhe des Stammtons, vor dem es steht. Das Kreuz erhöht um einen Halbton, das Be erniedrigt um einen Halbton. Das Doppelkreuz erhöht um einen Ganzton, das Doppel-Be erniedrigt um einen Ganzton. Das Auflösungszeichen nimmt die Veränderung zurück und stellt den Stammton wieder her.',
      },
      {
        en: 'The sign stands to the left of the note head, on the same line or space, and is spoken after the letter: C sharp, B flat. The letter itself does not change. To replace a double sharp with a single sharp, the single sign is written alone.',
        ru: 'Знак пишется слева от нотной головки, на той же линейке или в том же промежутке, а в названии идёт после ступени: до-диез, си-бемоль. Сама ступень при этом не меняется: нота остаётся на своём месте на нотоносце. Чтобы заменить дубль-диез простым диезом, пишут один диез.',
        de: 'Das Zeichen steht links vom Notenkopf, auf derselben Linie oder in demselben Zwischenraum. Im Deutschen steckt die Veränderung zugleich im Namen: Das Kreuz hängt die Silbe -is an, das Doppelkreuz -isis, aus C werden Cis und Cisis. Das Be hängt -es an, das Doppel-Be -eses, aus D werden Des und Deses. Unregelmäßig gebildet sind Es, As und B; das doppelt erniedrigte H heißt Heses. Soll aus einem Doppelkreuz ein einfaches Kreuz werden, steht das einfache Zeichen allein.',
        ruMarkup:
          'Знак пишется слева от нотной головки, на той же линейке или в том же промежутке, а в названии идёт после ступени: [[до-диез]], [[си-бемоль]]. Сама ступень при этом не меняется: нота остаётся на своём месте на нотоносце. Чтобы заменить дубль-диез простым диезом, пишут один диез.',
      },
    ],
    sourceId: 'source-048',
    experimentId: 'accidental-signs',
    reading: {
      pages: '6–9',
      sourceId: 'source-002',
      text: {
        en: 'Read each accidental relative to the natural letter, not relative to the last accidental. After a double sharp, a single sharp means one semitone above the natural. Align the sign with the notehead; do not draw a ledger line through the sign. Examples: F–F♯–F𝄪; B–B♭–B𝄫.',
        ru: 'Каждый знак отсчитывают от основной ступени, а не от предыдущего знака. После дубль-диеза диез означает повышение основной ступени на полутон. Знак ставят на высоте головки; добавочная линейка через знак не проходит. Например: фа — фа-диез — фа-дубль-диез; си — си-бемоль — си-дубль-бемоль.',
        de: 'Jedes Zeichen bezieht sich auf den Stammton, nicht auf das vorherige Zeichen. Nach einem Doppelkreuz bedeutet ein Kreuz einen Halbton über dem Stammton. Das Zeichen steht auf Höhe des Notenkopfs; Hilfslinien werden nicht durch das Zeichen gezogen. Beispiele: F–Fis–Fisis; H–B–Heses; E–Es und A–As.',
        ruMarkup:
          'Каждый знак отсчитывают от основной ступени, а не от предыдущего знака. После дубль-диеза диез означает повышение основной ступени на полутон. Знак ставят на высоте головки; добавочная линейка через знак не проходит. Например: [[фа]] — [[фа-диез]] — [[фа-дубль-диез]]; [[си]] — [[си-бемоль]] — [[си-дубль-бемоль]].',
      },
      assetIds: [],
    },
  },
  experiment: {
    id: 'accidental-signs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'accidental-signs',
    instructions: {
      en: 'Play C4 and C♯4 one after the other, then C4 and D4, and compare the two distances.',
      ru: 'Сыграйте до первой октавы и до-диез, затем до и ре, и сравните два расстояния.',
      de: 'Spiele c′ und cis′ nacheinander, dann c′ und d′, und vergleiche die beiden Abstände.',
      ruMarkup:
        'Сыграйте [[до]] первой октавы и [[до-диез]], затем [[до]] и [[ре]], и сравните два расстояния.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 261.625565,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'alteration-name',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      label: {
        en: 'Name an altered note',
        ru: 'Название альтерированной ступени',
        de: 'Einen veränderten Ton benennen',
      },
      generator: 'accidental-name',
      sourceIds: ['source-002'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Accidental',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 73,
      reference: false,
      title: {
        en: 'Accidental',
        ru: 'Знак альтерации',
        de: 'Versetzungszeichen',
      },
      body: {
        en: 'A sign that specifies a note’s alteration relative to its natural letter name: sharp, flat, double sharp, double flat or natural. A natural restores the unaltered pitch; signs are not added to one another.',
        ru: 'Знак, указывающий изменение основной ступени: диез, бемоль, дубль-диез, дубль-бемоль или бекар. Бекар восстанавливает основную ступень; знаки не складываются друг с другом.',
        de: 'Ein Zeichen, das die Veränderung gegenüber dem Stammton festlegt: Kreuz, Be, Doppelkreuz, Doppel-Be oder Auflösungszeichen. Das Auflösungszeichen stellt den Stammton wieder her; die Zeichen werden nicht addiert.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Sharp',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 74,
      reference: false,
      title: {
        en: 'Sharp',
        ru: 'Диез',
        de: 'Kreuz',
      },
      body: {
        en: 'A sign that raises the written note by one semitone.',
        ru: 'Знак, повышающий записанную ноту на полутон.',
        de: 'Ein Zeichen, das den Stammton um einen Halbton erhöht; der Name erhält die Endung -is.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Flat',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 75,
      reference: false,
      title: {
        en: 'Flat',
        ru: 'Бемоль',
        de: 'Be',
      },
      body: {
        en: 'A sign that lowers the written note by one semitone.',
        ru: 'Знак, понижающий записанную ноту на полутон.',
        de: 'Ein Zeichen, das den Stammton um einen Halbton erniedrigt. Meist wird -es angehängt; die gebräuchlichen Ausnahmen sind Es, As und B (das erniedrigte H).',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Double sharp',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 76,
      reference: false,
      title: {
        en: 'Double sharp',
        ru: 'Дубль-диез',
        de: 'Doppelkreuz',
      },
      body: {
        en: 'A sign that raises the written note by two semitones.',
        ru: 'Знак, повышающий записанную ноту на два полутона.',
        de: 'Ein Zeichen, das den Stammton um einen Ganzton erhöht; der Name erhält die Endung -isis.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Double flat',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 77,
      reference: false,
      title: {
        en: 'Double flat',
        ru: 'Дубль-бемоль',
        de: 'Doppel-Be',
      },
      body: {
        en: 'A sign that lowers the written note by two semitones.',
        ru: 'Знак, понижающий записанную ноту на два полутона.',
        de: 'Ein Zeichen, das den Stammton um einen Ganzton erniedrigt. Die Namen lauten Ceses, Deses, Eses, Feses, Geses, Ases und Heses; für Ases kommt auch Asas vor.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Natural',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 78,
      reference: false,
      title: {
        en: 'Natural',
        ru: 'Бекар',
        de: 'Auflösungszeichen',
      },
      body: {
        en: 'A sign that removes an earlier raising or lowering of a note.',
        ru: 'Знак, снимающий сделанное ранее повышение или понижение ноты.',
        de: 'Ein Zeichen, das eine Erhöhung oder Erniedrigung zurücknimmt.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Semitone',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 79,
      reference: false,
      title: {
        en: 'Semitone',
        ru: 'Полутон',
        de: 'Halbton',
      },
      body: {
        en: 'The smallest step between adjacent keys in twelve-tone equal temperament.',
        ru: 'Наименьший шаг между соседними клавишами в двенадцатиступенном равномерном строе.',
        de: 'Der kleinste Schritt zwischen benachbarten Tasten in der zwölfstufigen gleichstufigen Stimmung.',
      },
      sourceId: 'source-040',
    },
    {
      id: 'Whole tone',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-signs',
      order: 80,
      reference: false,
      title: {
        en: 'Whole tone',
        ru: 'Целый тон',
        de: 'Ganzton',
      },
      body: {
        en: 'An interval that spans two semitones.',
        ru: 'Интервал, охватывающий два полутона.',
        de: 'Ein Abstand von zwei Halbtönen.',
      },
      sourceId: 'source-040',
    },
  ],
};
export default content;
