import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'accidental-scope',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['note-names'],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F03',
    roadmapIds: ['014'],
    lessonIds: ['accidental-scope'],
    experimentIds: ['accidental-scope'],
    exerciseIds: ['sign-stops-at-the-barline', 'sign-holds-to-the-barline'],
    conceptIds: [
      'Key signature',
      'Bar',
      'Barline',
      'Tie',
      'Courtesy accidental',
      'Staff system',
    ],
  },
  lesson: {
    id: 'accidental-scope',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'accidental-scope',
    title: {
      en: 'How far a sign reaches',
      ru: 'Докуда действует знак',
      de: 'Wie weit ein Zeichen gilt',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Know where each accidental starts and where it stops.',
      ru: 'Поймите, где знак начинает и где перестаёт действовать.',
      de: 'Erkennen, wo ein Vorzeichen gilt und wo es endet.',
    },
    formula: {
      en: 'Signature: whole piece, every octave · In the bar: to the barline, one octave',
      ru: 'Ключевые знаки: всё произведение, все октавы · Случайные: до тактовой черты, одна октава',
      de: 'Vorzeichnung: ganzes Stück, alle Oktaven · Versetzungszeichen: bis zum Taktstrich, eine Oktave',
    },
    paragraphs: [
      {
        en: 'A key signature stands at the start of every system, after the clef. Each of its signs applies to its letter for the whole piece and in every octave, until a new signature replaces it. Signs do not add up: a flat in the signature and a flat in the bar are still one flat.',
        ru: 'Ключевые знаки выставляются при ключе в начале каждой нотной строки. Каждый из них действует на свою ступень во всём произведении и во всех октавах, пока его не заменят новые ключевые знаки. Знаки не складываются: бемоль при ключе и бемоль внутри такта дают один бемоль, а не двойное понижение.',
        de: 'Die Vorzeichnung steht am Anfang jeder Notenzeile hinter dem Schlüssel. Jedes ihrer Zeichen gilt für seinen Stammton im ganzen Stück und in allen Oktaven, bis eine neue Vorzeichnung sie ersetzt. Zeichen addieren sich nicht: Ein Be in der Vorzeichnung und ein Be im Takt ergeben zusammen ein Be, keine doppelte Erniedrigung.',
      },
      {
        en: 'In common-practice notation, a sign within a bar applies to the same written pitch until the barline. A tied continuation retains it across the barline. Courtesy signs can clarify the reading; an edition may explicitly declare other conventions.',
        ru: 'В традиционной нотации случайный знак действует на ту же ноту в той же октаве до тактовой черты. Залигованное продолжение сохраняет знак за чертой. Предупредительные знаки облегчают чтение; редакция может явно оговаривать другие правила.',
        de: 'In üblicher Notation gilt ein Versetzungszeichen für dieselbe Tonhöhe bis zum Taktstrich. Eine übergebundene Fortsetzung behält es darüber hinaus. Erinnerungszeichen erleichtern das Lesen; eine Ausgabe kann ausdrücklich andere Regeln festlegen.',
      },
    ],
    sourceId: 'source-048',
    experimentId: 'accidental-scope',
    reading: {
      pages: '6–9',
      sourceId: 'source-002',
      text: {
        en: 'Common-practice signature order is F C G D A E B for sharps and B E A D G C F for flats. Standard signatures use single signs. A local sign replaces the signature for that written pitch within the bar; a tied continuation preserves it across the barline. A later untied note again follows the signature. Editions may print reminders or declare different conventions.',
        ru: 'Обычный порядок ключевых диезов: фа, до, соль, ре, ля, ми, си; бемолей: си, ми, ля, ре, соль, до, фа. В стандартных ключевых знаках нет двойных альтераций. Случайный знак заменяет ключевой для данной ноты в данной октаве до конца такта; связанная продолжением нота сохраняет его за чертой. Следующая незалигованная нота снова подчиняется ключевым знакам. Редакции могут давать напоминания или оговаривать другие правила.',
        de: 'Übliche Reihenfolge der Kreuze: F C G D A E H; der Be: H E A D G C F. Reguläre Vorzeichnungen enthalten keine Doppelzeichen. Ein Versetzungszeichen ersetzt das Vorzeichen für diese Tonhöhe bis zum Taktende; eine übergebundene Fortsetzung behält es über den Taktstrich hinaus. Eine spätere, neu angeschlagene Note folgt wieder der Vorzeichnung. Ausgaben können Erinnerungszeichen oder ausdrücklich andere Regeln verwenden.',
        ruMarkup:
          'Обычный порядок ключевых диезов: [[фа]], [[до]], [[соль]], [[ре]], [[ля]], [[ми]], [[си]]; бемолей: [[си]], [[ми]], [[ля]], [[ре]], [[соль]], [[до]], [[фа]]. В стандартных ключевых знаках нет двойных альтераций. Случайный знак заменяет ключевой для данной ноты в данной октаве до конца такта; связанная продолжением нота сохраняет его за чертой. Следующая незалигованная нота снова подчиняется ключевым знакам. Редакции могут давать напоминания или оговаривать другие правила.',
      },
      assetIds: [
        'figure-signature-bass',
        'figure-accidental-tie-scope',
        'figure-accidental-octave-scope',
      ],
    },
  },
  experiment: {
    id: 'accidental-scope',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'accidental-scope',
    instructions: {
      en: 'Play B4, then B♭4, then the same pair an octave lower: one signature sign would cover both octaves.',
      ru: 'Сыграйте си первой октавы, затем си-бемоль, потом ту же пару октавой ниже: один ключевой знак действовал бы в обеих октавах.',
      de: 'Spiele h′, dann b′ und danach dasselbe Paar eine Oktave tiefer: Ein einziges Vorzeichen würde für beide Oktaven gelten.',
      ruMarkup:
        'Сыграйте [[си]] первой октавы, затем [[си-бемоль]], потом ту же пару октавой ниже: один ключевой знак действовал бы в обеих октавах.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 493.883301,
      wave: 'sine',
    },
    notation: {
      note: {
        letter: 6,
        accidental: 0,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'sign-stops-at-the-barline',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      label: {
        en: 'Read an accidental across a barline',
        ru: 'Действие знака за тактовой чертой',
        de: 'Versetzungszeichen über den Taktstrich hinaus lesen',
      },
      generator: 'accidental-scope',
      sourceIds: ['source-002'],
      kind: 'generated',
    },
    {
      id: 'sign-holds-to-the-barline',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      label: {
        en: 'Read an accidental within a bar',
        ru: 'Действие знака внутри такта',
        de: 'Versetzungszeichen innerhalb eines Taktes lesen',
      },
      generator: 'accidental-scope',
      sourceIds: ['source-002'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Key signature',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 81,
      reference: false,
      title: {
        en: 'Key signature',
        ru: 'Ключевые знаки',
        de: 'Vorzeichnung',
      },
      body: {
        en: 'The group of sharps or flats printed after the clef.',
        ru: 'Группа диезов или бемолей, выставленная при ключе.',
        de: 'Die Gruppe von Kreuzen oder Be-Zeichen hinter dem Schlüssel.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Bar',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 82,
      reference: false,
      title: {
        en: 'Bar',
        ru: 'Такт',
        de: 'Takt',
      },
      body: {
        en: 'The span of music between two barlines.',
        ru: 'Отрезок музыки между двумя тактовыми чертами.',
        de: 'Der Abschnitt zwischen zwei Taktstrichen.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Barline',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 83,
      reference: false,
      title: {
        en: 'Barline',
        ru: 'Тактовая черта',
        de: 'Taktstrich',
      },
      body: {
        en: 'The vertical line that separates one bar from the next.',
        ru: 'Вертикальная черта, отделяющая один такт от следующего.',
        de: 'Der senkrechte Strich, der einen Takt vom nächsten trennt.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Tie',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 84,
      reference: false,
      title: {
        en: 'Tie',
        ru: 'Связующая лига',
        de: 'Haltebogen',
      },
      body: {
        en: 'A curved line joining two note heads of the same pitch into one sound.',
        ru: 'Дуга, соединяющая две ноты одной высоты в один звук.',
        de: 'Ein Bogen, der zwei Notenköpfe derselben Tonhöhe zu einem Klang verbindet.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Courtesy accidental',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 85,
      reference: false,
      title: {
        en: 'Courtesy accidental',
        ru: 'Предупредительный знак',
        de: 'Vorsichtszeichen',
      },
      body: {
        en: 'A sign printed where the rule does not require it, to remove doubt.',
        ru: 'Знак, выписанный там, где правило его не требует, чтобы снять сомнение.',
        de: 'Ein Zeichen, das über die Regel hinaus gesetzt wird, um Zweifel auszuschließen.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Staff system',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'accidental-scope',
      order: 86,
      reference: false,
      title: {
        en: 'Staff system',
        ru: 'Нотная строка',
        de: 'Notenzeile',
      },
      body: {
        en: 'One line of music running across the page.',
        ru: 'Одна строка нотной записи, идущая через страницу.',
        de: 'Eine Zeile der Notenschrift, die über die Seite läuft.',
      },
      sourceId: 'source-023',
    },
  ],
};
export default content;
