import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'articulation',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['sound', 'tempo', 'chords'],
    locales: ['en', 'ru', 'de'],
    kind: 'concept',
    module: 'N02',
    roadmapIds: ['125'],
    lessonIds: ['articulation'],
    experimentIds: ['articulation'],
    exerciseIds: ['recognize-an-ornament', 'articulation-sign'],
    conceptIds: [
      'Unmarked articulation',
      'Ornament',
      'Trill',
      'Mordent',
      'Turn',
      'Grace note',
      'After-grace',
      'Slide ornament',
      'Arpeggio sign',
      'Breath mark and caesura',
      'Chant divisions',
      'Acciaccatura: distinguish the usage',
      'Unslashed grace note',
      'Non legato and leggiero',
      'articulation',
      'staccato',
      'staccatissimo',
      'tenuto',
      'portato',
      'phrasing',
    ],
  },
  lesson: {
    id: 'articulation',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'articulation',
    title: {
      en: 'Joined or separated',
      ru: 'Слитно или раздельно',
      de: 'Gebunden oder getrennt',
    },
    category: {
      en: 'Performance',
      ru: 'Исполнение',
      de: 'Vortrag',
    },
    summary: {
      en: 'Distinguish legato, staccato, tenuto and portato in notation and sound.',
      ru: 'Различайте легато, стаккато, тенуто и портато в записи и на слух.',
      de: 'Unterscheide Legato, Staccato, Tenuto und Portato in Schrift und Klang.',
    },
    formula: {
      en: 'Legato: connected · Staccato: detached · Tenuto: held · Portato: gently separated',
      ru: 'Легато: связно · Стаккато: отрывисто · Тенуто: выдержанно · Портато: мягко разделяя',
      de: 'Legato: gebunden · Staccato: abgesetzt · Tenuto: ausgehalten · Portato: sanft getrennt',
    },
    paragraphs: [
      {
        en: 'Articulation shapes a note’s attack, duration and connection with its neighbours. A slur usually groups notes for connected playing; on some instruments it also indicates a specific technique. A staccato dot above or below a note asks for detached playing. Shortening the sound creates a gap within its written value; the next note still starts at its written time. A dot to the right has a different meaning: it lengthens the note.',
        ru: 'Артикуляция определяет начало звука, его выдерживание и связь с соседними звуками. Лига обычно объединяет ноты для связного исполнения; на некоторых инструментах она также указывает приём игры. Точка стаккато над или под нотой требует отрывистого исполнения. Укороченный звук оставляет паузу внутри своей записанной длительности; следующая нота вступает в положенный момент. Точка справа означает другое: она увеличивает длительность.',
        de: 'Artikulation gestaltet Tonansatz, Tondauer und die Verbindung zu benachbarten Tönen. Ein Bindebogen fasst gewöhnlich Noten zum gebundenen Spiel zusammen; auf manchen Instrumenten bezeichnet er auch eine bestimmte Spieltechnik. Ein Staccatopunkt über oder unter der Note verlangt abgesetztes Spiel. Der verkürzte Ton lässt innerhalb seines Notenwerts eine Lücke; der nächste Einsatz bleibt an seiner notierten Stelle. Ein Punkt rechts neben der Note bedeutet dagegen eine Verlängerung.',
      },
      {
        en: 'Tenuto asks for a held note; portato combines a slur with separation, and non legato asks that successive notes not be joined. Modern engraving distinguishes a staccato dot from a staccatissimo wedge. Neither is a universal numerical duration: consult the edition and instrument. An unmarked line still requires an articulation choice.',
        ru: 'Тенуто требует выдержать ноту; портато сочетает лигу с разделением, а нон легато — несвязное исполнение соседних звуков. Современная графика различает точку стаккато и клин стаккатиссимо. Ни один знак не задаёт универсальной числовой длительности: учитывайте редакцию и инструмент. В неразмеченной строке также нужно выбрать артикуляцию.',
        de: 'Tenuto verlangt Aushalten; Portato verbindet einen Bogen mit Trennung, Non legato verlangt unverbundene Töne. Moderne Notation unterscheidet Staccatopunkt und Staccatissimokeil. Keines der Zeichen bestimmt eine allgemeingültige zahlenmäßige Dauer: beachte Ausgabe und Instrument. Auch eine unbezeichnete Linie verlangt eine Artikulationsentscheidung.',
      },
    ],
    sourceId: 'source-055',
    experimentId: 'articulation',
    reading: {
      pages: '19, 28–30',
      sourceId: 'source-015',
      text: {
        en: 'Distinguish articulation, phrasing and ornaments. Legato connects; staccato separates; tenuto asks that a note be held. Portato combines connection with gentle separation. A breath mark or caesura interrupts the line. A dot versus a wedge is not a universal numerical length rule across periods. Ornament recognition here is a reference exercise; realization needs the edition, period and instrument.',
        ru: 'Различайте артикуляцию, фразировку и украшения. Легато связывает, стаккато разделяет, тенуто требует выдержать звук. Портато сочетает связность с мягким разделением. Знак дыхания или цезура прерывает линию. Точка и клин не задают универсального числового соотношения длительностей во всех эпохах. Здесь упражнение на украшения проверяет узнавание; исполнение зависит от редакции, эпохи и инструмента.',
        de: 'Unterscheide Artikulation, Phrasierung und Verzierungen. Legato verbindet, staccato trennt, tenuto verlangt Aushalten. Portato verbindet mit sanfter Trennung. Atemzeichen oder Zäsur unterbrechen die Linie. Punkt und Keil legen epochenübergreifend kein zahlenmäßiges Längenverhältnis fest. Die Verzierungsübung dient dem Erkennen; die Ausführung hängt von Ausgabe, Epoche und Instrument ab.',
      },
      assetIds: [
        'figure-detached',
        'figure-tenuto',
        'figure-trill',
        'figure-mordent',
        'figure-upper-mordent',
        'figure-turn',
        'figure-grace',
        'figure-long-grace',
        'figure-after-grace',
        'figure-slide',
        'figure-arpeggio',
        'figure-articulation-phrase',
      ],
    },
  },
  experiment: {
    id: 'articulation',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'articulation',
    instructions: {
      en: 'Compare Full-length tones and Short detached tones at the same tempo. Listen to the gaps while the onsets stay in the same places. Instrumental articulation needs its own technique.',
      ru: 'При одном темпе сравните тоны полной длительности и короткие раздельные тоны. Атаки остаются на тех же местах, а паузы меняются. Исполнение штрихов на инструменте требует своей техники.',
      de: 'Vergleiche bei gleichem Tempo Töne in voller Dauer und kurze abgesetzte Töne. Die Einsätze bleiben an denselben Stellen, die Pausen ändern sich. Instrumentale Artikulation erfordert die jeweilige Spieltechnik.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 261.625565,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'articulation',
    },
  },
  exercises: [
    {
      id: 'recognize-an-ornament',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      label: {
        en: 'Recognize ornament signs',
        ru: 'Распознавание мелизмов',
        de: 'Verzierungszeichen erkennen',
      },
      generator: 'ornament-review',
      sourceIds: ['source-015'],
      kind: 'generated',
    },
    {
      id: 'articulation-sign',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      label: {
        en: 'Read articulation marks',
        ru: 'Чтение знаков артикуляции',
        de: 'Artikulationszeichen lesen',
      },
      generator: 'performance-marks',
      sourceIds: ['source-015'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Unmarked articulation',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 1,
      reference: true,
      title: {
        en: 'Unmarked articulation',
        ru: 'Артикуляция без обозначений',
        de: 'Artikulation ohne Spielzeichen',
      },
      aliases: {
        en: 'historical performance; default articulation',
        ru: 'историческое исполнительство; нон легато',
        de: 'historische Aufführungspraxis; Non legato',
      },
      body: {
        en: 'Missing slurs or dots do not prescribe identical playing in every period. Brian Blood contrasts Türk’s 1789 keyboard advice, which leaves a small gap in ordinary playing, with Clementi’s 1801 preference for sustained values. These are specific keyboard traditions, not a rule for all instruments or all eighteenth- and nineteenth-century music. Check the edition and performance context before choosing a default articulation.',
        ru: 'Отсутствие лиг и точек не предписывает одинакового исполнения во все эпохи. Брайан Блад сопоставляет клавирные рекомендации Тюрка 1789 года, допускающие небольшой промежуток при обычном исполнении, с предпочтением Клементи 1801 года выдерживать длительности. Это конкретные клавирные традиции, а не правило для всех инструментов и всей музыки XVIII–XIX веков. Уточняйте редакцию и исполнительский контекст.',
        de: 'Fehlende Bögen oder Punkte verlangen nicht in jeder Epoche dasselbe Spiel. Brian Blood stellt Türks Klavierlehre von 1789, die beim gewöhnlichen Vortrag eine kleine Trennung vorsieht, Clementis Empfehlung von 1801 zum Aushalten der Notenwerte gegenüber. Das sind bestimmte Klaviertraditionen, keine Regel für alle Instrumente oder die gesamte Musik des 18. und 19. Jahrhunderts. Prüfe Ausgabe und Aufführungskontext.',
      },
      sourceId: 'source-041',
    },
    {
      id: 'Ornament',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 6,
      reference: true,
      title: {
        en: 'Ornament',
        ru: 'Мелизм',
        de: 'Verzierung',
      },
      body: {
        en: 'A written embellishment. Trill, mordent and turn signs need a historical and instrumental context for realization.',
        ru: 'Записанное украшение мелодии. Исполнение трели, мордента и группетто требует исторического и инструментального контекста.',
        de: 'Eine notierte Ausschmückung. Triller, Mordent und Doppelschlag benötigen zur Ausführung einen historischen und instrumentalen Kontext.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'Trill',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 7,
      reference: true,
      title: {
        en: 'Trill',
        ru: 'Трель',
        de: 'Triller',
      },
      body: {
        en: 'Rapid alternation between a principal note and its upper neighbour. The starting note, any preparation and the ending depend on the period, instrument and edition.',
        ru: 'Быстрое чередование основного звука с верхним вспомогательным. Начальный звук, подготовка и окончание зависят от эпохи, инструмента и редакции.',
        de: 'Schneller Wechsel zwischen Hauptton und oberem Nebenton. Anfangston, Vorbereitung und Nachschlag richten sich nach Epoche, Instrument und Ausgabe.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'Mordent',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 8,
      reference: true,
      title: {
        en: 'Mordent',
        ru: 'Мордент',
        de: 'Mordent und Pralltriller',
      },
      body: {
        en: 'Specify upper or lower mordent rather than relying on the name alone. In the modern signs shown here, the unstruck form uses the upper neighbor, the struck-through form the lower. This identifies the sign, not a universal starting note or rhythm.',
        ru: 'Уточняйте вид: неперечёркнутый мордент связан с верхним вспомогательным звуком, перечёркнутый — с нижним. Здесь речь о показанных современных знаках, а не об универсальном начальном звуке или ритме исполнения.',
        de: 'Unterscheide den Pralltriller mit oberem Nebenton vom Mordent mit unterem Nebenton. Bei den hier gezeigten modernen Zeichen trägt die untere Form einen Strich. Damit ist das Zeichen bestimmt, nicht allgemein Anfangston oder Rhythmus.',
      },
      aliases: {
        en: 'upper mordent; lower mordent',
        ru: 'неперечёркнутый мордент; перечёркнутый мордент',
        de: 'Pralltriller; Mordent',
      },
      sourceId: 'source-036',
    },
    {
      id: 'Turn',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 9,
      reference: true,
      title: {
        en: 'Turn',
        ru: 'Группетто',
        de: 'Doppelschlag',
      },
      body: {
        en: 'A neighboring-note figure indicated by a turn sign; its placement relative to a note matters for timing.',
        ru: 'Фигура из основных и соседних звуков, обозначенная знаком группетто; положение знака относительно ноты существенно для времени исполнения.',
        de: 'Eine Nebentonfigur mit Doppelschlagzeichen; seine Stellung zur Note ist für den Zeitpunkt der Ausführung wesentlich.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'Grace note',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 10,
      reference: true,
      title: {
        en: 'Grace note',
        ru: 'Форшлаг',
        de: 'Vorschlag',
      },
      body: {
        en: 'Small notes indicate an embellishment before a principal note. A slashed stem is a distinct written form, not a universal timing formula.',
        ru: 'Мелкие ноты обозначают украшение перед основной нотой. Перечёркнутый штиль — отдельная форма записи, а не универсальная формула длительности.',
        de: 'Kleine Noten bezeichnen eine Verzierung vor einer Hauptnote. Ein durchstrichener Hals ist eine eigene Schreibform, keine allgemeine Zeitformel.',
      },
      sourceId: 'source-026',
    },
    {
      id: 'After-grace',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 11,
      reference: true,
      title: {
        en: 'After-grace',
        ru: 'Нахшлаг',
        de: 'Nachschlag',
      },
      body: {
        en: 'An embellishment following the principal note. Read its place within the phrase and the edition’s performance guidance.',
        ru: 'Украшение после основного звука. Учитывайте его место во фразе и исполнительские указания редакции.',
        de: 'Eine Verzierung nach dem Hauptton. Beachte ihre Stellung in der Phrase und die Ausführungshinweise der Ausgabe.',
      },
      sourceId: 'source-026',
    },
    {
      id: 'Slide ornament',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 12,
      reference: true,
      title: {
        en: 'Slide ornament',
        ru: 'Шлейфер',
        de: 'Schleifer',
      },
      body: {
        en: 'A short stepwise approach to a principal tone; its historical execution is not inferred from a generic playback preset.',
        ru: 'Короткий поступенный подход к основному звуку; историческое исполнение не выводят из универсальной настройки воспроизведения.',
        de: 'Eine kurze schrittweise Hinführung zum Hauptton; ihre historische Ausführung folgt keinem allgemeinen Wiedergabepreset.',
      },
      sourceId: 'source-036',
    },
    {
      id: 'Arpeggio sign',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 13,
      reference: true,
      title: {
        en: 'Arpeggio sign',
        ru: 'Знак арпеджиато',
        de: 'Arpeggiozeichen',
      },
      body: {
        en: 'A vertical wavy line asks that chord tones be spread in time. An arrow can specify direction.',
        ru: 'Вертикальная волнистая линия предлагает разложить звуки аккорда во времени. Стрелка может указывать направление.',
        de: 'Eine senkrechte Wellenlinie verlangt zeitlich versetzte Akkordtöne. Ein Pfeil kann die Richtung angeben.',
      },
      sourceId: 'source-027',
    },
    {
      id: 'Breath mark and caesura',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 19,
      reference: true,
      title: {
        en: 'Breath mark and caesura',
        ru: 'Знак дыхания и цезура',
        de: 'Atemzeichen und Zäsur',
      },
      body: {
        en: 'They mark a breath or break in the musical line. Unlike a numbered rest, their duration is not specified by a note value alone.',
        ru: 'Обозначают вдох или разрыв музыкальной линии. В отличие от паузы с определённой длительностью, время не задаётся одним нотным значением.',
        de: 'Sie kennzeichnen Atemholen oder einen Einschnitt in der musikalischen Linie. Anders als eine Pause mit festem Wert bestimmen sie die Dauer nicht allein durch einen Notenwert.',
      },
      sourceId: 'source-008',
    },
    {
      id: 'Chant divisions',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 20,
      reference: true,
      title: {
        en: 'Chant divisions',
        ru: 'Разделительные знаки хорала',
        de: 'Divisiones im Choral',
      },
      body: {
        en: 'Gregorian notation has its own phrase-division signs. Consult the chant edition; they are not ordinary metrical barlines.',
        ru: 'В григорианской нотации используются свои знаки разделения фраз. Обращайтесь к редакции хорала: это не обычные метрические тактовые черты.',
        de: 'Gregorianische Notation besitzt eigene Gliederungszeichen. Beachte die Choralausgabe; es sind keine gewöhnlichen metrischen Taktstriche.',
      },
      forwardModules: ['N04'],
      sourceId: 'source-004',
    },
    {
      id: 'Acciaccatura: distinguish the usage',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 37,
      reference: true,
      title: {
        en: 'Acciaccatura: distinguish the usage',
        ru: 'Аччаккатура: различайте значения',
        de: 'Acciaccatura: Gebrauch unterscheiden',
      },
      aliases: {
        en: 'acciaccatura; short grace',
        ru: 'аччаккатура; короткий форшлаг',
        de: 'Acciaccatura; kurzer Vorschlag; Zusammenschlag',
      },
      body: {
        en: 'Modern references often use acciaccatura for a small slashed grace note. Older keyboard usage can instead concern a crushed added tone within a chord. These are not interchangeable instructions. Recognize the printed form and consult the edition; a slash alone does not license a universal duration or onset.',
        ru: 'В современных справочниках acciaccatura часто называют мелкую перечёркнутую ноту форшлага. В старой клавирной практике слово может относиться к добавленному, быстро снимаемому звуку внутри аккорда. Это не взаимозаменяемые указания. Определите форму записи и обратитесь к редакции; одна черта не задаёт универсальные длительность и момент вступления.',
        de: 'Moderne Nachschlagewerke verwenden Acciaccatura häufig für eine kleine durchstrichene Vorschlagsnote. Älterer Tasteninstrumentengebrauch kann dagegen einen kurz angeschlagenen Zusatzton im Akkord meinen. Die Anweisungen sind nicht austauschbar. Erkenne die Schreibform und beachte die Ausgabe; ein Strich allein legt Dauer und Einsatz nicht allgemeingültig fest.',
      },
      sourceId: 'source-028',
      furtherSourceIds: ['source-036'],
    },
    {
      id: 'Unslashed grace note',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 38,
      reference: true,
      title: {
        en: 'Unslashed grace note',
        ru: 'Неперечёркнутый форшлаг',
        de: 'Nicht durchstrichener Vorschlag',
      },
      body: {
        en: 'A small note without the slash is a distinct written form, often associated with an appoggiatura or long grace. Its size does not tell you a universal fraction of the principal note. Recognition here stops at the notation; realization belongs to the specified period, instrument and edition.',
        ru: 'Мелкая нота без черты — отдельная форма записи, часто связанная с долгим форшлагом, апподжиатурой. Размер головки не определяет универсальную долю основной ноты. Здесь требуется узнать запись; исполнение зависит от указанной эпохи, инструмента и редакции.',
        de: 'Eine kleine Note ohne Strich ist eine eigene Schreibform, oft mit Appoggiatura oder langem Vorschlag verbunden. Die Kopfgröße bestimmt keinen allgemeinen Anteil am Hauptnotenwert. Hier geht es ums Erkennen; die Ausführung gehört zur angegebenen Epoche, zum Instrument und zur Ausgabe.',
      },
      sourceId: 'source-026',
    },
    {
      id: 'Non legato and leggiero',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 39,
      reference: true,
      title: {
        en: 'Non legato and leggiero',
        ru: 'Нон легато и легджиеро',
        de: 'Non legato und leggiero',
      },
      aliases: {
        en: 'non legato; leggiero; leggero',
        ru: 'нон легато; легджиеро; легко',
        de: 'non legato; leggiero; leggero',
      },
      body: {
        en: 'Non legato asks for notes that are not joined. Leggiero (also leggero) asks for lightness of delivery, not automatically shorter written values. A light phrase can still be connected. Read these words together with any slurs, dots and dynamic marks.',
        ru: 'Нон легато требует несвязного исполнения нот. Leggiero (также leggero) означает лёгкость подачи, а не автоматическое сокращение записанных длительностей. Лёгкая фраза может оставаться связной. Учитывайте лиги, точки и динамические знаки рядом с этими словами.',
        de: 'Non legato verlangt unverbundene Töne. Leggiero (auch leggero) verlangt Leichtigkeit, nicht automatisch kürzere Notenwerte. Eine leichte Phrase kann dennoch gebunden sein. Lies die Wörter zusammen mit Bögen, Punkten und dynamischen Angaben.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'articulation',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 127,
      reference: false,
      title: {
        en: 'Articulation',
        ru: 'Артикуляция',
        de: 'Artikulation',
      },
      body: {
        en: 'Articulation is how one note joins or separates from the note after it.',
        ru: 'Артикуляция — способ соединения или разделения соседних звуков.',
        de: 'Artikulation ist die Art, wie ein Ton mit dem folgenden verbunden oder von ihm getrennt wird.',
      },
      sourceId: 'source-037',
    },
    {
      id: 'staccato',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 128,
      reference: false,
      title: {
        en: 'Staccato',
        ru: 'Стаккато',
        de: 'Staccato',
      },
      body: {
        en: 'A dot above or below a note asks for detached playing: the sound is shortened within its written value. A dot to the right of the note instead increases its value.',
        ru: 'Точка над или под нотой означает отрывистое исполнение: звук укорачивается в пределах записанной длительности. Точка справа от ноты, напротив, увеличивает длительность.',
        de: 'Ein Punkt über oder unter der Note verlangt abgesetztes Spiel: Der Ton wird innerhalb seines Notenwerts verkürzt. Ein Punkt rechts neben der Note verlängert dagegen den Wert.',
      },
      sourceId: 'source-037',
    },
    {
      id: 'staccatissimo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 129,
      reference: false,
      title: {
        en: 'Staccatissimo',
        ru: 'Стаккатиссимо',
        de: 'Staccatissimo',
      },
      body: {
        en: 'In modern engraving a wedge asks for staccatissimo, shorter than staccato.',
        ru: 'В современной нотной графике клин означает стаккатиссимо — короче, чем стаккато.',
        de: 'Im modernen Notensatz verlangt der Keil Staccatissimo, kürzer als Staccato.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'tenuto',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 130,
      reference: false,
      title: {
        en: 'Tenuto',
        ru: 'Тенуто',
        de: 'Tenuto',
      },
      body: {
        en: 'A short horizontal line above or below a note asks that it be held, often with some emphasis. The instrument and context guide the execution; the line gives no fixed loudness.',
        ru: 'Короткая горизонтальная черта над или под нотой требует выдержать звук, нередко с подчёркиванием. Исполнение зависит от инструмента и контекста; фиксированной громкости знак не задаёт.',
        de: 'Ein kurzer waagerechter Strich über oder unter der Note verlangt Aushalten, oft mit einer Betonung. Instrument und Zusammenhang bestimmen die Ausführung; das Zeichen legt keine feste Lautstärke fest.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'portato',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 131,
      reference: false,
      title: {
        en: 'Portato',
        ru: 'Портато',
        de: 'Portato',
      },
      body: {
        en: 'Portato writes dots under a slur and asks for notes that are separated but not sharply detached.',
        ru: 'Портато записывают точками под лигой: звуки отделяются, но не резко.',
        de: 'Portato schreibt Punkte unter einem Bogen und verlangt Töne, die getrennt, aber nicht scharf abgesetzt sind.',
      },
      sourceId: 'source-015',
    },
    {
      id: 'phrasing',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'articulation',
      order: 132,
      reference: false,
      title: {
        en: 'Phrasing',
        ru: 'Фразировка',
        de: 'Phrasierung',
      },
      body: {
        en: 'Phrasing groups notes into units of musical sense and is not the same thing as articulation.',
        ru: 'Фразировка объединяет звуки в смысловые построения и не тождественна артикуляции.',
        de: 'Phrasierung fasst Töne zu Sinneinheiten zusammen und ist nicht dasselbe wie Artikulation.',
      },
      sourceId: 'source-008',
    },
  ],
};
export default content;
