import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'beat-division',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['staff'],
    locales: ['en', 'ru', 'de'],
    kind: 'measure',
    module: 'F05',
    roadmapIds: ['023', '024'],
    lessonIds: ['beat-division'],
    experimentIds: ['beat-division'],
    exerciseIds: ['irregular-group-written-value', 'compare-beaming'],
    conceptIds: [
      'Tuplet families',
      'Beat',
      'Triplet',
      'Duplet',
      'Irregular group',
      'Ratio mark',
      'Beam',
      'Grouping',
    ],
  },
  lesson: {
    id: 'beat-division',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'beat-division',
    title: {
      en: 'Dividing the beat',
      ru: 'Деление доли',
      de: 'Die Zählzeit teilen',
    },
    category: {
      en: 'Rhythm',
      ru: 'Ритм',
      de: 'Rhythmus',
    },
    summary: {
      en: 'Mark a division into three, and read beamed groups.',
      ru: 'Обозначайте деление на три и читайте группы под ребром.',
      de: 'Dreiteilungen kennzeichnen und Balkengruppen lesen.',
    },
    formula: {
      en: 'triplet = 3 in the time of 2  ·  ratio 7:4',
      ru: 'триоль = 3 вместо 2  ·  отношение 7:4',
      de: 'Triole = 3 statt 2  ·  Verhältnis 7:4',
    },
    paragraphs: [
      {
        en: 'Ordinary values halve successively. A tuplet changes that division: 3:2 means three written values in the time of two of the same value. The ratio, not the number of notes alone, determines the duration. Both 7:4 and 7:8 can occur; read the stated ratio and the surrounding meter.',
        ru: 'Обычные длительности последовательно делятся пополам. Особое деление меняет этот порядок: 3:2 означает три записанные длительности за время двух таких же. Длительность определяет отношение, а не одно число нот. Встречаются и 7:4, и 7:8; учитывайте указанное отношение и размер.',
        de: 'Reguläre Werte werden fortlaufend halbiert. Eine unregelmäßige Teilung verändert dieses Verhältnis: 3:2 bedeutet drei notierte Werte in der Zeit von zwei gleichen Werten. Das Verhältnis, nicht die Notenzahl allein, bestimmt die Dauer. Sowohl 7:4 als auch 7:8 kommen vor; lies das angegebene Verhältnis im Taktzusammenhang.',
      },
      {
        en: 'A beam replaces the flags on notes shorter than a quarter: one beam for each flag the note would carry. Beams group notes so that the beat can be seen at a glance, which is why grouping follows the metre rather than the melody. Modern vocal music is beamed by beat, like instrumental music.',
        ru: 'Ребро заменяет флажки у нот короче четверти: одно ребро на каждый флажок. Группировка под ребром показывает доли, поэтому она следует метру, а не рисунку мелодии. Современная вокальная музыка группируется по долям так же, как инструментальная; группировка по слогам — более старая практика.',
        de: 'Ein Balken ersetzt die Fähnchen bei Noten unter dem Viertelwert: ein Balken für jedes Fähnchen. Die Balkengruppen machen die Zählzeiten auf einen Blick sichtbar, deshalb richtet sich die Gruppierung nach dem Metrum und nicht nach der Melodie. Moderne Vokalmusik wird wie Instrumentalmusik nach Zählzeiten gebalkt; die Balkung nach Silben ist ältere Praxis.',
      },
    ],
    sourceId: 'source-051',
    experimentId: 'beat-division',
    reading: {
      pages: '12, 14–16',
      sourceId: 'source-052',
      text: {
        en: 'Read an explicit n:m as n written values in the time of m of those values. Three triplet eighths at 3:2 fill one quarter; two eighths at 2:3 fill a dotted quarter. Ratios such as 5:4, 7:4 and 13:12 must be stated in context. A tuplet may contain rests, subdivisions or ties. Beaming should reveal the chosen meter; historical vocal beaming can instead follow syllables.',
        ru: 'Явное отношение n:m означает n записанных длительностей за время m таких же длительностей. Три восьмые при 3:2 заполняют четверть; две восьмые при 2:3 — четверть с точкой. Отношения 5:4, 7:4 и 13:12 читают в указанном контексте. В особом делении возможны паузы, дробление и лиги. Рёбра помогают видеть размер; историческая вокальная группировка может следовать слогам.',
        de: 'Ein ausdrückliches Verhältnis n:m bedeutet n notierte Werte in der Zeit von m solchen Werten. Drei Achtel bei 3:2 füllen eine Viertel; zwei Achtel bei 2:3 eine punktierte Viertel. Verhältnisse wie 5:4, 7:4 und 13:12 müssen im Kontext angegeben sein. Eine unregelmäßige Teilung kann Pausen, Unterteilungen oder Haltebögen enthalten. Balken sollen die Taktgliederung zeigen; ältere Vokalnotation kann stattdessen Silben folgen.',
      },
      assetIds: [
        'figure-beamed',
        'figure-flagged',
        'figure-triplet',
        'figure-duplet',
        'figure-beamed-mixed',
        'figure-beamed-syllables',
        'figure-tuplet-mixed',
        'figure-tuplet-13-12',
        'figure-quartole',
        'figure-octole',
      ],
    },
  },
  experiment: {
    id: 'beat-division',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'beat-division',
    instructions: {
      en: 'At the same tempo, compare Two eighths per beat and Three triplet eighths per beat. Each example fills four beats; only the division changes.',
      ru: 'При одном темпе сравните две восьмые на долю и три триольные восьмые на долю. Каждый пример заполняет четыре доли; меняется только деление.',
      de: 'Vergleiche bei gleichem Tempo zwei Achtel und drei Triolenachtel je Zählzeit. Beide Beispiele füllen vier Zählzeiten; nur die Unterteilung ändert sich.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 329.627557,
      wave: 'square',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'division',
    },
  },
  exercises: [
    {
      id: 'irregular-group-written-value',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      label: {
        en: 'Read tuplet ratios',
        ru: 'Отношения при особом делении',
        de: 'Verhältnisse unregelmäßiger Teilungen lesen',
      },
      generator: 'tuplet',
      sourceIds: ['source-052'],
      kind: 'generated',
    },
    {
      id: 'compare-beaming',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      label: {
        en: 'Compare rhythmic grouping',
        ru: 'Сравнение ритмической группировки',
        de: 'Rhythmische Gruppierungen vergleichen',
      },
      generator: 'beaming-review',
      sourceIds: ['source-052'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Tuplet families',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 28,
      reference: true,
      title: {
        en: 'Tuplet families',
        ru: 'Виды особого деления',
        de: 'Unregelmäßige Teilungen',
      },
      aliases: {
        en: 'quintuplet; sextuplet; septuplet; nonuplet; 11-tuplet; 13-tuplet; 15-tuplet; 17-tuplet; quadruplet; octuplet',
        ru: 'квинтоль; секстоль; септоль; ноноль; квартоль; октоль',
        de: 'Quintole; Sextole; Septole; Nonole; Quartole; Oktole',
      },
      body: {
        en: 'Quintuplet, sextuplet, septuplet and nonuplet refer to groups of five, six, seven and nine. Larger numerals such as 11, 13, 15 or 17 also occur. They do not determine the replacement duration by themselves. At 13:12, thirteen written values occupy twelve such values. Duplets, quadruplets and octuplets can divide a dotted span evenly; compare their explicit ratios rather than inventing a universal convention.',
        ru: 'Квинтоль, секстоль, септоль и ноноль обозначают группы из пяти, шести, семи и девяти элементов. Встречаются также числа 11, 13, 15 и 17. Одно число ещё не определяет замещаемую длительность. При 13:12 тринадцать записанных длительностей занимают время двенадцати таких же. Дуоль, квартоль и октоль могут делить длительность с точкой на равные части; сравнивайте явные отношения.',
        de: 'Quintole, Sextole, Septole und Nonole benennen Gruppen von fünf, sechs, sieben und neun. Auch Zahlen wie 11, 13, 15 oder 17 kommen vor. Die Zahl allein bestimmt die ersetzte Dauer nicht. Bei 13:12 nehmen dreizehn notierte Werte die Zeit von zwölf solchen Werten ein. Duolen, Quartolen und Oktolen können einen punktierten Wert gleichmäßig teilen; vergleiche die ausdrücklichen Verhältnisse.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Beat',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 104,
      reference: false,
      title: {
        en: 'Beat',
        ru: 'Доля',
        de: 'Zählzeit',
      },
      body: {
        en: 'The unit of pulse that the written note values are counted against.',
        ru: 'Единица пульса, по которой отсчитываются записанные длительности.',
        de: 'Die Einheit des Pulses, gegen die die geschriebenen Notenwerte gezählt werden.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Triplet',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 105,
      reference: false,
      title: {
        en: 'Triplet',
        ru: 'Триоль',
        de: 'Triole',
      },
      body: {
        en: 'Three notes written in the time normally taken by two of that value.',
        ru: 'Три ноты, записанные во времени, которое обычно занимают две такие же.',
        de: 'Drei Noten in der Zeit, die sonst zwei desselben Wertes einnehmen.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Duplet',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 106,
      reference: false,
      title: {
        en: 'Duplet',
        ru: 'Дуоль',
        de: 'Duole',
      },
      body: {
        en: 'Two notes written in the time normally taken by three of that value.',
        ru: 'Две ноты, записанные во времени, которое обычно занимают три такие же.',
        de: 'Zwei Noten in der Zeit, die sonst drei desselben Wertes einnehmen.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Irregular group',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 107,
      reference: false,
      title: {
        en: 'Irregular group',
        ru: 'Особое деление длительностей',
        de: 'Unregelmäßige Teilung',
      },
      body: {
        en: 'A rhythmic division that replaces the usual subdivision with a specified ratio. In a 3:2 triplet, three written eighth-note units take the time of two ordinary eighths; the group may include rests.',
        ru: 'Деление длительности, заменяющее обычное дробление указанным отношением. В триоли 3:2 три записанные восьмые занимают время двух обычных восьмых; в группе возможны и паузы.',
        de: 'Eine rhythmische Teilung, die die übliche Unterteilung durch ein angegebenes Verhältnis ersetzt. In einer Triole 3:2 dauern drei notierte Achtel so lange wie zwei reguläre Achtel; die Gruppe kann auch Pausen enthalten.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Ratio mark',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 108,
      reference: false,
      title: {
        en: 'Ratio mark',
        ru: 'Цифровое отношение',
        de: 'Verhältnisangabe',
      },
      body: {
        en: 'Two numbers such as 7:4, printed when the written value could be misread.',
        ru: 'Два числа, например 7:4, которые печатают, когда запись можно прочесть неверно.',
        de: 'Zwei Zahlen wie 7:4, gedruckt, wenn der geschriebene Wert missverstanden werden könnte.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Beam',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 109,
      reference: false,
      title: {
        en: 'Beam',
        ru: 'Ребро',
        de: 'Balken',
      },
      body: {
        en: 'A thick line replacing flags; one beam stands for one flag.',
        ru: 'Толстая линия вместо флажков: одно ребро соответствует одному флажку.',
        de: 'Ein dicker Strich anstelle der Fähnchen; ein Balken steht für ein Fähnchen.',
      },
      sourceId: 'source-014',
    },
    {
      id: 'Grouping',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'beat-division',
      order: 110,
      reference: false,
      title: {
        en: 'Grouping',
        ru: 'Группировка',
        de: 'Gruppierung',
      },
      body: {
        en: 'The choice of which notes share a beam, so that the beat stays visible.',
        ru: 'Выбор нот под общим ребром, при котором доля остаётся видимой.',
        de: 'Die Wahl, welche Noten einen Balken teilen, damit die Zählzeit sichtbar bleibt.',
      },
      sourceId: 'source-014',
    },
  ],
};
export default content;
