import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'clefs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['note-names'],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F03',
    roadmapIds: ['013'],
    lessonIds: ['clefs'],
    experimentIds: ['clefs'],
    exerciseIds: ['same-place-other-clef', 'entry-clefs'],
    conceptIds: [
      'Ottava',
      'Instruments and clefs',
      'Keyboard and organ staves',
      'Clef',
      'Treble clef',
      'Bass clef',
      'C clef',
      'System',
      'Brace',
    ],
  },
  lesson: {
    id: 'clefs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'clefs',
    title: {
      en: 'One clef, one fixed pitch',
      ru: 'Ключ задаёт одну высоту',
      de: 'Ein Schlüssel, ein fester Ton',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Read the reference notes of treble, bass, alto and tenor clefs.',
      ru: 'Определяйте опорные ноты скрипичного, басового, альтового и тенорового ключей.',
      de: 'Lies die Bezugstöne von Violin-, Bass-, Alt- und Tenorschlüssel.',
    },
    formula: {
      en: 'G-clef line 2 = G4 · F-clef line 4 = F3 · C-clef = C4',
      ru: 'Соль-ключ, 2-я линейка = соль первой октавы · Фа-ключ, 4-я линейка = фа малой октавы · До-ключ = до первой октавы',
      de: 'G-Schlüssel 2. Linie = g′ · F-Schlüssel 4. Linie = f · C-Schlüssel = c′',
      ruMarkup:
        '[[Соль]]-ключ, 2-я линейка = [[соль]] первой октавы · [[Фа]]-ключ, 4-я линейка = [[фа]] малой октавы · [[До]]-ключ = [[до]] первой октавы',
    },
    paragraphs: [
      {
        en: 'A note’s position needs a clef to tell us its pitch. The treble clef is a G clef that places G4 on the second line; the bass clef is an F clef that places F3 on the fourth. Count neighbouring note names up or down from that reference. Different clefs place different registers conveniently on the same five lines and reduce the need for ledger lines.',
        ru: 'Чтобы определить высоту по положению ноты, нужен ключ. Скрипичный ключ — ключ соль: он указывает соль первой октавы на второй линейке. Басовый — ключ фа: он указывает фа малой октавы на четвёртой. От этой опорной ноты отсчитывают соседние ступени вверх или вниз. Разные ключи позволяют удобно записывать разные регистры на тех же пяти линейках и реже использовать добавочные.',
        de: 'Erst der Schlüssel ordnet einer Notenposition eine Tonhöhe zu. Der Violinschlüssel ist ein G-Schlüssel mit g′ auf der zweiten Linie; der Bassschlüssel ein F-Schlüssel mit f auf der vierten. Zähle von diesem Bezugston aus die benachbarten Stammtöne aufwärts oder abwärts. Verschiedene Schlüssel bringen unterschiedliche Tonlagen günstig auf denselben fünf Linien unter und sparen Hilfslinien.',
        ruMarkup:
          'Чтобы определить высоту по положению ноты, нужен ключ. Скрипичный ключ — ключ [[соль]]: он указывает [[соль]] первой октавы на второй линейке. Басовый — ключ [[фа]]: он указывает [[фа]] малой октавы на четвёртой. От этой опорной ноты отсчитывают соседние ступени вверх или вниз. Разные ключи позволяют удобно записывать разные регистры на тех же пяти линейках и реже использовать добавочные.',
      },
      {
        en: 'Middle C (C4) sits on the first ledger line below a treble staff or above a bass staff. C clefs mark C4 with their centre: the alto clef on the third line, the tenor clef on the fourth. Piano music usually joins two staves with a brace; read the clef printed on each staff.',
        ru: 'До первой октавы находится на первой добавочной линейке под скрипичным станом или над басовым. Ключи до указывают эту ноту своей серединой: альтовый — на третьей линейке, теноровый — на четвёртой. В фортепианной записи два стана обычно соединены акколадой; на каждом читайте его собственный ключ.',
        de: 'Das eingestrichene c (c′) steht auf der ersten Hilfslinie unter dem Violinsystem oder über dem Basssystem. C-Schlüssel markieren c′ mit ihrer Mitte: der Altschlüssel auf der dritten, der Tenorschlüssel auf der vierten Linie. Klaviermusik verbindet gewöhnlich zwei Notensysteme mit einer geschweiften Klammer; lies den Schlüssel jedes Systems.',
        ruMarkup:
          '[[До]] первой октавы находится на первой добавочной линейке под скрипичным станом или над басовым. Ключи [[до]] указывают эту ноту своей серединой: альтовый — на третьей линейке, теноровый — на четвёртой. В фортепианной записи два стана обычно соединены акколадой; на каждом читайте его собственный ключ.',
      },
    ],
    sourceId: 'source-029',
    experimentId: 'clefs',
    reading: {
      pages: '3–6',
      sourceId: 'source-002',
      text: {
        en: 'Treble: G4 on line 2; bass: F3 on line 4; alto: C4 on line 3; tenor: C4 on line 4. Viola commonly uses alto clef; cello, bassoon and trombone can use tenor clef for higher passages. An 8 below a clef lowers its sounding octave. An 8va bracket shifts one octave, a 15ma bracket two; follow its printed span.',
        ru: 'Скрипичный ключ указывает соль первой октавы на второй линейке; басовый — фа малой на четвёртой; альтовый — до первой на третьей; теноровый — до первой на четвёртой. Альт обычно читает альтовый ключ; виолончель, фагот и тромбон используют также теноровый. Восьмёрка под ключом понижает звучание на октаву. Пунктир 8va переносит на октаву, 15ma — на две, в пределах указанного участка.',
        de: 'Violinschlüssel: g′ auf Linie 2; Bassschlüssel: f auf Linie 4; Altschlüssel: c′ auf Linie 3; Tenorschlüssel: c′ auf Linie 4. Die Bratsche verwendet meist den Altschlüssel; Violoncello, Fagott und Posaune verwenden in höherer Lage auch den Tenorschlüssel. Eine 8 unter dem Schlüssel senkt die klingende Oktave. Eine 8va-Linie oktaviert um eine Oktave, 15ma um zwei; beachte ihren Geltungsbereich.',
        ruMarkup:
          'Скрипичный ключ указывает [[соль]] первой октавы на второй линейке; басовый — [[фа]] малой на четвёртой; альтовый — [[до]] первой на третьей; теноровый — [[до]] первой на четвёртой. Альт обычно читает альтовый ключ; виолончель, фагот и тромбон используют также теноровый. Восьмёрка под ключом понижает звучание на октаву. Пунктир 8va переносит на октаву, 15ma — на две, в пределах указанного участка.',
      },
      assetIds: ['figure-grand-staff', 'figure-organ-staves'],
    },
  },
  experiment: {
    id: 'clefs',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'clefs',
    instructions: {
      en: 'Play G4, then F3, and hear how far apart the reference pitches of these two clefs actually sound.',
      ru: 'Сыграйте соль первой октавы, затем фа малой октавы и услышьте, как далеко расходятся опорные ноты двух ключей.',
      de: 'Spiele g′ und danach das kleine f und höre, wie weit die Bezugstöne dieser beiden Schlüssel auseinanderliegen.',
      ruMarkup:
        'Сыграйте [[соль]] первой октавы, затем [[фа]] малой октавы и услышьте, как далеко расходятся опорные ноты двух ключей.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 391.995436,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'same-place-other-clef',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      label: {
        en: 'Read the same position in another clef',
        ru: 'Та же позиция в другом ключе',
        de: 'Dieselbe Position in einem anderen Schlüssel lesen',
      },
      generator: 'clef-transform',
      sourceIds: ['source-002'],
      kind: 'generated',
    },
    {
      id: 'entry-clefs',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      kind: 'diagnostic',
      order: 1,
      label: {
        en: 'What does a clef establish on a staff?',
        ru: 'Что определяет ключ на нотном стане?',
        de: 'Was legt ein Schlüssel im Notensystem fest?',
      },
      answer: 'pitch',
      options: [
        {
          id: 'pitch',
          label: {
            en: 'A reference for reading pitch positions',
            ru: 'Опору для чтения высоты нот',
            de: 'Einen Bezugspunkt zum Lesen der Tonhöhen',
          },
          feedback: {
            en: 'The clef anchors a pitch to a staff position, allowing the other positions to be read.',
            ru: 'Ключ закрепляет высоту за позицией на стане, позволяя читать остальные позиции.',
            de: 'Der Schlüssel ordnet einer Position eine Tonhöhe zu. Damit lassen sich die übrigen Positionen lesen.',
          },
        },
        {
          id: 'duration',
          label: {
            en: 'The duration of each note',
            ru: 'Длительность каждой ноты',
            de: 'Die Dauer jeder Note',
          },
          feedback: {
            en: 'Note values show duration. The clef instead supplies a reference for pitch positions.',
            ru: 'Длительность показывают нотные знаки соответствующих длительностей. Ключ задаёт опору для чтения высоты.',
            de: 'Notenwerte zeigen die Dauer. Der Schlüssel liefert dagegen einen Bezugspunkt für die Tonhöhen.',
          },
        },
        {
          id: 'loudness',
          label: {
            en: 'The loudness of each note',
            ru: 'Громкость каждой ноты',
            de: 'Die Lautstärke jeder Note',
          },
          feedback: {
            en: 'Dynamics concern loudness. A clef anchors pitch positions, not loudness.',
            ru: 'К громкости относятся динамические обозначения. Ключ задаёт высоту позиций, а не громкость.',
            de: 'Dynamische Angaben betreffen die Lautstärke. Ein Schlüssel legt Tonhöhenbezüge fest, keine Lautstärke.',
          },
        },
      ],
      sourceIds: ['source-059'],
    },
  ],
  concepts: [
    {
      id: 'Ottava',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 4,
      reference: true,
      title: {
        en: 'Ottava',
        ru: 'Октавный перенос',
        de: 'Oktavierung',
      },
      body: {
        en: '8 shifts one octave; 15 shifts two. Placement above or below indicates direction, and the line gives the scope.',
        ru: '8 переносит на октаву, 15 — на две. Положение сверху или снизу задаёт направление, пунктир — область действия.',
        de: '8 versetzt um eine Oktave, 15 um zwei. Die Stellung oben oder unten gibt die Richtung an, die Linie den Geltungsbereich.',
      },
      sourceId: 'source-002',
    },
    {
      id: 'Instruments and clefs',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 23,
      reference: true,
      title: {
        en: 'Instruments and clefs',
        ru: 'Инструменты и ключи',
        de: 'Instrumente und Schlüssel',
      },
      aliases: {
        en: 'viola; cello; bassoon; trombone; flute',
        ru: 'альт; виолончель; фагот; тромбон; флейта',
        de: 'Bratsche; Violoncello; Fagott; Posaune; Flöte',
      },
      body: {
        en: 'Read the printed clef, not an assumed instrument rule. Flute parts commonly use treble; viola parts alto and sometimes treble; cello parts bass, tenor or treble according to register. Tenor clef also occurs in bassoon and trombone parts. A clef change changes the pitch anchor, not the instrument.',
        ru: 'Читайте выставленный ключ, не подменяя его правилом об инструменте. Флейта обычно использует скрипичный; альт — альтовый, иногда скрипичный; виолончель — басовый, теноровый или скрипичный в зависимости от регистра. Теноровый встречается также у фагота и тромбона. Смена ключа меняет высотный ориентир, а не инструмент.',
        de: 'Lies den gedruckten Schlüssel statt einer vermeintlichen Instrumentenregel. Die Flöte verwendet meist den Violin-, die Bratsche den Alt- und gelegentlich den Violinschlüssel; das Violoncello je nach Lage Bass-, Tenor- oder Violinschlüssel. Der Tenorschlüssel kommt auch bei Fagott und Posaune vor. Ein Schlüsselwechsel ändert den Tonhöhenbezug, nicht das Instrument.',
      },
      forwardModules: ['N03'],
      sourceId: 'source-029',
      furtherSourceIds: ['source-030', 'source-031'],
    },
    {
      id: 'Keyboard and organ staves',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 24,
      reference: true,
      title: {
        en: 'Keyboard and organ staves',
        ru: 'Станы фортепиано и органа',
        de: 'Klavier- und Orgelsysteme',
      },
      aliases: {
        en: 'grand staff; organ pedals; bracket',
        ru: 'фортепианная система; педаль органа; скобка',
        de: 'Klavierakkolade; Orgelpedal; Klammer',
      },
      body: {
        en: 'A piano part commonly combines two staves with a brace. Organ notation commonly adds a third staff for the pedals below the two manual staves. This is a layout convention: a hand or voice can cross between staves, and neither staff is permanently restricted to one clef.',
        ru: 'Фортепианная партия обычно объединяет два стана акколадой. В органной записи ниже двух мануальных станов часто расположен третий — для педали. Это способ размещения записи: рука или голос могут переходить между станами, и за станом не закреплён навсегда один ключ.',
        de: 'Eine Klavierstimme verbindet meist zwei Notensysteme mit einer geschweiften Klammer. Bei der Orgel steht unter den beiden Manualsystemen häufig ein drittes System für das Pedal. Das ist eine Anordnungskonvention: Hand oder Stimme können das System wechseln; kein System ist auf einen einzigen Schlüssel festgelegt.',
      },
      forwardModules: ['N03'],
      sourceId: 'source-022',
    },
    {
      id: 'Clef',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 67,
      reference: false,
      title: {
        en: 'Clef',
        ru: 'Ключ',
        de: 'Notenschlüssel',
      },
      body: {
        en: 'A clef fixes one named pitch on one staff line, and every other pitch is counted from it.',
        ru: 'Ключ закрепляет одну названную ноту на определённой линейке, и от неё отсчитываются все остальные.',
        de: 'Ein Notenschlüssel legt einen benannten Ton auf einer Linie fest, von dem aus alle anderen gezählt werden.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Treble clef',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 68,
      reference: false,
      title: {
        en: 'Treble clef',
        ru: 'Скрипичный ключ',
        de: 'Violinschlüssel',
      },
      body: {
        en: 'The treble clef is the G-clef whose curl encircles the second line and fixes G4 there.',
        ru: 'Скрипичный ключ — соль-ключ, завиток которого обвивает вторую линейку и закрепляет на ней соль первой октавы.',
        de: 'Der Violinschlüssel ist der G-Schlüssel, dessen Schleife die zweite Linie umschließt und dort g′ festlegt.',
        ruMarkup:
          'Скрипичный ключ — [[соль]]-ключ, завиток которого обвивает вторую линейку и закрепляет на ней [[соль]] первой октавы.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'Bass clef',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 69,
      reference: false,
      title: {
        en: 'Bass clef',
        ru: 'Басовый ключ',
        de: 'Bassschlüssel',
      },
      body: {
        en: 'The bass clef is the F-clef whose two dots surround the fourth line and fix F3 there.',
        ru: 'Басовый ключ — фа-ключ, две точки которого стоят по сторонам четвёртой линейки и закрепляют на ней фа малой октавы.',
        de: 'Der Bassschlüssel ist der F-Schlüssel, dessen zwei Punkte die vierte Linie einschließen und dort das kleine f festlegen.',
        ruMarkup:
          'Басовый ключ — [[фа]]-ключ, две точки которого стоят по сторонам четвёртой линейки и закрепляют на ней [[фа]] малой октавы.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'C clef',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 70,
      reference: false,
      title: {
        en: 'C clef',
        ru: 'До-ключ',
        de: 'C-Schlüssel',
        ruMarkup: '[[До]]-ключ',
      },
      body: {
        en: 'A C clef names C4 on the line its centre marks: the third line for the alto clef, the fourth for the tenor clef.',
        ru: 'До-ключ указывает до первой октавы на той линейке, где сходятся его половины: третья — альтовый ключ, четвёртая — теноровый.',
        de: 'Ein C-Schlüssel benennt c′ auf der Linie, die seine Mitte bezeichnet: die dritte beim Altschlüssel, die vierte beim Tenorschlüssel.',
        ruMarkup:
          '[[До]]-ключ указывает [[до]] первой октавы на той линейке, где сходятся его половины: третья — альтовый ключ, четвёртая — теноровый.',
      },
      sourceId: 'source-023',
    },
    {
      id: 'System',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 71,
      reference: false,
      title: {
        en: 'System',
        ru: 'Система',
        de: 'Akkolade',
      },
      body: {
        en: 'A system is the set of staves that are read together because they sound at the same time.',
        ru: 'Система — группа нотоносцев, которые читают вместе, потому что они звучат одновременно.',
        de: 'Eine Akkolade ist die Gruppe von Notensystemen, die zusammen gelesen werden, weil sie gleichzeitig erklingen.',
      },
      sourceId: 'source-022',
    },
    {
      id: 'Brace',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'clefs',
      order: 72,
      reference: false,
      title: {
        en: 'Brace',
        ru: 'Акколада',
        de: 'Geschweifte Klammer',
      },
      body: {
        en: 'A brace is the curved sign that joins two staves into a single keyboard system.',
        ru: 'Акколада — фигурная скобка, которая соединяет нотоносцы в одну систему.',
        de: 'Die geschweifte Klammer ist das Zeichen, das zwei Notensysteme zu einer Akkolade verbindet.',
      },
      sourceId: 'source-022',
    },
  ],
};
export default content;
