import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'dots-ties',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['staff'],
    locales: ['en', 'ru', 'de'],
    kind: 'measure',
    module: 'F05',
    roadmapIds: ['022'],
    lessonIds: ['dots-ties'],
    experimentIds: ['dots-ties'],
    exerciseIds: [
      'dot-adds-half',
      'second-dot-adds-half-the-first',
      'tied-values-add',
      'entry-dots-ties',
    ],
    conceptIds: ['Dotted note', 'Double dot', 'Dotted rest', 'Slur', 'Legato'],
  },
  lesson: {
    id: 'dots-ties',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'dots-ties',
    title: {
      en: 'Dots and ties',
      ru: 'Точки и связующие лиги',
      de: 'Punkte und Haltebögen',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Write lengths the plain halving series cannot reach.',
      ru: 'Записывайте длительности, которых нет в делении пополам.',
      de: 'Werte schreiben, die das reine Halbieren nicht liefert.',
    },
    formula: {
      en: 'Dotted value = original × 3/2 · double-dotted = original × 7/4 · tie: add values',
      ru: 'С точкой = исходная длительность × 3/2 · с двумя = × 7/4 · связующая лига: сумма длительностей',
      de: 'Punktiert = Ausgangswert × 3/2 · doppelt punktiert = × 7/4 · Haltebogen: Werte addieren',
    },
    paragraphs: [
      {
        en: "A dot after a note head adds half of that note's value. A dotted note therefore lasts as long as three of the next smaller unit: a dotted half equals three quarters. A second dot adds half of what the first dot added, and the same rule applies to rests.",
        ru: 'Точка справа от головки прибавляет половину длительности этой ноты. Поэтому нота с точкой равна трём следующим меньшим: половинная с точкой — трём четвертям. Вторая точка прибавляет половину того, что прибавила первая. То же правило действует и для пауз.',
        de: 'Ein Punkt hinter dem Notenkopf verlängert die Note um die Hälfte ihres Wertes. Eine punktierte Note dauert deshalb so lange wie drei des nächstkleineren Wertes: eine punktierte Halbe entspricht drei Vierteln. Ein zweiter Punkt fügt die Hälfte des ersten Punktes hinzu. Für Pausen gilt dieselbe Regel.',
      },
      {
        en: 'A tie joins equal pitches into one sustained sound and adds their durations, including across barlines. An articulation slur connects a group of notes without adding their values. A phrasing slur describes a larger musical grouping.',
        ru: 'Связующая лига объединяет ноты одной высоты в протяжённый звук и складывает их длительности, в том числе через тактовую черту. Артикуляционная лига связывает группу нот, не складывая их длительности. Фразировочная лига обозначает более крупное смысловое объединение.',
        de: 'Ein Haltebogen verbindet gleiche Tonhöhen zu einem gehaltenen Klang und addiert ihre Dauern, auch über Taktstriche hinweg. Ein Bindebogen verbindet eine Notengruppe, ohne deren Werte zu addieren. Ein Phrasierungsbogen bezeichnet eine größere musikalische Einheit.',
      },
    ],
    sourceId: 'source-050',
    experimentId: 'dots-ties',
    reading: {
      pages: '13, 16–17',
      sourceId: 'source-009',
      text: {
        en: 'A dotted quarter equals three eighths; a double-dotted quarter equals seven sixteenths. Dots also extend rests. Tied notes add their durations without a new attack. A tie links equal pitches; a slur indicates connection or grouping and does not add their values. Whether a value fits in the bar is arithmetic; whether its spelling shows the beat clearly is a separate question.',
        ru: 'Четверть с точкой равна трём восьмым, с двумя точками — семи шестнадцатым. Точки увеличивают и паузы. Связующая лига суммирует длительности без новой атаки. Она соединяет ноты одной высоты; артикуляционная лига указывает связность или группировку и не складывает их длительности. Помещается ли значение в такт — вопрос арифметики; хорошо ли запись показывает доли — отдельный вопрос.',
        de: 'Eine punktierte Viertel entspricht drei Achteln, eine doppelt punktierte Viertel sieben Sechzehnteln. Punkte verlängern auch Pausen. Ein Haltebogen addiert Dauern ohne neuen Anschlag. Er verbindet gleiche Tonhöhen; ein Bindebogen zeigt Verbindung oder Gruppierung und addiert keine Werte. Ob ein Wert in den Takt passt, ist eine Rechenfrage; ob seine Schreibweise die Zählzeiten gut zeigt, eine andere.',
      },
      assetIds: [
        'figure-dotted',
        'figure-double-dotted',
        'figure-tied',
        'figure-dotted-rest',
        'figure-cross-bar-tie',
      ],
    },
  },
  experiment: {
    id: 'dots-ties',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'dots-ties',
    instructions: {
      en: 'Compare Two separate quarter notes with Two quarter notes tied. Both fill two beats; the tied example has one attack and one sustained sound.',
      ru: 'Сравните две отдельные четверти с двумя четвертями под лигой продления. Обе записи заполняют две доли; под лигой слышны одна атака и один протяжённый звук.',
      de: 'Vergleiche zwei getrennte Viertelnoten mit zwei Vierteln unter einem Haltebogen. Beide füllen zwei Zählzeiten; das gebundene Beispiel hat nur einen Toneinsatz und einen durchgehenden Klang.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 293.664768,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 1,
        accidental: 0,
        octave: 4,
      },
      group: 'ties',
    },
  },
  exercises: [
    {
      id: 'dot-adds-half',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      label: {
        en: 'Read a dotted value',
        ru: 'Длительность с точкой',
        de: 'Einen punktierten Wert lesen',
      },
      generator: 'dotted-value',
      sourceIds: ['source-009'],
      kind: 'generated',
    },
    {
      id: 'second-dot-adds-half-the-first',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      label: {
        en: 'Read a double-dotted value',
        ru: 'Длительность с двумя точками',
        de: 'Einen doppelt punktierten Wert lesen',
      },
      generator: 'dotted-value',
      sourceIds: ['source-009'],
      kind: 'generated',
    },
    {
      id: 'tied-values-add',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      label: {
        en: 'Add tied durations',
        ru: 'Сумма длительностей под связующей лигой',
        de: 'Übergebundene Dauern addieren',
      },
      generator: 'tie-sum',
      sourceIds: ['source-009'],
      kind: 'generated',
    },
    {
      id: 'entry-dots-ties',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      kind: 'diagnostic',
      order: 2,
      label: {
        en: 'How many quarter-note durations equal one dotted half note?',
        ru: 'Скольким четвертям равна половинная нота с точкой?',
        de: 'Wie vielen Viertelnoten entspricht eine punktierte halbe Note?',
      },
      answer: 'three',
      options: [
        {
          id: 'two',
          label: {
            en: 'Two',
            ru: 'Двум',
            de: 'Zwei',
          },
          feedback: {
            en: 'Two quarters make the undotted half note. Its dot adds one more quarter: three in total.',
            ru: 'Две четверти составляют половинную без точки. Точка добавляет ещё четверть: всего три.',
            de: 'Zwei Viertel ergeben die unpunktierte halbe Note. Der Punkt fügt ein Viertel hinzu: insgesamt drei.',
          },
        },
        {
          id: 'four',
          label: {
            en: 'Four',
            ru: 'Четырём',
            de: 'Vier',
          },
          feedback: {
            en: 'The dot adds half of the original value, rather than doubling it: two quarters plus one is three.',
            ru: 'Точка добавляет половину исходной длительности, а не удваивает её: две четверти плюс одна — три.',
            de: 'Der Punkt fügt die Hälfte des ursprünglichen Werts hinzu, statt ihn zu verdoppeln: zwei Viertel plus eines sind drei.',
          },
        },
        {
          id: 'three',
          label: {
            en: 'Three',
            ru: 'Трём',
            de: 'Drei',
          },
          feedback: {
            en: 'A half note is two quarters. The dot adds half that value, one quarter, giving three quarters.',
            ru: 'Половинная равна двум четвертям. Точка добавляет половину этой длительности — одну четверть; получается три четверти.',
            de: 'Eine halbe Note entspricht zwei Vierteln. Der Punkt fügt die Hälfte dieses Werts hinzu, also ein Viertel: insgesamt drei Viertel.',
          },
        },
      ],
      sourceIds: ['source-060'],
    },
  ],
  concepts: [
    {
      id: 'Dotted note',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      order: 99,
      reference: false,
      title: {
        en: 'Dotted note',
        ru: 'Нота с точкой',
        de: 'Punktierte Note',
      },
      body: {
        en: 'A note followed by a dot, lasting three of the next smaller unit.',
        ru: 'Нота с точкой справа, равная трём следующим меньшим длительностям.',
        de: 'Eine Note mit Punkt, die drei nächstkleinere Werte lang dauert.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Double dot',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      order: 100,
      reference: false,
      title: {
        en: 'Double dot',
        ru: 'Двойная точка',
        de: 'Doppelpunktierung',
      },
      body: {
        en: 'A second dot that adds half of what the first dot added.',
        ru: 'Вторая точка, прибавляющая половину того, что прибавила первая.',
        de: 'Ein zweiter Punkt, der die Hälfte des ersten Punktes hinzufügt.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Dotted rest',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      order: 101,
      reference: false,
      title: {
        en: 'Dotted rest',
        ru: 'Пауза с точкой',
        de: 'Punktierte Pause',
      },
      body: {
        en: 'A rest lengthened by a dot in exactly the way a note is.',
        ru: 'Пауза, удлинённая точкой точно так же, как нота.',
        de: 'Eine Pause, die ein Punkt genauso verlängert wie eine Note.',
      },
      sourceId: 'source-019',
    },
    {
      id: 'Slur',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      order: 102,
      reference: false,
      title: {
        en: 'Slur',
        ru: 'Артикуляционная лига',
        de: 'Bindebogen',
      },
      body: {
        en: 'A curved line above or below a group of notes indicating connection or grouping. Depending on the instrument, it can also specify a playing technique. Unlike a tie, it does not add the notes’ values into one sustained sound.',
        ru: 'Дуга над или под группой нот, обозначающая связное исполнение или объединение группы. В зависимости от инструмента она может указывать и приём игры. В отличие от связующей лиги, она не складывает длительности в один выдержанный звук.',
        de: 'Ein Bogen über oder unter einer Notengruppe, der Verbindung oder Gruppierung anzeigt. Je nach Instrument kann er auch eine Spieltechnik vorschreiben. Anders als ein Haltebogen addiert er die Notenwerte nicht zu einem gehaltenen Ton.',
      },
      sourceId: 'source-008',
    },
    {
      id: 'Legato',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dots-ties',
      order: 103,
      reference: false,
      title: {
        en: 'Legato',
        ru: 'Легато',
        de: 'Legato',
      },
      body: {
        en: 'Playing or singing without a break between consecutive notes.',
        ru: 'Исполнение без разрыва между соседними нотами.',
        de: 'Spielen oder Singen ohne Unterbrechung zwischen aufeinanderfolgenden Tönen.',
      },
      sourceId: 'source-018',
    },
  ],
};
export default content;
