import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'durations',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['staff'],
    locales: ['en', 'ru', 'de'],
    kind: 'measure',
    module: 'F04',
    roadmapIds: ['017'],
    lessonIds: ['durations'],
    experimentIds: ['durations'],
    exerciseIds: ['identify-written-duration'],
    conceptIds: [
      'Multi-measure rest',
      'Stem direction',
      'Duration names and aliases',
      'Historical multi-measure rests',
      'Note value',
      'Whole note',
      'Rest',
      'Whole-bar rest',
      'Flag',
    ],
  },
  lesson: {
    id: 'durations',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'durations',
    title: {
      en: 'Note values and rests',
      ru: 'Длительности и паузы',
      de: 'Notenwerte und Pausen',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Read how long each written note lasts.',
      ru: 'Читайте, как долго звучит каждая записанная нота.',
      de: 'Lesen, wie lange eine geschriebene Note dauert.',
    },
    formula: {
      en: 'whole = 2 halves = 4 quarters = 8 eighths = 16 sixteenths',
      ru: 'целая = 2 половинные = 4 четверти = 8 восьмых = 16 шестнадцатых',
      de: 'Ganze = 2 Halbe = 4 Viertel = 8 Achtel = 16 Sechzehntel',
    },
    paragraphs: [
      {
        en: 'A note value says how long a note lasts in relation to the others, not in seconds. Each value is two of the next smaller one. The chain runs whole, half, quarter, eighth, sixteenth, and continues by halving. Only a tempo turns these relations into clock time.',
        ru: 'Длительность показывает, как долго звучит нота по отношению к другим, а не в секундах. Каждая длительность вмещает две следующие меньшие: целая, половинная, четверть, восьмая, шестнадцатая — и дальше делением пополам. Только темп превращает эти отношения в реальное время.',
        de: 'Ein Notenwert sagt, wie lange eine Note im Verhältnis zu den anderen klingt, nicht in Sekunden. Jeder Wert enthält zwei des nächstkleineren: ganze Note, halbe Note, Viertelnote, Achtelnote, Sechzehntelnote und so weiter durch Halbieren. Erst das Tempo macht daraus messbare Zeit.',
      },
      {
        en: 'The shape of a note carries its value. An open head without a stem is a whole note; with a stem it is a half; a filled head a quarter, and each added flag halves the value again. Every value has its own rest, and the whole rest also stands for a silent bar.',
        ru: 'Форма ноты задаёт её длительность. Пустая головка без штиля — целая, со штилем — половинная, закрашенная головка — четверть, и каждый следующий флажок снова делит длительность пополам. У каждой длительности есть своя пауза, а целая пауза обозначает и молчание всего такта любого размера.',
        de: 'Die Form der Note trägt ihren Wert. Ein leerer Kopf ohne Hals ist eine ganze Note, mit Hals eine halbe, ein ausgefüllter Kopf eine Viertelnote, und jedes weitere Fähnchen halbiert den Wert erneut. Zu jedem Wert gehört eine eigene Pause; die ganze Pause gilt außerdem als Taktpause, gleich wie lang der Takt ist.',
      },
    ],
    sourceId: 'source-009',
    experimentId: 'durations',
    reading: {
      pages: '11–13, 17',
      sourceId: 'source-009',
      text: {
        en: 'Read the halving chain through the 128th. Every additional flag or beam halves a filled note’s value. Rests have corresponding values; a whole-bar rest instead fills the stated meter. In 3/4 it lasts three quarters; in 6/8, six eighths. A multi-measure rest carries the number of complete bars. English pairs include whole/semibreve, half/minim, quarter/crotchet and eighth/quaver.',
        ru: 'Читайте последовательное деление длительностей пополам вплоть до сто двадцать восьмой. Каждый дополнительный флажок или ребро вдвое сокращает длительность закрашенной ноты. Паузам соответствуют те же значения; тактовая пауза заполняет весь указанный такт: три четверти в 3/4, шесть восьмых в 6/8. Число над многотактовой паузой обозначает количество целых тактов.',
        de: 'Lies die Halbierungsfolge bis zur Hundertachtundzwanzigstelnote. Jedes zusätzliche Fähnchen oder jeder weitere Balken halbiert den Wert einer ausgefüllten Note. Pausen haben entsprechende Werte; die Ganztaktpause füllt dagegen den angegebenen Takt: drei Viertel in 3/4, sechs Achtel in 6/8. Die Zahl über einer Mehrtaktpause nennt die Anzahl ganzer Takte.',
      },
      assetIds: [
        'figure-note-1',
        'figure-note-2',
        'figure-note-4',
        'figure-note-8',
        'figure-note-16',
        'figure-note-32',
        'figure-note-64',
        'figure-note-128',
        'figure-rest-1',
        'figure-rest-2',
        'figure-rest-4',
        'figure-rest-8',
        'figure-rest-16',
        'figure-rest-32',
        'figure-rest-64',
        'figure-rest-128',
        'figure-whole-bar-3',
        'figure-whole-bar-6',
        'figure-multi-rest',
        'figure-stem-directions',
        'figure-historical-multirests',
      ],
    },
  },
  experiment: {
    id: 'durations',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'durations',
    instructions: {
      en: 'Compare One whole note, Two half notes and Four quarter notes at the same tempo. The written values fill the same four quarter-note beats; count the attacks.',
      ru: 'При одном темпе сравните «Одна целая», «Две половинные» и «Четыре четверти». Записанные длительности заполняют одинаковые четыре четвертные доли; считайте атаки.',
      de: 'Vergleiche bei gleichem Tempo eine ganze Note, zwei halbe Noten und vier Viertelnoten. Die notierten Werte füllen dieselben vier Viertelzählzeiten; zähle die Toneinsätze.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 261.625565,
      wave: 'square',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'durations',
    },
  },
  exercises: [
    {
      id: 'identify-written-duration',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      label: {
        en: 'Recognize note and rest values',
        ru: 'Распознавание длительностей нот и пауз',
        de: 'Noten- und Pausenwerte erkennen',
      },
      generator: 'value-identification',
      sourceIds: ['source-009'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Multi-measure rest',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 5,
      reference: true,
      title: {
        en: 'Multi-measure rest',
        ru: 'Многотактовая пауза',
        de: 'Mehrtaktpause',
      },
      body: {
        en: 'Its number counts complete silent measures, not note values.',
        ru: 'Число указывает количество целых тактов молчания, а не длительностей нот.',
        de: 'Ihre Zahl zählt vollständige pausierende Takte, nicht Notenwerte.',
      },
      sourceId: 'source-019',
    },
    {
      id: 'Stem direction',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 25,
      reference: true,
      title: {
        en: 'Stem direction',
        ru: 'Направление штиля',
        de: 'Halsrichtung',
      },
      body: {
        en: 'An upward stem attaches to the right of the head, a downward stem to the left. For isolated notes in one voice, stems normally point toward the staff center; the middle-line note normally points down. Beamed groups, chords and multiple voices can override this convention: opposite stems can identify separate voices rather than different durations.',
        ru: 'Штиль вверх примыкает к головке справа, вниз — слева. У отдельных нот одного голоса штиль обычно направлен к середине стана; на средней линейке — вниз. Группировка, аккорды и многоголосие могут менять это правило: встречные штили способны обозначать разные голоса, а не разные длительности.',
        de: 'Ein aufwärts gerichteter Hals sitzt rechts am Kopf, ein abwärts gerichteter links. Bei einzelnen Noten einer Stimme zeigt er meist zur Systemmitte; auf der Mittellinie gewöhnlich nach unten. Balkengruppen, Akkorde und mehrere Stimmen können davon abweichen: Gegenläufige Hälse können Stimmen unterscheiden, nicht Notenwerte.',
      },
      sourceId: 'source-024',
    },
    {
      id: 'Duration names and aliases',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 26,
      reference: true,
      title: {
        en: 'Duration names and aliases',
        ru: 'Названия длительностей',
        de: 'Namen der Notenwerte',
      },
      aliases: {
        en: 'semibreve; minim; crotchet; quaver; semiquaver; demisemiquaver; hemidemisemiquaver; half note; quarter note; eighth note; sixteenth note; thirty-second note; sixty-fourth note; 128th note',
        ru: 'половинная; четверть; восьмая; шестнадцатая; тридцать вторая; шестьдесят четвёртая; сто двадцать восьмая',
        de: 'Halbe; Viertel; Achtel; Sechzehntel; Zweiunddreißigstel; Vierundsechzigstel; Hundertachtundzwanzigstel',
      },
      body: {
        en: 'American whole, half, quarter and eighth correspond to British semibreve, minim, crotchet and quaver. Sixteenth, thirty-second and sixty-fourth are semiquaver, demisemiquaver and hemidemisemiquaver. The names change, not the ratios: each step halves the value; 128th continues that chain. Matching rest names describe silence of the same written duration.',
        ru: 'После целой следуют половинная, четверть, восьмая, шестнадцатая, тридцать вторая, шестьдесят четвёртая и сто двадцать восьмая. Каждая следующая длительность вдвое меньше предыдущей. Для пауз используются соответствующие названия. В англоязычных изданиях американское quarter note и британское crotchet, например, обозначают одну и ту же четверть.',
        de: 'Auf die Ganze folgen Halbe, Viertel, Achtel, Sechzehntel, Zweiunddreißigstel, Vierundsechzigstel und Hundertachtundzwanzigstel. Jeder Schritt halbiert den Wert; die entsprechenden Pausen haben dieselben Dauern. In englischen Ausgaben bezeichnen etwa quarter note und crotchet denselben Viertelwert: verschiedene Benennungen, keine verschiedenen Rhythmen.',
      },
      sourceId: 'source-020',
    },
    {
      id: 'Historical multi-measure rests',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 27,
      reference: true,
      title: {
        en: 'Historical multi-measure rests',
        ru: 'Исторические многотактовые паузы',
        de: 'Kirchenpausen',
      },
      body: {
        en: 'Some editions combine longa-, breve- and whole-rest shapes to show a short run of silent measures. A modern horizontal multi-rest with a number is another representation. Read the measure count and edition convention; do not mistake these combined symbols for a single ordinary rest value.',
        ru: 'В некоторых изданиях короткую последовательность пустых тактов показывают сочетанием знаков пауз лонги, бревиса и целой. Другой способ — современная многотактовая пауза с числом. Учитывайте количество тактов и правила издания; не принимайте сочетание знаков за одну обычную длительность паузы.',
        de: 'Manche Ausgaben kombinieren Longa-, Brevis- und Ganzpausenzeichen für wenige pausierende Takte. Eine waagerechte Mehrtaktpause mit Zahl ist eine andere Darstellung. Lies die Taktzahl und die Konvention der Ausgabe; verwechsle die kombinierten Zeichen nicht mit einem einzelnen gewöhnlichen Pausenwert.',
      },
      forwardModules: ['N04'],
      sourceId: 'source-021',
    },
    {
      id: 'Note value',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 94,
      reference: false,
      title: {
        en: 'Note value',
        ru: 'Длительность',
        de: 'Notenwert',
      },
      body: {
        en: 'The written length of a note, given in relation to the other values rather than in seconds.',
        ru: 'Записанная протяжённость ноты, заданная по отношению к другим длительностям, а не в секундах.',
        de: 'Die geschriebene Dauer einer Note, die im Verhältnis zu den anderen Werten steht und nicht in Sekunden.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Whole note',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 95,
      reference: false,
      title: {
        en: 'Whole note',
        ru: 'Целая нота',
        de: 'Ganze Note',
      },
      body: {
        en: 'A note value equal to two half notes or four quarter notes. It is drawn with an open head and no stem. Longer values, such as the breve, also exist; a whole note is not always a whole bar.',
        ru: 'Длительность, равная двум половинным или четырём четвертям. Записывается незакрашенной головкой без штиля. Существуют и более долгие значения, например бревис; целая нота не всегда занимает ровно такт.',
        de: 'Ein Notenwert von zwei Halben oder vier Vierteln, mit offenem Kopf ohne Hals. Längere Werte wie die Brevis gibt es ebenfalls; eine ganze Note füllt nicht in jeder Taktart einen ganzen Takt.',
      },
      sourceId: 'source-018',
    },
    {
      id: 'Rest',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 96,
      reference: false,
      title: {
        en: 'Rest',
        ru: 'Пауза',
        de: 'Pause',
      },
      body: {
        en: 'A sign for silence that lasts a stated note value.',
        ru: 'Знак молчания, длящегося указанную длительность.',
        de: 'Ein Zeichen für Schweigen von einem bestimmten Notenwert.',
      },
      sourceId: 'source-019',
    },
    {
      id: 'Whole-bar rest',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 97,
      reference: false,
      title: {
        en: 'Whole-bar rest',
        ru: 'Тактовая пауза',
        de: 'Taktpause',
      },
      body: {
        en: 'The whole rest used for a silent bar, whatever the length of that bar.',
        ru: 'Целая пауза, обозначающая молчание всего такта независимо от его размера.',
        de: 'Die ganze Pause für einen schweigenden Takt, gleich wie lang dieser Takt ist.',
      },
      sourceId: 'source-019',
    },
    {
      id: 'Flag',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'durations',
      order: 98,
      reference: false,
      title: {
        en: 'Flag',
        ru: 'Флажок',
        de: 'Fähnchen',
      },
      body: {
        en: 'A hook on the stem; each flag halves the note value again.',
        ru: 'Крючок у штиля; каждый флажок снова делит длительность пополам.',
        de: 'Ein Haken am Notenhals; jedes Fähnchen halbiert den Wert erneut.',
      },
      sourceId: 'source-018',
    },
  ],
};
export default content;
