import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'dynamics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['sound', 'tempo', 'chords'],
    locales: ['en', 'ru', 'de'],
    kind: 'concept',
    module: 'N02',
    roadmapIds: ['124'],
    lessonIds: ['dynamics'],
    experimentIds: ['dynamics'],
    exerciseIds: ['relative-dynamic-level'],
    conceptIds: [
      'Character and emphasis',
      'Fortepiano (fp)',
      'Character: line and expression',
      'Character: motion and weight',
      'Subsiding directions',
      'Mancando: historical vocabulary',
      'piano (p)',
      'forte (f)',
      'mezzo (mp, mf)',
      'crescendo',
      'decrescendo',
      'hairpin',
      'sforzato (sf, sfz)',
      'accent',
    ],
  },
  lesson: {
    id: 'dynamics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'dynamics',
    title: {
      en: 'Loudness without a number',
      ru: 'Громкость без числа',
      de: 'Lautstärke ohne Zahl',
    },
    category: {
      en: 'Performance',
      ru: 'Исполнение',
      de: 'Vortrag',
    },
    summary: {
      en: 'Distinguish dynamic levels, gradual changes and accents.',
      ru: 'Различайте уровни динамики, постепенные изменения и акценты.',
      de: 'Unterscheide dynamische Grade, allmähliche Änderungen und Akzente.',
    },
    formula: {
      en: 'pp < p < mp < mf < f < ff',
      ru: 'pp < p < mp < mf < f < ff',
      de: 'pp < p < mp < mf < f < ff',
    },
    paragraphs: [
      {
        en: 'Dynamic marks guide the strength of the sound: p (piano) means soft, f (forte) loud, mp (mezzo piano) moderately soft and mf (mezzo forte) moderately loud. They establish a level within the musical context; p at the start of a piece does not require an earlier loud passage. They specify no fixed decibel value. Instrument, room and ensemble balance affect how a mark is realized.',
        ru: 'Динамические обозначения указывают силу звучания: p (пиано) — тихо, f (форте) — громко, mp (меццо-пиано) — умеренно тихо, mf (меццо-форте) — умеренно громко. Они задают уровень в музыкальном контексте: пиано в начале пьесы не требует предшествующего громкого участка. Фиксированного значения в децибелах у этих знаков нет. Исполнение зависит от инструмента, помещения и баланса ансамбля.',
        de: 'Dynamikzeichen geben die Klangstärke an: p (piano) heißt leise, f (forte) laut, mp (mezzopiano) mäßig leise und mf (mezzoforte) mäßig laut. Sie bestimmen einen Grad im musikalischen Zusammenhang; ein p am Stückanfang setzt keine vorherige laute Stelle voraus. Einen festen Dezibelwert geben sie nicht an. Instrument, Raum und Ensemblebalance beeinflussen die Ausführung.',
      },
      {
        en: 'Crescendo increases the level and decrescendo decreases it over the indicated span. An accent or sforzato emphasizes an event relative to the surrounding dynamic level; it does not prescribe a fixed sound pressure.',
        ru: 'Крещендо усиливает звучание, диминуэндо ослабляет его на указанном участке. Акцент или сфорцато выделяет событие относительно окружающей динамики, не задавая фиксированного звукового давления.',
        de: 'Crescendo steigert, Decrescendo verringert die Lautstärke auf der angegebenen Strecke. Akzent oder Sforzato betont ein Ereignis im Verhältnis zur umgebenden Dynamik und legt keinen festen Schalldruck fest.',
      },
    ],
    sourceId: 'source-054',
    experimentId: 'dynamics',
    reading: {
      pages: '26–28',
      sourceId: 'source-012',
      text: {
        en: 'Separate a sustained level from an accent: fp asks for a strong onset followed by a soft continuation; sfz emphasizes an event. A crescendo hairpin governs its drawn span, not an endless increase. pppp and ffff extend the relative ladder. Calando or morendo can combine changes of motion and intensity; interpret them with the phrase and edition.',
        ru: 'Отличайте постоянный уровень от акцента: fp требует громкого начала с тихим продолжением; sfz выделяет отдельное событие. Вилка крещендо относится к указанному участку, а не к бесконечному усилению. pppp и ffff расширяют относительную шкалу. Calando или morendo могут объединять изменения движения и силы звучания; учитывайте фразу и редакцию.',
        de: 'Unterscheide einen anhaltenden Grad von einer Betonung: fp verlangt einen kräftigen Beginn mit leiser Fortsetzung; sfz hebt ein Ereignis hervor. Eine Crescendogabel gilt für ihre gezeichnete Strecke, nicht für endloses Lauterwerden. pppp und ffff erweitern die relative Skala. Calando oder morendo können Bewegung und Intensität zugleich verändern; beachte Phrase und Ausgabe.',
      },
      assetIds: ['figure-dynamic-hairpin', 'figure-dynamic-fp'],
    },
  },
  experiment: {
    id: 'dynamics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'dynamics',
    instructions: {
      en: 'At a comfortable listening volume, compare the Softer and Louder examples. They play the same pitch at different levels: the lab illustrates a contrast, while the musical meaning of p and f depends on context.',
      ru: 'На комфортной громкости сравните примеры «Тише» и «Громче». Они воспроизводят один звук с разной громкостью: лаборатория показывает контраст, а музыкальный смысл пиано и форте зависит от контекста.',
      de: 'Vergleiche bei angenehmer Hörlautstärke die Beispiele „Leiser“ und „Lauter“. Sie spielen denselben Ton mit unterschiedlicher Lautstärke. Das Labor veranschaulicht den Kontrast; die musikalische Bedeutung von p und f hängt vom Zusammenhang ab.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 440,
      wave: 'sine',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'dynamics',
    },
  },
  exercises: [
    {
      id: 'relative-dynamic-level',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      label: {
        en: 'Compare dynamic levels',
        ru: 'Сравнение уровней динамики',
        de: 'Dynamische Grade vergleichen',
      },
      generator: 'performance-marks',
      sourceIds: ['source-012'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Character and emphasis',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 3,
      reference: true,
      title: {
        en: 'Character and emphasis',
        ru: 'Характер и подчёркивание',
        de: 'Charakter und Betonung',
      },
      body: {
        en: 'Dolce asks for sweetness; espressivo for expression. Rinforzando (rinf., rfz) requests emphasis. Calando suggests subsiding; morendo dying away. Follow the phrase and edition when translating these directions into timing and intensity.',
        ru: 'Dolce — нежно; espressivo — выразительно. Rinforzando (rinf., rfz) требует подчёркивания. Calando — затихая; morendo — замирая. Изменения времени и силы звучания уточняйте по фразе и редакции.',
        de: 'Dolce verlangt Lieblichkeit, espressivo Ausdruck. Rinforzando (rinf., rfz) fordert Betonung. Calando bedeutet nachlassend, morendo ersterbend. Übertrage diese Angaben im Zusammenhang mit Phrase und Ausgabe auf Zeitmaß und Intensität.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Fortepiano (fp)',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 21,
      reference: true,
      title: {
        en: 'Fortepiano (fp)',
        ru: 'Фортепиано (fp)',
        de: 'Fortepiano (fp)',
      },
      body: {
        en: 'A strong attack followed immediately by a soft continuation; it is not the instrument name in this context.',
        ru: 'Сильное начало звука с немедленным тихим продолжением; здесь это исполнительское указание, а не название инструмента.',
        de: 'Kräftiger Beginn mit unmittelbar leiser Fortsetzung; hier eine Vortragsangabe, nicht der Instrumentenname.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'Character: line and expression',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 33,
      reference: true,
      title: {
        en: 'Character: line and expression',
        ru: 'Характер: линия и выражение',
        de: 'Charakter: Linie und Ausdruck',
      },
      aliases: {
        en: 'cantabile; dolce; espressivo; affettuoso; amabile; con anima; con dolore; dolente; sotto voce',
        ru: 'кантабиле; дольче; эспрессиво; аффеттуозо; амабиле; с душой; с болью; жалобно; вполголоса',
        de: 'cantabile; dolce; espressivo; affettuoso; amabile; con anima; con dolore; dolente; sotto voce',
      },
      body: {
        en: 'Cantabile asks for a singing line; dolce and amabile for gentleness; espressivo for expressive shaping. Affettuoso suggests warmth of feeling, con anima animation of expression, con dolore/dolente sorrow. Sotto voce restrains the delivery. These directions concern the manner of the phrase; they cannot be reduced to one gain or tempo setting.',
        ru: 'Cantabile требует певучей линии, dolce и amabile — мягкости, espressivo — выразительной формы. Affettuoso передаёт теплоту чувства, con anima — одушевлённость, con dolore/dolente — скорбь. Sotto voce сдерживает подачу звука. Эти указания относятся к ведению фразы и не сводятся к одной настройке громкости или темпа.',
        de: 'Cantabile verlangt eine singende Linie, dolce und amabile Sanftheit, espressivo ausdrucksvolle Gestaltung. Affettuoso legt gefühlsvolle Wärme nahe, con anima Beseeltheit, con dolore/dolente Schmerz. Sotto voce nimmt den Vortrag zurück. Diese Angaben betreffen die Gestaltung der Phrase, nicht einen einzigen Lautstärke- oder Temporegler.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-032'],
    },
    {
      id: 'Character: motion and weight',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 34,
      reference: true,
      title: {
        en: 'Character: motion and weight',
        ru: 'Характер: движение и вес',
        de: 'Charakter: Bewegung und Gewicht',
      },
      aliases: {
        en: 'agitato; animato; brillante; con brio; furioso; tempestoso; tumultuoso; maestoso; marciale; grave; serioso; giusto; grazioso; giocoso; scherzando; piacevole; secco',
        ru: 'ажитато; анимато; брилланте; кон брио; фуриозо; маэстозо; марциально; граве; сериозо; грациозо; джокозо; скерцандо; сухо',
        de: 'agitato; animato; brillante; con brio; furioso; tempestoso; tumultuoso; maestoso; marciale; grave; serioso; giusto; grazioso; giocoso; scherzando; piacevole; secco',
      },
      body: {
        en: 'Agitato is unsettled, animato animated, brillante brilliant, con brio energetic. Furioso, tempestoso and tumultuoso suggest turbulent intensity. Maestoso gives dignity, marciale a march character, grave/serioso seriousness, giusto an appropriate or regular manner. Grazioso is graceful, giocoso/scherzando playful, piacevole pleasant, secco dry. Compare the character words with the actual dynamics and articulation rather than treating them as synonyms for “fast” or “loud”.',
        ru: 'Agitato — взволнованно, animato — оживлённо, brillante — блестяще, con brio — энергично. Furioso, tempestoso и tumultuoso передают бурную напряжённость. Maestoso придаёт величавость, marciale — маршевость, grave/serioso — серьёзность, giusto — уместную или ровную манеру. Grazioso — грациозно, giocoso/scherzando — игриво, piacevole — приятно, secco — сухо. Сопоставляйте характер с выписанной динамикой и артикуляцией, не заменяя все слова указаниями «быстро» или «громко».',
        de: 'Agitato wirkt erregt, animato belebt, brillante glänzend, con brio schwungvoll. Furioso, tempestoso und tumultuoso legen stürmische Intensität nahe. Maestoso gibt Würde, marciale Marschcharakter, grave/serioso Ernst, giusto ein angemessenes oder regelmäßiges Maß. Grazioso ist anmutig, giocoso/scherzando spielerisch, piacevole angenehm, secco trocken. Vergleiche den Charakter mit Dynamik und Artikulation statt alles mit „schnell“ oder „laut“ gleichzusetzen.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-032', 'source-034'],
    },
    {
      id: 'Subsiding directions',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 35,
      reference: true,
      title: {
        en: 'Subsiding directions',
        ru: 'Указания на угасание',
        de: 'Nachlassender Vortrag',
      },
      aliases: {
        en: 'calando; morendo; perdendosi; smorzando',
        ru: 'каландо; морендо; пердендоси; сморцандо',
        de: 'calando; morendo; perdendosi; smorzando',
      },
      body: {
        en: 'Calando asks the passage to subside; morendo suggests dying away, perdendosi losing itself, smorzando fading out. The phrase may need both less motion and less intensity. Do not automatically assign every word the same ritardando or volume curve: the printed dynamics, tempo and edition establish the context.',
        ru: 'Calando предлагает успокоить и ослабить движение; morendo — замирая, perdendosi — теряясь, smorzando — угасая. Фразе могут понадобиться и меньшая подвижность, и меньшая сила. Не назначайте каждому слову одинаковое замедление или кривую громкости: контекст задают выписанные темп, динамика и редакция.',
        de: 'Calando lässt die Passage nachlassen; morendo bedeutet ersterbend, perdendosi sich verlierend, smorzando verlöschend. Die Phrase kann weniger Bewegung und weniger Intensität verlangen. Ordne nicht jedem Wort dieselbe Verzögerung oder Lautstärkekurve zu: gedruckte Dynamik, Tempo und Ausgabe bestimmen den Zusammenhang.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-013', 'source-032'],
    },
    {
      id: 'Mancando: historical vocabulary',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 36,
      reference: true,
      title: {
        en: 'Mancando: historical vocabulary',
        ru: 'Mancando: историческое указание',
        de: 'Mancando: historischer Wortgebrauch',
      },
      aliases: {
        en: 'mancando',
        ru: 'манкандо; ослабевая',
        de: 'mancando',
      },
      body: {
        en: 'Mancando asks the sound to lose strength. Dolmetsch’s dictionary describes fading, while its tempo table includes slowing as well as softening, as does Wolf’s 1985 account. These descriptions guide interpretation; they do not prescribe a numerical tempo or gain curve. Decide how the passage subsides from its phrase, instrument and edition.',
        ru: 'Mancando — ослабевая. Словарь Dolmetsch описывает угасание, а таблица темпов того же издания включает замедление вместе с ослаблением звучности, как и изложение Вольфа 1985 года. Эти толкования направляют исполнение, но не задают числовой кривой темпа или громкости. Характер угасания определяют фраза, инструмент и редакция.',
        de: 'Mancando verlangt ein Nachlassen der Klangstärke. Das Dolmetsch-Wörterbuch beschreibt ein Verlöschen; seine Tempotabelle nennt zusätzlich eine Verlangsamung, ebenso wie Wolfs Darstellung von 1985. Daraus folgt keine feste Tempo- oder Lautstärkekurve. Phrase, Instrument und Ausgabe bestimmen, wie die Passage nachlässt.',
      },
      sourceId: 'source-033',
      furtherSourceIds: ['source-013', 'source-042'],
    },
    {
      id: 'piano (p)',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 119,
      reference: false,
      title: {
        en: 'Piano (p)',
        ru: 'Пиано (p)',
        de: 'Piano (p)',
      },
      body: {
        en: 'The mark p asks for a soft level relative to the passages around it.',
        ru: 'Знак p требует тихого звучания относительно соседних участков.',
        de: 'Das Zeichen p verlangt eine im Verhältnis zur Umgebung leise Stufe.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'forte (f)',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 120,
      reference: false,
      title: {
        en: 'Forte (f)',
        ru: 'Форте (f)',
        de: 'Forte (f)',
      },
      body: {
        en: 'The mark f asks for a loud level relative to the passages around it.',
        ru: 'Знак f требует громкого звучания относительно соседних участков.',
        de: 'Das Zeichen f verlangt eine im Verhältnis zur Umgebung laute Stufe.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'mezzo (mp, mf)',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 121,
      reference: false,
      title: {
        en: 'Mezzo (mp, mf)',
        ru: 'Меццо (mp, mf)',
        de: 'Mezzo (mp, mf)',
      },
      body: {
        en: 'Mezzo means “half” or “moderately”: mp asks for moderately soft playing and mf for moderately loud. These are relative dynamic levels, not an instruction to halve amplitude or perceived loudness.',
        ru: 'Mezzo означает «наполовину» или «умеренно»: mp — умеренно тихо, mf — умеренно громко. Это относительные уровни динамики, а не указание вдвое уменьшить амплитуду или воспринимаемую громкость.',
        de: 'Mezzo bedeutet „halb“ oder „mäßig“: mp verlangt mäßig leises, mf mäßig lautes Spiel. Gemeint sind relative dynamische Grade, keine Halbierung der Amplitude oder der wahrgenommenen Lautstärke.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'crescendo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 122,
      reference: false,
      title: {
        en: 'Crescendo',
        ru: 'Крещендо',
        de: 'Crescendo',
      },
      body: {
        en: 'A crescendo asks for a gradual increase in loudness across the passage it covers.',
        ru: 'Крещендо — постепенное усиление звучности на протяжении отмеченного отрезка.',
        de: 'Ein Crescendo verlangt eine allmähliche Zunahme der Lautstärke über die bezeichnete Strecke.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'decrescendo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 123,
      reference: false,
      title: {
        en: 'Decrescendo',
        ru: 'Диминуэндо',
        de: 'Decrescendo',
      },
      body: {
        en: 'A decrescendo, also written diminuendo, asks for a gradual decrease in loudness.',
        ru: 'Диминуэндо, оно же декрещендо, — постепенное ослабление звучности.',
        de: 'Ein Decrescendo, auch Diminuendo geschrieben, verlangt eine allmähliche Abnahme der Lautstärke.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'hairpin',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 124,
      reference: false,
      title: {
        en: 'Hairpin',
        ru: 'Вилка',
        de: 'Gabel',
      },
      body: {
        en: 'A hairpin is the pair of converging lines that draws a crescendo or decrescendo over the staff.',
        ru: 'Вилка — пара сходящихся линий, обозначающая крещендо или диминуэндо у нотоносца.',
        de: 'Eine Gabel ist das Linienpaar, das ein Crescendo oder Decrescendo am Notensystem darstellt.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'sforzato (sf, sfz)',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 125,
      reference: false,
      title: {
        en: 'Sforzato (sf, sfz)',
        ru: 'Сфорцато (sf, sfz)',
        de: 'Sforzato (sf, sfz)',
      },
      body: {
        en: 'Sforzato marks a single note as suddenly stronger than the level in force.',
        ru: 'Сфорцато отмечает отдельный звук как внезапно более сильный, чем установленный уровень.',
        de: 'Sforzato kennzeichnet einen einzelnen Ton als plötzlich stärker als die geltende Stufe.',
      },
      sourceId: 'source-012',
    },
    {
      id: 'accent',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'dynamics',
      order: 126,
      reference: false,
      title: {
        en: 'Accent',
        ru: 'Акцент',
        de: 'Akzent',
      },
      body: {
        en: 'An accent sign asks for a single note to be given more weight than its neighbours.',
        ru: 'Знак акцента требует выделить один звук сильнее соседних.',
        de: 'Ein Akzentzeichen verlangt, einen einzelnen Ton stärker zu gewichten als seine Nachbarn.',
      },
      sourceId: 'source-012',
    },
  ],
};
export default content;
