import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'enharmonics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['note-names'],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F03',
    roadmapIds: ['014'],
    lessonIds: ['enharmonics'],
    experimentIds: ['enharmonics'],
    exerciseIds: ['enharmonic-respelling'],
    conceptIds: [
      'Enharmonic spelling',
      'Letter name',
      'Scale degree',
      'Raised degree',
      'Lowered degree',
      'Chromatic semitone',
      'Diatonic semitone',
    ],
  },
  lesson: {
    id: 'enharmonics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'enharmonics',
    title: {
      en: 'Two spellings, one sound',
      ru: 'Две записи, один звук',
      de: 'Zwei Schreibweisen, ein Klang',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Tell enharmonic spellings apart and know why the spelling matters.',
      ru: 'Различайте энгармонические записи и понимайте, зачем нужна каждая.',
      de: 'Enharmonische Schreibweisen unterscheiden und ihren Sinn verstehen.',
    },
    formula: {
      en: 'C♯ = D♭ · F♯ = G♭ · E = F♭ · in equal temperament',
      ru: 'до-диез = ре-бемоль · фа-диез = соль-бемоль · ми = фа-бемоль · в равномерном строе',
      de: 'Cis = Des · Fis = Ges · E = Fes · in gleichstufiger Stimmung',
      ruMarkup:
        '[[до-диез]] = [[ре-бемоль]] · [[фа-диез]] = [[соль-бемоль]] · [[ми]] = [[фа-бемоль]] · в равномерном строе',
    },
    paragraphs: [
      {
        en: 'In twelve-tone equal temperament one pitch can be written in more than one way. C sharp and D flat sound the same; so do F sharp and G flat, and E and F flat. Each spelling names a different letter, and the letter decides which scale degree the note occupies.',
        ru: 'В двенадцатиступенном равномерном строе один и тот же звук можно записать по-разному. До-диез и ре-бемоль звучат одинаково; так же соотносятся фа-диез и соль-бемоль, ми и фа-бемоль. Каждая запись называет свою ступень, и именно ступень определяет место ноты в звукоряде.',
        de: 'In der zwölfstufigen gleichstufigen Stimmung lässt sich derselbe Klang unterschiedlich schreiben. Cis und Des klingen gleich, ebenso Fis und Ges oder E und Fes. Jede Schreibweise nennt einen anderen Stammton, und der Stammton bestimmt, welche Stufe der Ton in der Tonleiter einnimmt.',
        ruMarkup:
          'В двенадцатиступенном равномерном строе один и тот же звук можно записать по-разному. [[До-диез]] и [[ре-бемоль]] звучат одинаково; так же соотносятся [[фа-диез]] и [[соль-бемоль]], [[ми]] и [[фа-бемоль]]. Каждая запись называет свою ступень, и именно ступень определяет место ноты в звукоряде.',
      },
      {
        en: 'Spelling identifies the written interval and its harmonic context. C–D sharp is an augmented second; C–E flat is a minor third. A sharp or flat alone does not determine the direction of the next note.',
        ru: 'Запись определяет название интервала и проясняет гармонический контекст. До — ре-диез — увеличенная секунда, до — ми-бемоль — малая терция. Диез или бемоль сами по себе не определяют направление следующей ноты.',
        de: 'Die Schreibweise bezeichnet das notierte Intervall und verdeutlicht den harmonischen Zusammenhang. C–Dis ist eine übermäßige Sekunde, C–Es eine kleine Terz. Ein Kreuz oder Be allein bestimmt nicht die Richtung des nächsten Tons.',
        ruMarkup:
          'Запись определяет название интервала и проясняет гармонический контекст. [[До]] — [[ре-диез]] — увеличенная секунда, [[до]] — [[ми-бемоль]] — малая терция. Диез или бемоль сами по себе не определяют направление следующей ноты.',
      },
    ],
    sourceId: 'source-049',
    experimentId: 'enharmonics',
    reading: {
      pages: '10',
      sourceId: 'source-001',
      text: {
        en: 'A sounding key alone cannot select a spelling. In 12-TET, C–D♯ is an augmented second, while C–E♭ is a minor third. The letters and harmonic context decide the written interval. Neither a sharp nor a flat universally dictates the direction of the next note.',
        ru: 'По одной звучащей клавише нельзя выбрать запись. В равномерном строе до — ре-диез образуют увеличенную секунду, а до — ми-бемоль — малую терцию. Записанный интервал определяется ступенями и гармоническим контекстом. Диез или бемоль сами по себе не предписывают направление следующей ноты.',
        de: 'Die klingende Taste allein bestimmt die Schreibweise nicht. In gleichstufiger Stimmung ist C–Dis eine übermäßige Sekunde, C–Es eine kleine Terz. Buchstaben und harmonischer Zusammenhang bestimmen das notierte Intervall. Ein Kreuz oder Be schreibt nicht allgemein die Richtung des folgenden Tons vor.',
        ruMarkup:
          'По одной звучащей клавише нельзя выбрать запись. В равномерном строе [[до]] — [[ре-диез]] образуют увеличенную секунду, а [[до]] — [[ми-бемоль]] — малую терцию. Записанный интервал определяется ступенями и гармоническим контекстом. Диез или бемоль сами по себе не предписывают направление следующей ноты.',
      },
      assetIds: [],
    },
  },
  experiment: {
    id: 'enharmonics',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'enharmonics',
    instructions: {
      en: 'Set the lab to F♯4, then look for G♭4, and notice that both names point at one frequency.',
      ru: 'Установите фа-диез первой октавы, затем найдите соль-бемоль и убедитесь, что оба названия указывают на одну частоту.',
      de: 'Stelle fis′ ein, suche danach ges′ und stelle fest, dass beide Namen auf dieselbe Frequenz führen.',
      ruMarkup:
        'Установите [[фа-диез]] первой октавы, затем найдите [[соль-бемоль]] и убедитесь, что оба названия указывают на одну частоту.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 369.994423,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 3,
        accidental: 1,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'enharmonic-respelling',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      label: {
        en: 'Respell the same pitch',
        ru: 'Энгармоническая замена',
        de: 'Enharmonisch umschreiben',
      },
      generator: 'enharmonic',
      sourceIds: ['source-001'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Enharmonic spelling',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 87,
      reference: false,
      title: {
        en: 'Enharmonic spelling',
        ru: 'Энгармоническая запись',
        de: 'Enharmonische Verwechslung',
      },
      body: {
        en: 'Two different written notes that sound as one pitch in equal temperament.',
        ru: 'Две разные записи, дающие в равномерном строе одну и ту же высоту.',
        de: 'Zwei verschiedene Schreibweisen, die in gleichstufiger Stimmung denselben Klang ergeben.',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Letter name',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 88,
      reference: false,
      title: {
        en: 'Letter name',
        ru: 'Название основной ступени',
        de: 'Stammtonname',
      },
      body: {
        en: 'The plain name of a note before any accidental is added.',
        ru: 'Основное название ноты до прибавления знака альтерации.',
        de: 'Der unveränderte Tonname vor jedem Versetzungszeichen.',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Scale degree',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 89,
      reference: false,
      title: {
        en: 'Scale degree',
        ru: 'Ступень звукоряда',
        de: 'Tonleiterstufe',
      },
      body: {
        en: 'The numbered position a note occupies in its scale.',
        ru: 'Порядковое место, которое нота занимает в своём звукоряде.',
        de: 'Die nummerierte Position, die ein Ton in seiner Tonleiter einnimmt.',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Raised degree',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 90,
      reference: false,
      title: {
        en: 'Raised degree',
        ru: 'Повышенная ступень',
        de: 'Erhöhte Stufe',
      },
      body: {
        en: 'A degree raised relative to the scale being discussed, usually by a semitone: G becomes G♯ when the seventh degree of A natural minor is raised.',
        ru: 'Ступень, повышенная относительно рассматриваемой гаммы, обычно на полутон: при повышении VII ступени ля натурального минора соль превращается в соль-диез.',
        de: 'Eine gegenüber der betrachteten Tonleiter erhöhte Stufe, meist um einen Halbton: Wird die siebte Stufe der natürlichen a-Moll-Tonleiter erhöht, wird G zu Gis.',
        ruMarkup:
          'Ступень, повышенная относительно рассматриваемой гаммы, обычно на полутон: при повышении VII ступени [[ля]] натурального минора [[соль]] превращается в [[соль-диез]].',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Lowered degree',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 91,
      reference: false,
      title: {
        en: 'Lowered degree',
        ru: 'Пониженная ступень',
        de: 'Erniedrigte Stufe',
      },
      body: {
        en: 'A degree lowered relative to the scale being discussed, usually by a semitone: lowering the third degree of C major changes E to E♭.',
        ru: 'Ступень, пониженная относительно рассматриваемой гаммы, обычно на полутон: при понижении III ступени до мажора ми превращается в ми-бемоль.',
        de: 'Eine gegenüber der betrachteten Tonleiter erniedrigte Stufe, meist um einen Halbton: Wird die dritte Stufe von C-Dur erniedrigt, wird E zu Es.',
        ruMarkup:
          'Ступень, пониженная относительно рассматриваемой гаммы, обычно на полутон: при понижении III ступени [[до]] мажора [[ми]] превращается в [[ми-бемоль]].',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Chromatic semitone',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 92,
      reference: false,
      title: {
        en: 'Chromatic semitone',
        ru: 'Хроматический полутон',
        de: 'Chromatischer Halbton',
      },
      body: {
        en: 'A semitone between two notes that share a letter, such as C and C sharp.',
        ru: 'Полутон между двумя нотами одной ступени, например до и до-диез.',
        de: 'Ein Halbton zwischen zwei Tönen desselben Stammtons, etwa C und Cis.',
        ruMarkup:
          'Полутон между двумя нотами одной ступени, например [[до]] и [[до-диез]].',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Diatonic semitone',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'enharmonics',
      order: 93,
      reference: false,
      title: {
        en: 'Diatonic semitone',
        ru: 'Диатонический полутон',
        de: 'Diatonischer Halbton',
      },
      body: {
        en: 'A semitone between two neighbouring letters, such as C sharp and D.',
        ru: 'Полутон между двумя соседними ступенями, например до-диез и ре.',
        de: 'Ein Halbton zwischen zwei benachbarten Stammtönen, etwa Cis und D.',
        ruMarkup:
          'Полутон между двумя соседними ступенями, например [[до-диез]] и [[ре]].',
      },
      sourceId: 'source-001',
    },
  ],
};
export default content;
