import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'note-names',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F01',
    roadmapIds: ['003'],
    lessonIds: ['note-names'],
    experimentIds: ['note-names'],
    exerciseIds: ['register-1', 'register-2', 'register-3', 'natural-name'],
    conceptIds: [
      'Pitch-name systems',
      'Natural note',
      'Note name',
      'Octave register',
      'Octave notation',
      'Middle C',
    ],
  },
  lesson: {
    id: 'note-names',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'note-names',
    title: {
      en: 'Note names and octaves',
      ru: 'Названия нот и октавы',
      de: 'Tonnamen und Oktavlagen',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Name any natural note and say which octave it sits in.',
      ru: 'Называйте любую основную ступень и определяйте её октаву.',
      de: 'Benenne jeden Stammton und bestimme seine Oktavlage.',
    },
    formula: {
      en: 'C D E F G A B · C4 … B4 · C5',
      ru: 'до ре ми фа соль ля си · первая октава: до … си · далее вторая',
      de: 'C D E F G A H · c′ … h′ · c″',
      ruMarkup:
        '[[до]] [[ре]] [[ми]] [[фа]] [[соль]] [[ля]] [[си]] · первая октава: [[до]] … [[си]] · далее вторая',
    },
    paragraphs: [
      {
        en: 'Seven names carry the natural notes: C, D, E, F, G, A and B. After B the series starts again at C, and the frequency of that C is twice the frequency of the C below it. That repeating distance is the octave.',
        ru: 'Основных ступеней семь: до, ре, ми, фа, соль, ля, си. После си ряд начинается заново с до, и частота этого до вдвое больше, чем у предыдущего. Расстояние до повторения названия называется октавой.',
        de: 'Sieben Namen tragen die Stammtöne: C, D, E, F, G, A und H. Nach dem H beginnt die Reihe wieder bei C, und dieses C schwingt doppelt so schnell wie das C darunter. Dieser wiederkehrende Abstand heißt Oktave.',
        ruMarkup:
          'Основных ступеней семь: [[до]], [[ре]], [[ми]], [[фа]], [[соль]], [[ля]], [[си]]. После [[си]] ряд начинается заново с [[до]], и частота этого [[до]] вдвое больше, чем у предыдущего. Расстояние до повторения названия называется октавой.',
      },
      {
        en: 'A name alone does not fix a pitch, because every octave repeats it. Scientific pitch notation adds a number: middle C is C4, and the number rises at each C, so B4 lies just below C5. The reference pitch of this lab is A4 at 440 Hz.',
        ru: 'Одно название не задаёт высоту: оно повторяется в каждой октаве, поэтому называют и октаву. Русские названия идут снизу вверх: субконтроктава, контроктава, большая, малая, первая, вторая, третья, четвёртая, пятая. Каждая октава начинается с до, и си первой октавы лежит непосредственно под до второй. Опорный тон лаборатории — ля первой октавы, 440 Гц.',
        de: 'Ein Name allein legt noch keine Tonhöhe fest, denn jede Oktave wiederholt ihn. Die Helmholtz-Bezeichnung ergänzt deshalb die Lage: große Oktave C bis H, kleine Oktave c bis h, eingestrichene Oktave c′ bis h′, zweigestrichene Oktave c″ bis h″. Jede Oktave beginnt bei ihrem C, das h′ liegt also unmittelbar unter dem c″. Der Kammerton dieses Labors ist a′ mit 440 Hz.',
        ruMarkup:
          'Одно название не задаёт высоту: оно повторяется в каждой октаве, поэтому называют и октаву. Русские названия идут снизу вверх: субконтроктава, контроктава, большая, малая, первая, вторая, третья, четвёртая, пятая. Каждая октава начинается с [[до]], и [[си]] первой октавы лежит непосредственно под [[до]] второй. Опорный тон лаборатории — [[ля]] первой октавы, 440 Гц.',
      },
    ],
    sourceId: 'source-039',
    experimentId: 'note-names',
    reading: {
      pages: '2–3',
      sourceId: 'source-001',
      text: {
        en: 'Read octave names at the written C boundary. In English, B♯3 and C4 may sound alike in 12-TET but keep different written octave numbers. The standard 88-key piano extends from A0 to C8; an instrument’s compass is not a universal limit of music.',
        ru: 'Границу записанной октавы проводят по до. Си-диез малой октавы и до первой могут совпадать по высоте в равномерном строе, сохраняя разные обозначения октав. Диапазон обычного 88-клавишного фортепиано: от ля субконтроктавы до до пятой октавы; это не универсальные границы музыки.',
        de: 'Die geschriebene Oktave beginnt jeweils bei c. his und c′ können in gleichstufiger Stimmung gleich klingen, behalten aber verschiedene Oktavbezeichnungen. H bezeichnet den Stammton, B dessen Erniedrigung. Der übliche Flügel mit 88 Tasten reicht von A₂ bis c⁵; sein Tonumfang ist keine allgemeine Grenze der Musik.',
        ruMarkup:
          'Границу записанной октавы проводят по [[до]]. [[Си-диез]] малой октавы и [[до]] первой могут совпадать по высоте в равномерном строе, сохраняя разные обозначения октав. Диапазон обычного 88-клавишного фортепиано: от [[ля]] субконтроктавы до [[до]] пятой октавы; это не универсальные границы музыки.',
      },
      assetIds: [],
    },
  },
  experiment: {
    id: 'note-names',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'note-names',
    instructions: {
      en: 'In Notes, select C in octave 4. Use the note buttons up to B, then select C in octave 5. Play and name each note.',
      ru: 'Во вкладке «Ноты» выберите до первой октавы. Пройдите кнопками ступеней до си, затем выберите до второй октавы. Проигрывайте и называйте каждую ноту.',
      de: 'Wähle unter Noten das c′. Gehe mit den Tonknöpfen bis h′ und wähle dann c″. Spiele und benenne jeden Ton.',
      ruMarkup:
        'Во вкладке «Ноты» выберите [[до]] первой октавы. Пройдите кнопками ступеней до [[си]], затем выберите [[до]] второй октавы. Проигрывайте и называйте каждую ноту.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 261.625565,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'register-1',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      label: {
        en: 'Move by one octave',
        ru: 'Перенос на одну октаву',
        de: 'Um eine Oktave versetzen',
      },
      generator: 'octave-region',
      sourceIds: ['source-001'],
      kind: 'generated',
    },
    {
      id: 'register-2',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      label: {
        en: 'Move by two octaves',
        ru: 'Перенос на две октавы',
        de: 'Um zwei Oktaven versetzen',
      },
      generator: 'octave-region',
      sourceIds: ['source-001'],
      kind: 'generated',
    },
    {
      id: 'register-3',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      label: {
        en: 'Move by three octaves',
        ru: 'Перенос на три октавы',
        de: 'Um drei Oktaven versetzen',
      },
      generator: 'octave-region',
      sourceIds: ['source-001'],
      kind: 'generated',
    },
    {
      id: 'natural-name',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      label: {
        en: 'Name a natural note',
        ru: 'Название основной ступени',
        de: 'Einen Stammton benennen',
      },
      generator: 'accidental-name',
      sourceIds: ['source-001'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Pitch-name systems',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 43,
      reference: true,
      title: {
        en: 'Pitch-name systems',
        ru: 'Системы названий нот',
        de: 'Systeme der Tonbenennung',
      },
      aliases: {
        en: 'German H; German B; scientific pitch; Helmholtz',
        ru: 'немецкая H; немецкая B; система Гельмгольца; научная нотация',
        de: 'H und B; wissenschaftliche Tonhöhenbezeichnung; Helmholtz',
      },
      body: {
        en: 'Optional reference for reading another naming tradition: German H is English B natural, while German B is English B-flat. Scientific C4 and Helmholtz c′ identify middle C; Russian names that register the first octave. These correspondences compare written systems, not different sounds. Ordinary lessons teach the system of the selected language.',
        ru: 'Необязательная справка для чтения другой традиции: немецкая H — си, немецкая B — си-бемоль; в английской системе B — си, B-flat — си-бемоль. До первой октавы соответствует научному C4 и обозначению Гельмгольца c′. Сопоставляются системы записи, а не разные звуки. Обычные уроки используют систему выбранного языка.',
        de: 'Optionale Hilfe zum Lesen einer anderen Tradition: Deutsches H entspricht englischem B natural, deutsches B dem englischen B-flat. Das wissenschaftliche C4 und Helmholtz’ c′ bezeichnen dasselbe mittlere C; die russische Tradition nennt diesen Bereich erste Oktave. Verglichen werden Schreibsysteme, nicht verschiedene Klänge. Die regulären Lektionen unterrichten das System der gewählten Sprache.',
        ruMarkup:
          'Необязательная справка для чтения другой традиции: немецкая H — [[си]], немецкая B — [[си-бемоль]]; в английской системе B — [[си]], B-flat — [[си-бемоль]]. [[До]] первой октавы соответствует научному C4 и обозначению Гельмгольца c′. Сопоставляются системы записи, а не разные звуки. Обычные уроки используют систему выбранного языка.',
      },
      sourceId: 'source-040',
      furtherSourceIds: ['source-039'],
    },
    {
      id: 'Natural note',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 56,
      reference: false,
      title: {
        en: 'Natural note',
        ru: 'Основная ступень',
        de: 'Stammton',
      },
      body: {
        en: 'A note on an unaltered pitch class: C, D, E, F, G, A or B. These are the white keys of the piano; a natural sign may explicitly restore one after an alteration.',
        ru: 'Звук одной из семи основных ступеней: до, ре, ми, фа, соль, ля или си, без повышения или понижения. Им соответствуют белые клавиши фортепиано. После альтерации основную ступень может восстанавливать знак бекара.',
        de: 'Ein Ton der unveränderten Stammtonreihe C, D, E, F, G, A, H. Diesen Tönen entsprechen die weißen Klaviertasten; ein Auflösungszeichen kann nach einer Veränderung den Stammton wiederherstellen.',
        ruMarkup:
          'Звук одной из семи основных ступеней: [[до]], [[ре]], [[ми]], [[фа]], [[соль]], [[ля]] или [[си]], без повышения или понижения. Им соответствуют белые клавиши фортепиано. После альтерации основную ступень может восстанавливать знак бекара.',
      },
      sourceId: 'source-039',
    },
    {
      id: 'Note name',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 57,
      reference: false,
      title: {
        en: 'Note name',
        ru: 'Название ноты',
        de: 'Tonname',
      },
      body: {
        en: 'A name that identifies a note in every octave at once, not one single pitch.',
        ru: 'Название, которое относится к ноте во всех октавах сразу, а не к одной высоте.',
        de: 'Ein Name, der einen Ton in allen Oktaven zugleich bezeichnet und nicht eine einzelne Tonhöhe.',
      },
      sourceId: 'source-039',
    },
    {
      id: 'Octave register',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 58,
      reference: false,
      title: {
        en: 'Octave register',
        ru: 'Октавный диапазон',
        de: 'Oktavlage',
      },
      body: {
        en: 'An octave-based naming range from C to the B above it, for example C4–B4. Register in a broader musical sense means a region of pitch and need not span exactly one octave.',
        ru: 'Диапазон от до до ближайшего си выше него, используемый для названия октав, например первая октава. Более общее понятие регистра обозначает область высот и не обязано совпадать с одной октавой.',
        de: 'Ein Bereich der Oktavbenennung von C bis zum H darüber, etwa c′–h′. Ein Register im weiteren musikalischen Sinn ist ein Tonhöhenbereich und muss nicht genau eine Oktave umfassen.',
        ruMarkup:
          'Диапазон от [[до]] до ближайшего [[си]] выше него, используемый для названия октав, например первая октава. Более общее понятие регистра обозначает область высот и не обязано совпадать с одной октавой.',
      },
      sourceId: 'source-039',
    },
    {
      id: 'Octave notation',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 59,
      reference: false,
      title: {
        en: 'Octave notation',
        ru: 'Обозначения октав',
        de: 'Oktavbezeichnungen',
      },
      body: {
        en: 'Octave notation distinguishes registers. Scientific pitch uses numbers (C4), Helmholtz notation uses letter case and marks (c′), and Russian tradition uses names such as the first octave. These are different systems for identifying the same pitch.',
        ru: 'Обозначение октавы уточняет высоту ноты. В русской традиции говорят «до первой октавы»; ту же высоту научная система обозначает C4, а система Гельмгольца — c′. Это разные системы обозначений, а не разные ноты.',
        de: 'Oktavbezeichnungen unterscheiden die Tonlagen. Die wissenschaftliche Schreibweise verwendet Zahlen (C4), die Helmholtz-Bezeichnung Groß- und Kleinbuchstaben mit Strichen (c′); die russische Tradition verwendet Oktavnamen. Diese verschiedenen Systeme bezeichnen dieselbe Tonhöhe.',
        ruMarkup:
          'Обозначение октавы уточняет высоту ноты. В русской традиции говорят «[[до]] первой октавы»; ту же высоту научная система обозначает C4, а система Гельмгольца — c′. Это разные системы обозначений, а не разные ноты.',
      },
      sourceId: 'source-001',
    },
    {
      id: 'Middle C',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'note-names',
      order: 60,
      reference: false,
      title: {
        en: 'Middle C',
        ru: 'До первой октавы',
        de: 'Eingestrichenes c',
        ruMarkup: '[[До]] первой октавы',
      },
      body: {
        en: 'The C near the middle of a piano keyboard, written C4. At A4 = 440 Hz in twelve-tone equal temperament, its frequency is about 261.6 Hz; another reference pitch or tuning changes that frequency.',
        ru: 'До в средней части фортепианной клавиатуры, начало первой октавы. При ля первой октавы = 440 Гц в двенадцатиступенном равномерном строе его частота примерно 261,6 Гц; при другой опорной частоте или строе она меняется.',
        de: 'Das c nahe der Klaviaturmitte, geschrieben c′. Bei a′ = 440 Hz in zwölfstufiger gleichstufiger Stimmung liegt es bei etwa 261,6 Hz; ein anderer Bezugston oder eine andere Stimmung verändert diese Frequenz.',
        ruMarkup:
          '[[До]] в средней части фортепианной клавиатуры, начало первой октавы. При [[ля]] первой октавы = 440 Гц в двенадцатиступенном равномерном строе его частота примерно 261,6 Гц; при другой опорной частоте или строе она меняется.',
      },
      sourceId: 'source-040',
    },
  ],
};
export default content;
