import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'repeats',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['sound', 'tempo', 'chords'],
    locales: ['en', 'ru', 'de'],
    kind: 'concept',
    module: 'N02',
    roadmapIds: ['127'],
    lessonIds: ['repeats'],
    experimentIds: ['repeats'],
    exerciseIds: ['follow-repeat-route'],
    conceptIds: [
      'Tremolo notation',
      'Simile',
      'Figured bass',
      'Segue',
      'double bar',
      'final bar line',
      'repeat sign',
      'first and second endings',
      'da capo',
      'segno',
      'dal segno',
      'fine',
    ],
  },
  lesson: {
    id: 'repeats',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'repeats',
    title: {
      en: 'Printed order, played order',
      ru: 'Повторы и порядок исполнения',
      de: 'Wiederholungen und Spielreihenfolge',
    },
    category: {
      en: 'Performance',
      ru: 'Исполнение',
      de: 'Vortrag',
    },
    summary: {
      en: 'Trace repeats, alternate endings and return instructions before playing.',
      ru: 'Проследите повторы, вольты и возвраты перед исполнением.',
      de: 'Verfolge Wiederholungen, Klammern und Sprunganweisungen vor dem Spielen.',
    },
    formula: {
      en: '‖: … :‖ · [1.] [2.] · D.C. al fine · D.S. al fine',
      ru: '‖: … :‖ · [1.] [2.] · D.C. al fine · D.S. al fine',
      de: '‖: … :‖ · [1.] [2.] · D.C. al fine · D.S. al fine',
    },
    paragraphs: [
      {
        en: 'A double bar divides one section from the next; a thin line followed by a thick one ends the piece. A repeat sign is a double bar with two dots, and the dots face the music to be played again. When two repeated sections meet, the two signs share a single bar line.',
        ru: 'Двойная тактовая черта отделяет один раздел от другого; тонкая черта с последующей жирной завершает пьесу. Знак репризы — двойная черта с двумя точками, обращёнными к тому, что играется повторно. Когда два повторяемых раздела соседствуют, оба знака делят одну черту.',
        de: 'Ein Doppelstrich trennt einen Abschnitt vom nächsten; ein dünner Strich mit folgendem dicken beendet das Stück. Das Wiederholungszeichen ist ein Doppelstrich mit zwei Punkten, wobei die Punkte zu der Musik zeigen, die noch einmal erklingt. Treffen zwei zu wiederholende Abschnitte aufeinander, teilen sich beide Zeichen einen Strich.',
      },
      {
        en: 'Play ending 1 before the repeat, then skip it and take ending 2. Da capo returns to the beginning; dal segno returns to the segno. Al Fine means stop at Fine on the return; al Coda instead directs a transfer to the coda at its indicated point. Read the complete instruction before tracing the route.',
        ru: 'Перед повтором сыграйте первую вольту, затем пропустите её и перейдите ко второй. Da capo возвращает к началу, dal segno — к сеньо. Al Fine означает остановиться у Fine после возврата; al Coda — перейти в коду в указанном месте. Прослеживайте путь, прочитав указание целиком.',
        de: 'Spiele vor der Wiederholung die erste Klammer, überspringe sie danach und nimm die zweite. Da capo führt zum Anfang, dal segno zum Segno. Al Fine verlangt beim Rücklauf den Schluss bei Fine; al Coda stattdessen den Sprung zur Coda an der bezeichneten Stelle. Lies die vollständige Anweisung, bevor du den Weg verfolgst.',
      },
    ],
    sourceId: 'source-056',
    experimentId: 'repeats',
    reading: {
      pages: '18–22',
      sourceId: 'source-016',
      text: {
        en: 'Trace a route before playing: for a body A with endings B and C, repeat signs and first/second endings give A–B–A–C. D.C. returns to the beginning, D.S. to the segno; al Fine or al Coda supplies the stopping or transfer instruction. A percent repeat substitutes a previous measure; tremolo slashes abbreviate repetitions. simile asks you to continue the established manner.',
        ru: 'Перед исполнением проследите путь: основной участок А с окончаниями Б и В под первой и второй вольтами даёт А–Б–А–В. D.C. возвращает к началу, D.S. — к сеньо; al Fine или al Coda уточняет остановку или переход. Знак повторения такта заменяет предыдущий такт; черты тремоло сокращают запись повторений. Simile предлагает продолжать установленный способ исполнения.',
        de: 'Verfolge vor dem Spielen den Weg: Ein Abschnitt A mit den Endungen B und C unter erster und zweiter Klammer ergibt A–B–A–C. D.C. führt zum Anfang, D.S. zum Segno; al Fine oder al Coda bestimmt Halt oder Weiterleitung. Ein Taktwiederholungszeichen ersetzt den vorigen Takt; Tremolostriche kürzen Wiederholungen ab. Simile verlangt die Fortsetzung der etablierten Spielweise.',
      },
      assetIds: [
        'figure-tremolo',
        'figure-repeat-volta',
        'figure-repeat-implicit',
        'figure-repeat-dc-fine',
        'figure-repeat-ds-coda',
        'figure-repeat-abbreviation',
        'figure-tremolo-two',
      ],
    },
  },
  experiment: {
    id: 'repeats',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'repeats',
    instructions: {
      en: 'Play the four-note figure, then compare its repeat with the version that changes the ending. Each repeated example has eight attacks; listen for the last pitch.',
      ru: 'Проиграйте фигуру из четырёх нот, затем сравните её повтор с вариантом, где изменено окончание. В каждом примере с повтором восемь атак; вслушайтесь в последнюю высоту.',
      de: 'Spiele die Figur aus vier Tönen und vergleiche ihre Wiederholung mit der Fassung mit geändertem Schluss. Beide Wiederholungsbeispiele haben acht Einsätze; achte auf den letzten Ton.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 391.995436,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'repeats',
    },
  },
  exercises: [
    {
      id: 'follow-repeat-route',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      label: {
        en: 'Read repeats and abbreviations',
        ru: 'Повторы и сокращения нотной записи',
        de: 'Wiederholungen und Abbreviaturen lesen',
      },
      generator: 'performance-marks',
      sourceIds: ['source-016'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Tremolo notation',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 14,
      reference: true,
      title: {
        en: 'Tremolo notation',
        ru: 'Запись тремоло',
        de: 'Tremolonotation',
      },
      body: {
        en: 'Stem slashes abbreviate repeated notes; strokes between notes can indicate alternation. Distinguish measured and unmeasured instructions.',
        ru: 'Черты на штиле сокращённо обозначают повторение звука; черты между нотами — чередование звуков. Различайте тремоло с точно заданным ритмом и тремоло без точного числа повторений.',
        de: 'Halsstriche kürzen Tonwiederholungen ab; Striche zwischen Noten können einen Wechsel anzeigen. Unterscheide gemessene und ungemessene Angaben.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'Simile',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 15,
      reference: true,
      title: {
        en: 'Simile',
        ru: 'Симиле',
        de: 'Simile',
      },
      body: {
        en: 'Continue in the same manner; the context tells you whether this concerns articulation, accompaniment or another pattern.',
        ru: 'Продолжайте тем же способом; контекст определяет, касается ли это артикуляции, сопровождения или другого рисунка.',
        de: 'In gleicher Weise fortfahren; der Kontext bestimmt, ob Artikulation, Begleitung oder ein anderes Muster gemeint ist.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Figured bass',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 17,
      reference: true,
      title: {
        en: 'Figured bass',
        ru: 'Цифрованный бас',
        de: 'Generalbass',
      },
      body: {
        en: 'Figures attached to a bass indicate intervals for a harmonic realization. They are not interchangeable with modern chord symbols.',
        ru: 'Цифры при басовом голосе указывают интервалы над басом, по которым исполнитель строит остальные голоса. Например, цифра 6 указывает сексту над басом. Эти обозначения нельзя напрямую заменять современными буквенными обозначениями аккордов.',
        de: 'Ziffern zu einer Bassstimme geben Intervalle für die harmonische Aussetzung an. Sie sind nicht mit heutigen Akkordsymbolen austauschbar.',
      },
      aliases: {
        en: 'thoroughbass',
        ru: 'генерал-бас',
        de: 'bezifferter Bass',
      },
      forwardModules: ['H04'],
      relatedTopics: ['chords'],
      sourceId: 'source-006',
    },
    {
      id: 'Segue',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 40,
      reference: true,
      title: {
        en: 'Segue',
        ru: 'Сегве',
        de: 'Segue',
      },
      body: {
        en: 'Segue asks you to continue. In a repeated-pattern context it can maintain an established manner, as simile does; in a transition it may require continuation without a break. Determine what continues from the surrounding instruction, not from the word alone.',
        ru: 'Segue означает «продолжайте». При повторяющемся рисунке оно может сохранять установленную манеру, подобно simile; при переходе — требовать продолжения без перерыва. Что именно продолжается, определяют по окружающему указанию, а не по одному слову.',
        de: 'Segue bedeutet weiterführen. Bei einem wiederkehrenden Muster kann es wie simile die bisherige Art fortsetzen; bei einem Übergang kann es eine Fortsetzung ohne Unterbrechung verlangen. Was weitergeführt wird, ergibt sich aus der umgebenden Anweisung.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'double bar',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 133,
      reference: false,
      title: {
        en: 'Double bar',
        ru: 'Двойная тактовая черта',
        de: 'Doppelstrich',
      },
      body: {
        en: 'A double bar is two thin lines marking the end of a section rather than the end of the piece.',
        ru: 'Двойная тактовая черта — две тонкие линии, отмечающие конец раздела, а не конец пьесы.',
        de: 'Der Doppelstrich besteht aus zwei dünnen Strichen und markiert das Ende eines Abschnitts, nicht das des Stücks.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'final bar line',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 134,
      reference: false,
      title: {
        en: 'Final bar line',
        ru: 'Заключительная черта',
        de: 'Schlussstrich',
      },
      body: {
        en: 'A thin line followed by a thick one marks the end of the piece or movement.',
        ru: 'Тонкая линия с последующей жирной отмечает конец пьесы или части.',
        de: 'Ein dünner Strich mit folgendem dicken Strich beendet das Stück oder den Satz.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'repeat sign',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 135,
      reference: false,
      title: {
        en: 'Repeat sign',
        ru: 'Знак репризы',
        de: 'Wiederholungszeichen',
      },
      body: {
        en: 'A repeat sign is a double bar with two dots, and the dots face the music to be played again.',
        ru: 'Знак репризы — двойная черта с двумя точками, обращёнными к музыке, которую играют повторно.',
        de: 'Das Wiederholungszeichen ist ein Doppelstrich mit zwei Punkten, die zu der noch einmal zu spielenden Musik zeigen.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'first and second endings',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 136,
      reference: false,
      title: {
        en: 'First and second endings',
        ru: 'Вольты',
        de: 'Wiederholungsklammer',
      },
      body: {
        en: 'First and second endings are bracketed bars that give the repeat a different continuation.',
        ru: 'Вольты — отмеченные скобками такты, дающие повторению другое продолжение.',
        de: 'Wiederholungsklammern sind eingeklammerte Takte, die der Wiederholung einen anderen Fortgang geben.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'da capo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 137,
      reference: false,
      title: {
        en: 'Da capo',
        ru: 'Da capo',
        de: 'Da capo',
      },
      body: {
        en: 'Da capo sends the reader back to the beginning of the piece.',
        ru: 'Da capo отсылает исполнителя к началу пьесы.',
        de: 'Da capo führt zum Anfang des Stücks zurück.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'segno',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 138,
      reference: false,
      title: {
        en: 'Segno',
        ru: 'Сеньо',
        de: 'Segno',
      },
      body: {
        en: 'The segno is the sign that marks the place a dal segno returns to.',
        ru: 'Сеньо — знак, отмечающий место, к которому возвращает указание dal segno.',
        de: 'Das Segno ist das Zeichen, zu dem ein dal segno zurückführt.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'dal segno',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 139,
      reference: false,
      title: {
        en: 'Dal segno',
        ru: 'Dal segno',
        de: 'Dal segno',
      },
      body: {
        en: 'Dal segno sends the reader back to the segno rather than to the beginning.',
        ru: 'Dal segno отсылает не к началу, а к знаку сеньо.',
        de: 'Dal segno führt nicht zum Anfang, sondern zum Segno zurück.',
      },
      sourceId: 'source-016',
    },
    {
      id: 'fine',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'repeats',
      order: 140,
      reference: false,
      title: {
        en: 'Fine',
        ru: 'Fine',
        de: 'Fine',
      },
      body: {
        en: 'Fine marks where the piece stops after a da capo or dal segno return.',
        ru: 'Fine отмечает место остановки после возврата по da capo или dal segno.',
        de: 'Fine bezeichnet die Stelle, an der das Stück nach der Rückkehr durch da capo oder dal segno endet.',
      },
      sourceId: 'source-016',
    },
  ],
};
export default content;
