import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'staff',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['note-names'],
    locales: ['en', 'ru', 'de'],
    kind: 'sign',
    module: 'F03',
    roadmapIds: ['012'],
    lessonIds: ['staff'],
    experimentIds: ['staff'],
    exerciseIds: ['read-a-notated-pitch', 'read-a-short-excerpt'],
    conceptIds: [
      'Tablature',
      'Graphic notation',
      'Why extend notation?',
      'Staff',
      'Staff line',
      'Space',
      'Note head',
      'Stem',
      'Ledger line',
    ],
  },
  lesson: {
    id: 'staff',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'staff',
    title: {
      en: 'Five lines, four spaces',
      ru: 'Пять линеек, четыре промежутка',
      de: 'Fünf Linien, vier Zwischenräume',
    },
    category: {
      en: 'Notation',
      ru: 'Нотация',
      de: 'Notenschrift',
    },
    summary: {
      en: 'Locate notes on lines, in spaces and on ledger lines.',
      ru: 'Находите ноты на линейках, в промежутках и на добавочных линейках.',
      de: 'Finde Noten auf Linien, in Zwischenräumen und auf Hilfslinien.',
    },
    formula: {
      en: '5 lines + 4 spaces = 9 places · one place above and one below = 11 · counted from the bottom',
      ru: '5 линеек + 4 промежутка = 9 мест · плюс место над станом и под ним = 11 · счёт снизу вверх',
      de: '5 Linien + 4 Zwischenräume = 9 Plätze · je ein Platz darüber und darunter = 11 · von unten gezählt',
    },
    paragraphs: [
      {
        en: 'A staff is five parallel lines with four spaces between them, nine places in all. Lines and spaces are both counted from the bottom: the lowest line is the first line, the lowest space the first space. A note head sits on a line, crossed by it, or inside a space.',
        ru: 'Нотный стан — пять параллельных линеек и четыре промежутка между ними, всего девять мест. И линейки, и промежутки считают снизу вверх: нижняя линия — первая линейка, нижний промежуток — первый промежуток. Головка ноты стоит либо на линейке, которая её пересекает, либо внутри промежутка.',
        de: 'Das Notensystem besteht aus fünf waagerechten Linien und vier Zwischenräumen, zusammen neun Plätzen. Beide werden von unten nach oben gezählt: die unterste Linie ist die erste Linie, der unterste Zwischenraum der erste Zwischenraum. Ein Notenkopf steht auf einer Linie, die ihn durchschneidet, oder in einem Zwischenraum.',
      },
      {
        en: 'The places just above and below the staff bring the total to eleven before ledger lines are needed. Beyond them, short ledger lines continue the same alternation of lines and spaces: the next diatonic step does not always need another line. Notes are read left to right; vertically aligned notes sound together.',
        ru: 'Места сразу над пятой линейкой и под первой дают всего одиннадцать позиций без добавочных линеек. Дальше чередование линеек и промежутков продолжается. Например, над скрипичным станом ля второй октавы стоит на первой добавочной линейке, си — в промежутке над ней, до третьей — на второй добавочной. Ноты читают слева направо; выстроенные по вертикали ноты звучат одновременно.',
        de: 'Die Plätze unmittelbar über und unter dem System ergeben insgesamt elf Positionen ohne Hilfslinien. Außerhalb setzen kurze Hilfslinien den Wechsel von Linien und Zwischenräumen fort: Nicht jeder nächste diatonische Schritt braucht eine weitere Linie. Noten werden von links nach rechts gelesen; senkrecht ausgerichtete Noten erklingen gleichzeitig.',
        ruMarkup:
          'Места сразу над пятой линейкой и под первой дают всего одиннадцать позиций без добавочных линеек. Дальше чередование линеек и промежутков продолжается. Например, над скрипичным станом [[ля]] второй октавы стоит на первой добавочной линейке, [[си]] — в промежутке над ней, [[до]] третьей — на второй добавочной. Ноты читают слева направо; выстроенные по вертикали ноты звучат одновременно.',
      },
    ],
    sourceId: 'source-038',
    experimentId: 'staff',
    reading: {
      pages: '1, 4–6',
      sourceId: 'source-017',
      text: {
        en: 'Count five lines from the bottom, with four spaces between them. Ledger lines continue the same alternation. Read successive events from left to right; aligned notes in different voices share an onset. In the placement exercise, move one staff step at a time before naming the result.',
        ru: 'Пять линеек считают снизу; между ними четыре промежутка. Добавочные линейки продолжают тот же порядок. Последовательность читают слева направо; вертикальное совмещение нот разных голосов показывает общее время вступления. В упражнении на постановку перемещайтесь по одной позиции стана и называйте результат.',
        de: 'Die fünf Linien werden von unten gezählt; dazwischen liegen vier Zwischenräume. Hilfslinien setzen diese Folge fort. Zeitlich aufeinanderfolgende Ereignisse liest man von links nach rechts; senkrecht ausgerichtete Noten verschiedener Stimmen haben denselben Einsatz. Bewege die Note in der Setzübung jeweils um eine Linien- oder Zwischenraumposition.',
      },
      assetIds: [],
    },
  },
  experiment: {
    id: 'staff',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'staff',
    instructions: {
      en: 'Compare the two pitch examples: C4 and G4 one after another, then together. Relate what you hear to the order and alignment of notes on the staff.',
      ru: 'Сравните два примера: до и соль первой октавы по очереди, затем одновременно. Соотнесите услышанное с порядком и вертикальным расположением нот на стане.',
      de: 'Vergleiche die Tonhöhenbeispiele: c′ und g′ nacheinander, dann gleichzeitig. Vergleiche das Gehörte mit der Reihenfolge und vertikalen Anordnung der Noten im Notensystem.',
      ruMarkup:
        'Сравните два примера: [[до]] и [[соль]] первой октавы по очереди, затем одновременно. Соотнесите услышанное с порядком и вертикальным расположением нот на стане.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 261.625565,
      wave: 'triangle',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'pitch',
    },
  },
  exercises: [
    {
      id: 'read-a-notated-pitch',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      label: {
        en: 'Read a note on the staff',
        ru: 'Чтение ноты на стане',
        de: 'Einen notierten Ton lesen',
      },
      generator: 'read-pitch',
      sourceIds: ['source-017'],
      kind: 'generated',
    },
    {
      id: 'read-a-short-excerpt',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      label: {
        en: 'Read a short musical passage',
        ru: 'Чтение короткого нотного фрагмента',
        de: 'Einen kurzen Notenausschnitt lesen',
      },
      generator: 'short-excerpt',
      sourceIds: ['source-017'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Tablature',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 16,
      reference: true,
      title: {
        en: 'Tablature',
        ru: 'Табулатура',
        de: 'Tabulatur',
      },
      body: {
        en: 'Instrument-specific notation can show strings and frets rather than staff pitches. Read its tuning and legend; tablature is not one universal system.',
        ru: 'Инструментальная запись может показывать струны и лады вместо высот на стане. Проверьте настройку и условные обозначения; табулатура — не единая универсальная система.',
        de: 'Instrumentbezogene Notation kann Saiten und Bünde statt Tonhöhen im Liniensystem zeigen. Prüfe Stimmung und Zeichenerklärung; Tabulatur ist kein einheitliches Universalsystem.',
      },
      forwardModules: ['N05'],
      sourceId: 'source-007',
    },
    {
      id: 'Graphic notation',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 18,
      reference: true,
      title: {
        en: 'Graphic notation',
        ru: 'Графическая нотация',
        de: 'Grafische Notation',
      },
      body: {
        en: 'A score may use shapes, spatial relationships or action instructions. Read its own legend; horizontal space means elapsed time only when specified. Some choices may deliberately remain open.',
        ru: 'Партитура может использовать формы, пространственные отношения или инструкции действий. Читайте её условные обозначения: расстояние означает время только при соответствующем указании. Некоторые решения могут намеренно оставаться открытыми.',
        de: 'Eine Partitur kann Formen, räumliche Beziehungen oder Handlungsanweisungen verwenden. Lies ihre eigene Legende: horizontaler Abstand bedeutet nur bei entsprechender Festlegung verstrichene Zeit. Manche Entscheidungen bleiben absichtlich offen.',
      },
      forwardModules: ['N05'],
      sourceId: 'source-005',
    },
    {
      id: 'Why extend notation?',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 42,
      reference: true,
      title: {
        en: 'Why extend notation?',
        ru: 'Зачем расширять нотацию?',
        de: 'Warum Notation erweitern?',
      },
      aliases: {
        en: 'proportional notation; action notation; microtones; clusters; open score',
        ru: 'пропорциональная нотация; нотация действий; микроинтервалы; кластеры; открытая форма',
        de: 'proportionale Notation; Aktionsschrift; Mikrointervalle; Cluster; offene Partitur',
      },
      body: {
        en: 'A composer may need to indicate an action, a sound mass, pitches outside a conventional scale, or timing without a regular beat. Ordinary noteheads and barlines may then need additional signs or a different layout. A graphic score can specify some choices and leave others open. Its legend decides whether distance means elapsed time, gesture or something else; this is not a single replacement system for all music.',
        ru: 'Композитору может понадобиться обозначить действие, звуковую массу, высоты вне привычного звукоряда или время без регулярного пульса. Тогда обычные головки и тактовые черты дополняются знаками или иной организацией страницы. Графическая партитура может закреплять одни решения и оставлять другие открытыми. Её пояснения определяют, означает ли расстояние время, жест или что-то другое; это не единая замена всей музыкальной записи.',
        de: 'Ein Komponist kann eine Handlung, eine Klangmasse, Tonhöhen außerhalb einer gewohnten Skala oder Zeit ohne regelmäßigen Puls bezeichnen wollen. Gewöhnliche Notenköpfe und Taktstriche benötigen dann Ergänzungen oder eine andere Anordnung. Eine grafische Partitur kann einige Entscheidungen festlegen und andere offenlassen. Ihre Legende bestimmt, ob Abstand Zeit, Geste oder anderes bedeutet; sie ist kein einheitlicher Ersatz für jede Musik.',
      },
      forwardModules: ['N05'],
      sourceId: 'source-005',
      furtherSourceIds: ['source-023', 'source-035'],
    },
    {
      id: 'Staff',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 61,
      reference: false,
      title: {
        en: 'Staff',
        ru: 'Нотный стан',
        de: 'Notensystem',
      },
      body: {
        en: 'The staff is the set of five lines and four spaces on which pitches are written.',
        ru: 'Нотный стан, или нотоносец, — пять линеек и четыре промежутка, на которых записываются высоты.',
        de: 'Das Notensystem ist die Folge von fünf Linien und vier Zwischenräumen, auf denen Tonhöhen notiert werden.',
      },
      sourceId: 'source-038',
    },
    {
      id: 'Staff line',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 62,
      reference: false,
      title: {
        en: 'Staff line',
        ru: 'Линейка',
        de: 'Notenlinie',
      },
      body: {
        en: 'A staff line is one of the five lines, numbered from the bottom upwards.',
        ru: 'Линейка — одна из пяти линий стана; их нумеруют снизу вверх.',
        de: 'Eine Notenlinie ist eine der fünf Linien, die von unten nach oben gezählt werden.',
      },
      sourceId: 'source-038',
    },
    {
      id: 'Space',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 63,
      reference: false,
      title: {
        en: 'Space',
        ru: 'Межлинейный промежуток',
        de: 'Zwischenraum',
      },
      body: {
        en: 'A space is the gap between two neighbouring lines, and it carries a note head just as a line does.',
        ru: 'Промежуток — расстояние между соседними линейками, и нота размещается на нём так же, как на линейке.',
        de: 'Ein Zwischenraum liegt zwischen zwei benachbarten Notenlinien und trägt einen Notenkopf ebenso wie eine Linie.',
      },
      sourceId: 'source-038',
    },
    {
      id: 'Note head',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 64,
      reference: false,
      title: {
        en: 'Note head',
        ru: 'Головка ноты',
        de: 'Notenkopf',
      },
      body: {
        en: 'The note head is the oval whose centre marks the line or space that gives the pitch.',
        ru: 'Головка ноты — овал, центр которого указывает линейку или промежуток и тем самым высоту.',
        de: 'Der Notenkopf ist das Oval, dessen Mitte die Linie oder den Zwischenraum und damit die Tonhöhe angibt.',
      },
      sourceId: 'source-038',
    },
    {
      id: 'Stem',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 65,
      reference: false,
      title: {
        en: 'Stem',
        ru: 'Штиль',
        de: 'Notenhals',
      },
      body: {
        en: 'The stem is the vertical line attached to the head; it belongs to duration, not to pitch.',
        ru: 'Штиль — вертикальная черта у головки; он относится к длительности, а не к высоте.',
        de: 'Der Notenhals ist der senkrechte Strich am Notenkopf; er gehört zur Dauer, nicht zur Tonhöhe.',
      },
      sourceId: 'source-024',
    },
    {
      id: 'Ledger line',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'staff',
      order: 66,
      reference: false,
      title: {
        en: 'Ledger line',
        ru: 'Добавочная линейка',
        de: 'Hilfslinie',
      },
      body: {
        en: 'A ledger line is a short line added above or below the staff to carry pitches beyond its eleven places.',
        ru: 'Добавочная линейка — короткая линия над станом или под ним, продолжающая его за пределы одиннадцати мест.',
        de: 'Eine Hilfslinie ist eine kurze Linie über oder unter dem Notensystem, die es über seine elf Plätze hinaus fortsetzt.',
      },
      sourceId: 'source-038',
    },
  ],
};
export default content;
