import type { TopicBundle } from '../schema';

const content: TopicBundle = {
  topic: {
    id: 'tempo',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: ['staff'],
    locales: ['en', 'ru', 'de'],
    kind: 'measure',
    module: 'F04',
    roadmapIds: ['019'],
    lessonIds: ['tempo'],
    experimentIds: ['tempo'],
    exerciseIds: ['metronome-unit'],
    conceptIds: [
      'Metronome history',
      'Tempo words',
      'Tempo I',
      'Slow and moderate tempo words',
      'Lively and fast tempo words',
      'Qualifying a direction',
      'Tempo changes and agogics',
      'Tempo',
      'Metronome mark',
      'Beats per minute',
      'Accelerando',
      'Ritardando',
      'A tempo',
      'Fermata',
      'Agogics',
    ],
  },
  lesson: {
    id: 'tempo',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'tempo',
    title: {
      en: 'Tempo and its marks',
      ru: 'Темп и его обозначения',
      de: 'Tempo und seine Zeichen',
    },
    category: {
      en: 'Performance',
      ru: 'Исполнение',
      de: 'Vortrag',
    },
    summary: {
      en: 'Read tempo words and calculate a note’s duration from a metronome mark.',
      ru: 'Понимайте темповые обозначения и вычисляйте длительность по метроному.',
      de: 'Verstehe Tempowörter und berechne eine Dauer aus der Metronomangabe.',
    },
    formula: {
      en: '♩ = 120 → one quarter = 0.5 s',
      ru: '♩ = 120 → одна четверть = 0,5 с',
      de: '♩ = 120 → eine Viertel = 0,5 s',
    },
    paragraphs: [
      {
        en: 'Tempo describes how quickly the musical pulse moves. Italian words often suggest both speed and character: Adagio is slow, Andante suggests a walking pace, Moderato a moderate pace, and Allegro a lively, usually fast movement. These descriptions overlap; they are not exact BPM ranges. Follow later tempo changes and the context of the piece.',
        ru: 'Темп — скорость движения музыкального пульса. Итальянские слова часто передают и скорость, и характер: Adagio — медленно, Andante — в темпе шага, Moderato — умеренно, Allegro — оживлённо, обычно быстро. Эти значения пересекаются и не задают точных диапазонов метронома. Учитывайте последующие изменения темпа и характер произведения.',
        de: 'Tempo bezeichnet die Geschwindigkeit des musikalischen Pulses. Italienische Wörter geben oft Tempo und Charakter an: Adagio bedeutet langsam, Andante etwa im Gehtempo, Moderato mäßig und Allegro lebhaft, meist schnell. Diese Beschreibungen überschneiden sich und sind keine exakten BPM-Bereiche. Beachte spätere Tempoänderungen und den Zusammenhang des Stücks.',
      },
      {
        en: 'A metronome mark pairs a note value with a number: ♩ = 120 means 120 quarter notes per minute, so one quarter lasts 60 / 120 = 0.5 seconds. Accelerando asks for a gradual acceleration; ritardando for a gradual slowing. A tempo returns to the preceding tempo, while Tempo I returns to the initial tempo. A fermata prolongs a note or rest without a fixed multiplier; its length depends on the musical context.',
        ru: 'Метрономическое обозначение соединяет длительность и число: ♩ = 120 означает 120 четвертей в минуту, поэтому одна четверть длится 60 / 120 = 0,5 секунды. Accelerando предписывает постепенное ускорение, ritardando — замедление. A tempo возвращает предшествующий темп, а Tempo I — первоначальный. Фермата продлевает ноту или паузу без фиксированного множителя; степень продления зависит от музыкального контекста.',
        de: 'Eine Metronomangabe verbindet einen Notenwert mit einer Zahl: ♩ = 120 bedeutet 120 Viertelnoten pro Minute; eine Viertel dauert also 60 / 120 = 0,5 Sekunden. Accelerando verlangt allmähliches Beschleunigen, ritardando allmähliches Verlangsamen. A tempo führt zum vorigen Tempo zurück, Tempo I zum Anfangstempo. Eine Fermate verlängert eine Note oder Pause ohne festen Faktor; ihre Dauer richtet sich nach dem musikalischen Zusammenhang.',
      },
    ],
    sourceId: 'source-053',
    experimentId: 'tempo',
    reading: {
      pages: '23–26',
      sourceId: 'source-013',
      text: {
        en: 'Always read the note unit next to the metronome number. At quarter = 60 one quarter lasts one second; at eighth = 60 one eighth lasts one second. a tempo returns to the preceding tempo; Tempo I to the initial one. A fermata suspends regular timing without specifying a fixed multiplier. Tempo words also carry character and cannot be ranked as exact BPM values.',
        ru: 'Всегда читайте длительность рядом с числом метронома. При четверть = 60 четверть длится секунду; при восьмая = 60 секунду длится восьмая. A tempo возвращает предыдущий темп, Tempo I — первоначальный. Фермата нарушает регулярный отсчёт, не задавая точного множителя длительности. Темповые слова передают и характер, поэтому их нельзя ранжировать как точные значения метронома.',
        de: 'Lies stets den Notenwert neben der Metronomzahl. Bei Viertel = 60 dauert eine Viertel eine Sekunde; bei Achtel = 60 eine Achtel. a tempo führt zum vorigen Tempo zurück, Tempo I zum Anfangstempo. Eine Fermate unterbricht das regelmäßige Zeitmaß ohne festen Verlängerungsfaktor. Tempowörter tragen auch Ausdruck und bilden keine exakte BPM-Rangfolge.',
      },
      assetIds: ['figure-tempo-return'],
    },
  },
  experiment: {
    id: 'tempo',
    version: 1,
    scopeId: 'western-notation',
    prerequisites: [],
    locales: ['en', 'ru', 'de'],
    topicId: 'tempo',
    instructions: {
      en: 'Choose ♩ = 60 and play Four steady beats, then repeat at ♩ = 120. Count four beats each time and compare their spacing.',
      ru: 'Выберите ♩ = 60 и запустите «Четыре ровные доли», затем повторите при ♩ = 120. Каждый раз отсчитайте четыре доли и сравните расстояние между атаками.',
      de: 'Wähle ♩ = 60 und spielen Sie vier gleichmäßige Zählzeiten, dann wiederhole bei ♩ = 120. Zähle jeweils vier Zählzeiten und vergleiche die Abstände der Einsätze.',
    },
    engine: 'sound-lab',
    preset: {
      hz: 440,
      wave: 'sine',
    },
    notation: {
      note: {
        letter: 0,
        accidental: 0,
        octave: 4,
      },
      group: 'tempo',
    },
  },
  exercises: [
    {
      id: 'metronome-unit',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      label: {
        en: 'Read tempo and metronome marks',
        ru: 'Темп и метрономические обозначения',
        de: 'Tempo- und Metronomangaben lesen',
      },
      generator: 'performance-marks',
      sourceIds: ['source-013'],
      kind: 'generated',
    },
  ],
  concepts: [
    {
      id: 'Metronome history',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 0,
      reference: true,
      title: {
        en: 'Metronome history',
        ru: 'История метронома',
        de: 'Geschichte des Metronoms',
      },
      aliases: {
        en: 'Mälzel; Maelzel; Winkel; M.M.',
        ru: 'Мельцель; Винкель; М. М.',
        de: 'Mälzel; Maelzel; Winkel; M. M.',
      },
      body: {
        en: 'M.M. refers to Mälzel’s metronome. The development of the portable mechanical instrument involved both Winkel and Mälzel; Brian Blood’s account distinguishes technical improvements from Mälzel’s wider commercialization and reports disputed priority. In a score, the practical information remains the marked note value and its count per minute.',
        ru: 'М. М. отсылает к метроному Мельцеля. В создании переносного механического прибора участвовали Винкель и Мельцель; Брайан Блад различает технические усовершенствования и широкое распространение прибора Мельцелем, отмечая спор о первенстве. Для чтения нот главное — указанная длительность и число её отсчётов в минуту.',
        de: 'M. M. verweist auf Mälzels Metronom. An der Entwicklung des tragbaren mechanischen Geräts waren Winkel und Mälzel beteiligt; Brian Blood unterscheidet technische Verbesserungen von Mälzels breiter Vermarktung und berichtet von umstrittener Priorität. Für das Notenlesen zählen der angegebene Notenwert und seine Anzahl pro Minute.',
      },
      sourceId: 'source-013',
    },
    {
      id: 'Tempo words',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 2,
      reference: true,
      title: {
        en: 'Tempo words',
        ru: 'Словесные обозначения темпа',
        de: 'Tempowörter',
      },
      body: {
        en: 'Largo suggests breadth; Adagio a slow pace; Allegro liveliness. Più and meno mean more and less; molto and poco qualify the amount. These words describe movement and character, not fixed BPM values.',
        ru: 'Largo — широко; Adagio — медленно; Allegro — оживлённо. Più и meno означают больше и меньше, molto и poco уточняют степень. Слова характеризуют движение и характер, а не фиксированное число ударов в минуту.',
        de: 'Largo bezeichnet Breite, Adagio langsames Tempo, Allegro Lebhaftigkeit. Più und meno bedeuten mehr und weniger; molto und poco bestimmen den Grad. Die Wörter beschreiben Bewegung und Charakter, keine festen Metronomzahlen.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Tempo I',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 22,
      reference: true,
      title: {
        en: 'Tempo I',
        ru: 'Первоначальный темп',
        de: 'Tempo I',
      },
      body: {
        en: 'Return to the initial tempo, which need not be the most recent tempo before a change.',
        ru: 'Возврат к первоначальному темпу, который не обязательно совпадает с последним темпом перед изменением.',
        de: 'Rückkehr zum Anfangstempo, das nicht das unmittelbar vor einer Änderung geltende Tempo sein muss.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Slow and moderate tempo words',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 29,
      reference: true,
      title: {
        en: 'Slow and moderate tempo words',
        ru: 'Медленные и умеренные темпы',
        de: 'Langsame und mäßige Tempowörter',
      },
      aliases: {
        en: 'Largo; Larghetto; Lento; Adagio; Adagietto; Andante; Andantino; Moderato',
        ru: 'ларго; ларгетто; ленто; адажио; адажиетто; анданте; андантино; модерато',
        de: 'Largo; Larghetto; Lento; Adagio; Adagietto; Andante; Andantino; Moderato',
      },
      body: {
        en: 'Largo suggests breadth, Lento slowness, Adagio a slow, settled movement; Andante evokes walking and Moderato moderation. Diminutive forms such as Larghetto, Adagietto and Andantino qualify movement and character, but do not provide a dependable numerical conversion. Read them with the meter, phrase and edition; these overlapping descriptions are not a ranked BPM table.',
        ru: 'Largo передаёт широту, Lento — медленность, Adagio — спокойное медленное движение; Andante напоминает шаг, Moderato указывает на умеренность. Уменьшительные формы Larghetto, Adagietto и Andantino уточняют движение и характер, но не дают надёжного числового пересчёта. Учитывайте размер, фразу и редакцию; это не таблица ранжированных значений метронома.',
        de: 'Largo vermittelt Breite, Lento Langsamkeit, Adagio ruhiges langsames Bewegen; Andante erinnert ans Gehen, Moderato an Mäßigung. Verkleinerungsformen wie Larghetto, Adagietto und Andantino verändern Bewegung und Charakter, liefern aber keine zuverlässige Zahlenumrechnung. Lies sie mit Takt, Phrase und Ausgabe; die Beschreibungen bilden keine BPM-Rangliste.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-013'],
    },
    {
      id: 'Lively and fast tempo words',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 30,
      reference: true,
      title: {
        en: 'Lively and fast tempo words',
        ru: 'Подвижные и быстрые темпы',
        de: 'Lebhafte und schnelle Tempowörter',
      },
      aliases: {
        en: 'Allegro; Allegretto; Allegro molto; Vivace; Vivo; Presto; Prestissimo',
        ru: 'аллегро; аллегретто; виваче; престо; престиссимо',
        de: 'Allegro; Allegretto; Allegro molto; Vivace; Vivo; Presto; Prestissimo',
      },
      body: {
        en: 'Allegro asks for lively, usually fast movement; Allegretto often softens that character. Vivace or vivo emphasizes animation, Presto speed, and Prestissimo extreme speed. Molto intensifies the word it accompanies. None names an exact metronome value or overrides a separately printed note-unit marking.',
        ru: 'Allegro означает оживлённое, обычно быстрое движение; Allegretto часто смягчает этот характер. Vivace или vivo подчёркивает живость, Presto — быстроту, Prestissimo — предельную быстроту. Molto усиливает сопровождаемое слово. Ни одно слово не задаёт точного значения метронома и не отменяет отдельно указанную длительность отсчёта.',
        de: 'Allegro verlangt lebhafte, meist schnelle Bewegung; Allegretto mildert häufig diesen Charakter. Vivace oder vivo betont Lebhaftigkeit, Presto Schnelligkeit, Prestissimo äußerste Schnelligkeit. Molto verstärkt das begleitete Wort. Keines nennt einen exakten Metronomwert oder ersetzt einen ausdrücklich angegebenen Zählwert.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-013'],
    },
    {
      id: 'Qualifying a direction',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 31,
      reference: true,
      title: {
        en: 'Qualifying a direction',
        ru: 'Уточнения исполнительских указаний',
        de: 'Vortragsangaben näher bestimmen',
      },
      aliases: {
        en: 'più; meno; molto; poco; poco a poco; assai; non troppo; quasi; comodo; sostenuto; con moto; con fuoco; appassionato; con passione',
        ru: 'пью; мено; мольто; поко; постепенно; не слишком; выдержанно; с движением; с огнём; страстно',
        de: 'più; meno; molto; poco; poco a poco; assai; non troppo; quasi; comodo; sostenuto; con moto; con fuoco; appassionato; con passione',
      },
      body: {
        en: 'Più and meno mean more and less; molto/assai intensify, poco limits, poco a poco makes a change gradual, and non troppo limits excess. Quasi means “as if”. Comodo suggests ease, sostenuto sustained delivery, con moto movement and con fuoco fire. Appassionato or con passione asks for passion. Identify what each qualifier modifies before changing speed, attack or loudness.',
        ru: 'Più и meno — больше и меньше; molto/assai усиливают, poco ограничивает, poco a poco означает постепенность, non troppo — «не слишком». Quasi — «как бы». Comodo предполагает удобное, непринуждённое движение, sostenuto — выдержанность, con moto — подвижность, con fuoco — огонь. Appassionato или con passione требует страстности. Сначала определите, что уточняется: темп, атака или сила звука.',
        de: 'Più und meno bedeuten mehr und weniger; molto/assai verstärken, poco begrenzt, poco a poco macht eine Änderung allmählich, non troppo begrenzt das Übermaß. Quasi bedeutet „gleichsam“. Comodo legt Bequemlichkeit nahe, sostenuto getragenes Spiel, con moto Bewegung, con fuoco Feuer. Appassionato oder con passione verlangt Leidenschaft. Bestimme zuerst, worauf sich der Zusatz bezieht.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Tempo changes and agogics',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 32,
      reference: true,
      title: {
        en: 'Tempo changes and agogics',
        ru: 'Изменения темпа и агогика',
        de: 'Tempoänderungen und Agogik',
      },
      aliases: {
        en: 'rallentando; ritenuto; allargando; stringendo; stretto; rubato; più mosso; meno mosso; in tempo',
        ru: 'раллентандо; ритенуто; алларгандо; стринджендо; стретто; рубато; более подвижно; менее подвижно',
        de: 'rallentando; ritenuto; allargando; stringendo; stretto; rubato; più mosso; meno mosso; in tempo',
      },
      body: {
        en: 'Ritardando/rallentando slow the motion; ritenuto holds it back, often more immediately. Allargando broadens; stringendo presses forward, and stretto can urge the close onward. Più/meno mosso asks for more/less movement. Rubato permits expressive flexibility, not a new time signature. A tempo returns to the preceding tempo, Tempo I to the initial one; read in tempo as a contextual return to regular time. A spaced-out word or line marks a span, not an automatic reset at every barline.',
        ru: 'Ritardando/rallentando замедляет движение; ritenuto сдерживает его, часто более непосредственно. Allargando расширяет, stringendo подгоняет, stretto может устремлять к завершению. Più/meno mosso — более/менее подвижно. Rubato допускает выразительную свободу времени, но не меняет размер. A tempo возвращает предшествующий темп, Tempo I — первоначальный; in tempo читают как контекстное возвращение к регулярному движению. Растянутое слово или линия обозначает участок, а не автоматическую отмену на каждой тактовой черте.',
        de: 'Ritardando/rallentando verlangsamt; ritenuto hält die Bewegung oft unmittelbarer zurück. Allargando verbreitert, stringendo drängt vorwärts; stretto kann zum Schluss hindrängen. Più/meno mosso verlangt mehr/weniger Bewegung. Rubato erlaubt zeitliche Ausdrucksfreiheit, keinen neuen Takt. A tempo kehrt zum vorigen, Tempo I zum Anfangstempo zurück; in tempo verlangt kontextabhängig wieder regelmäßiges Zeitmaß. Ein auseinandergezogenes Wort oder eine Linie bezeichnet eine Strecke, keinen automatischen Widerruf an jedem Taktstrich.',
      },
      sourceId: 'source-003',
      furtherSourceIds: ['source-013'],
    },
    {
      id: 'Tempo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 111,
      reference: false,
      title: {
        en: 'Tempo',
        ru: 'Темп',
        de: 'Tempo',
      },
      body: {
        en: 'The speed at which the beats of a piece follow one another.',
        ru: 'Скорость, с которой следуют друг за другом доли пьесы.',
        de: 'Die Geschwindigkeit, mit der die Zählzeiten eines Stückes aufeinander folgen.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Metronome mark',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 112,
      reference: false,
      title: {
        en: 'Metronome mark',
        ru: 'Метрономическое обозначение',
        de: 'Metronomzahl',
      },
      body: {
        en: 'A note value with a number, fixing how many such beats fill one minute.',
        ru: 'Длительность с числом, указывающая, сколько таких долей укладывается в минуту.',
        de: 'Ein Notenwert mit einer Zahl, die festlegt, wie viele solcher Schläge auf eine Minute gehen.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Beats per minute',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 113,
      reference: false,
      title: {
        en: 'Beats per minute',
        ru: 'Удары в минуту',
        de: 'Schläge pro Minute',
      },
      body: {
        en: 'The unit of a metronome mark: the count of beats in sixty seconds.',
        ru: 'Единица метрономического обозначения: число долей за шестьдесят секунд.',
        de: 'Die Einheit der Metronomzahl: die Zahl der Schläge in sechzig Sekunden.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Accelerando',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 114,
      reference: false,
      title: {
        en: 'Accelerando',
        ru: 'Accelerando',
        de: 'Accelerando',
      },
      body: {
        en: 'A direction to become gradually faster.',
        ru: 'Указание постепенно ускорять движение.',
        de: 'Die Anweisung, allmählich schneller zu werden.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Ritardando',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 115,
      reference: false,
      title: {
        en: 'Ritardando',
        ru: 'Ritardando',
        de: 'Ritardando',
      },
      body: {
        en: 'A direction to become gradually slower.',
        ru: 'Указание постепенно замедлять движение.',
        de: 'Die Anweisung, allmählich langsamer zu werden.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'A tempo',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 116,
      reference: false,
      title: {
        en: 'A tempo',
        ru: 'A tempo',
        de: 'A tempo',
      },
      body: {
        en: 'A direction to return to the speed that was in force before the change.',
        ru: 'Указание вернуться к темпу, действовавшему до изменения.',
        de: 'Die Anweisung, zum Tempo zurückzukehren, das vor der Änderung galt.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Fermata',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 117,
      reference: false,
      title: {
        en: 'Fermata',
        ru: 'Фермата',
        de: 'Fermate',
      },
      body: {
        en: 'A sign that prolongs a note or rest beyond its written value without specifying a fixed multiplier. The phrase, style and performance context guide the duration.',
        ru: 'Знак продления ноты или паузы сверх записанной длительности без фиксированного множителя. Продолжительность определяется фразой, стилем и исполнительским контекстом.',
        de: 'Ein Zeichen, das eine Note oder Pause über ihren notierten Wert hinaus verlängert, ohne festen Faktor. Phrase, Stil und Aufführungskontext bestimmen die Dauer.',
      },
      sourceId: 'source-003',
    },
    {
      id: 'Agogics',
      version: 1,
      scopeId: 'western-notation',
      prerequisites: [],
      locales: ['en', 'ru', 'de'],
      topicId: 'tempo',
      order: 118,
      reference: false,
      title: {
        en: 'Agogics',
        ru: 'Агогика',
        de: 'Agogik',
      },
      body: {
        en: 'The small changes of speed that shape a performance.',
        ru: 'Небольшие изменения темпа, формирующие исполнение.',
        de: 'Die kleinen Tempoänderungen, die einen Vortrag gestalten.',
      },
      sourceId: 'source-003',
    },
  ],
};
export default content;
